### ISSUE TITLE
2024 programmatically use free software graph database

### ISSUE THREAD

**Issue by brunocek** [neo4j/neo4j-python-driver#1011]
# 2024 programmatically use free software graph database

1. What is the most valuable, free software, graph database, skill set to learn? 

Should the programmatical use of the graph database be python via Bolt protocol on ongdb? Or should the connection use some different protocol?

2. Do we need ongdb?

I recall reading that some queries are not available on neo4j personal (only paid enterprise) and that ongdb was forked to keep it, but unfortunately I cannot find the page where I read this.

( https://neo4j.com/pricing/ )( formaly /editions ) says on the paid professional:

> Support for analytical queries with Parallel Runtime

Does it mean we cannot do some Cypher queries/graph algorithms (unless in paid enterprise)? Are these available in SPARQL? And is it a better choice?

---
My research now shows me only two functional limitations on neo4j personal:

- unable to delete, create and alter databases ( https://stackoverflow.com/questions/23310114/how-to-reset-clear-delete-neo4j-database#comment127325229_60933970 thanks to @james-so)
- 200k vertexes and 400k edges ( https://neo4j.com/pricing/ )

My use case is not impacted by these neo4j personal limitations. On the other hand, at the moment, my research leads me to believe python with [package neo4j]( https://github.com/neo4j/neo4j-python-driver ) and Bolt protocol is the best programmatical use of a free software graph db. Comments on this perception, please?

3. Do ongdb users connect via Bolt 1.7 ? - I was unable to.

The release notes of version 5.1 contains a table of compatibility. It says version 3.5 and 4.0  are the two last ones that support certainly Bolt 1.7.
( https://pypi.org/project/neo4j/5.1.0/ )

Release notes for 4.1 to 5.0 will hold the description of how to use Bolt 1.7, but as we see in 5.1, they actually don't know if it works or not.

I use pipenv on debian, and I was unable to install an older version of python [package neo4j]( https://github.com/neo4j/neo4j-python-driver ):

```
ERROR: Could not find a version that satisfies the requirement neo4j4.0
ERROR: No matching distribution found for neo4j4.0

```

Please help and advise. It would be great to hear (have it documented) from users.

All release notes: ( https://pypi.org/project/neo4j/#history )

### tracking (also asked on..)

- ( https://github.com/graphfoundation/ongdb/issues/106 )

**Comment by robsdedude** [comment]
This issue tracker is about the Python driver for Neo4j, not the whole ecosystem of Graph databases.

So neither do your questions fit the issue tracker nor do I actually have any answers to your questions. For general questions like this, I recommend trying one of the following platforms:
 - Neo4j Online Community: https://community.neo4j.com/
 - StackOverflow: https://stackoverflow.com/questions/tagged/neo4j+python  
   (Might not be ideal, as SO doesn't allow questions asking for opinions, e.g., "what's the best tool for XYZ").
 - Discord: https://discord.gg/neo4j
