### ISSUE TITLE
Pylance Typing checking error for AsyncTransaction

### ISSUE THREAD

**Issue by eric-nguyen-cs** [neo4j/neo4j-python-driver#1015]
# Bug Report

![Screenshot 2024-01-31 at 11 52 15](https://github.com/neo4j/neo4j-python-driver/assets/77902715/96060717-a124-4359-a9fc-9906112a8bd8)

I am using the AsyncTransaction context manager

```python
 async with txn_manager as _txn:
    ...
```

However, the Pylance VSCode extension (powered by Pyright) in Basic Type checking mode is giving a type error:
`Object of type "AsyncTransaction" cannot be used with "with" because it does not implement __aenter__`
`Object of type "AsyncTransaction" cannot be used with "with" because it does not implement __aexit__`

I believe that it is because `AsyncTransaction`'s `__aenter__` and `__aexit__` are wrapped with `functools.wraps(AsyncTransactionBase._enter)` and `functools.wraps(AsyncTransactionBase._exit)` respectively

# My Environment
Python Version: 3.11
Driver Version: 5.14
Operating System: macOS

**Comment by robsdedude** [comment]
Hi and thanks for reaching out.

I'm thinking this might rather be an issue with the chosen type checker (Pylance, in your case).

Reasons I'm thinking this:
 * `mypy` is happy with this
 * Looking at how `functools.wraps` is [annotated in `typeshed`](https://github.com/python/typeshed/blob/faf9d77d79adcda3bd6f8f170c7f76e30080c1d2/stdlib/functools.pyi#L115) should make the type checker infer that `wraps(xyz)` returns the identity function (only regarding `__call__`). So `wraps(xyz)(abc).__call__(...)` should be equivalent to `abc.__call__(...)`. In our example, the type checker should consider `__aenter__` and `__aexit__` to exist and be callable.
 
 Please let me know if you disagree and why.

**Comment by eric-nguyen-cs** [comment]
Thank you for your quick response

I agree what you said, the bug does seem to come from `pyright` and not the `neo4j` code: I ran the code against other type checkers (`pyre-check` and `pytype`) and it seems that only `pyright` raised an issue here.

However, I am wondering if the `AsyncTransaction` methods should be `wrapped` with the `AsyncTransactionBase` ones : the `functools.wraps` function's [documentation](https://docs.python.org/3/library/functools.html#functools.update_wrapper) seems to indicate that `functools.wraps` is mostly used for decorated functions. I'm not sure what the value of adding this decorator here: the docstrings could easily be moved to the `AsyncTransaction` methods, as the `AsyncTransactionBase` class is not exposed to the library consumers.

**Comment by robsdedude** [comment]
You are right in that `wraps` does not seem to be apt here. While I could use the optional arguments to `wraps` to make it only copy the docs string (and maybe annotations), there's no good reason for this complication. So I cleaned up the code in the PR linked above. Thanks again for reaching out.

**Comment by eric-nguyen-cs** [comment]
And thank you for quickly responding and solving the issue!
