### ISSUE TITLE
Can warnings package be used to raise warnings?

### ISSUE THREAD

**Issue by na-wapf** [neo4j/neo4j-python-driver#1083]
Regarding the code below, in my use case, I am unable to prevent poorly formatted warning text from being shown in the output:

https://github.com/neo4j/neo4j-python-driver/blob/d117f0c94660b97785d108761d041b12b9abb0ac/src/neo4j/_sync/work/result.py#L322

https://github.com/neo4j/neo4j-python-driver/blob/d117f0c94660b97785d108761d041b12b9abb0ac/src/neo4j/_async/work/result.py#L322

```text
Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownRelationshipTypeWarning} {category: UNRECOGNIZED} {title: The provided relationship type is not in the database.} {description: One of the relation...
```

If it was emitted using the standard `warnings` package I would be able to capture it and emit the text with better formatting. Somthing like

```python
import warnings
import neo4j....

with warnings.catch_warnings(record=True) as w:
    # run query
    ...
    # process w for relevant parts of output
    print(...)
```

Would this be possible?

**Comment by robsdedude** [comment]
Hi and thanks for reaching out with your feature request.

If you follow the code a little further down, you can see that the `warnings` package is used as well as the notifications being logged.

https://github.com/neo4j/neo4j-python-driver/blob/d117f0c94660b97785d108761d041b12b9abb0ac/src/neo4j/_async/work/result.py#L333

https://github.com/neo4j/neo4j-python-driver/blob/d117f0c94660b97785d108761d041b12b9abb0ac/src/neo4j/_async/work/result.py#L337-L345

Your example code seems to work for me

```python
import warnings
import logging

import neo4j

# disable driver logs for less noise
logging.getLogger("neo4j").setLevel(logging.CRITICAL)


URL = "neo4j://localhost:7687"
AUTH = ("neo4j", "pass")


with neo4j.GraphDatabase.driver(URL, auth=AUTH) as driver:
    with driver.session(
        database="neo4j",
        default_access_mode=neo4j.api.WRITE_ACCESS,
    ) as session:
        with session.begin_transaction() as tx:
            # function `id` is deprecated
            with warnings.catch_warnings(record=True) as warn_rec:
                tx.run("CREATE (n:Test) RETURN id(n)").consume()
            tx.rollback()

    print("\n\n".join(str(w.message) for w in warn_rec))
```
Gives
```
{severity: WARNING} {code: Neo.ClientNotification.Statement.FeatureDeprecationWarning} {category: DEPRECATION} {title: This feature is deprecated and will be removed in future versions.} {description: The query used a deprecated function: `id`.} {position: line: 1, column: 24, offset: 23} for query:
CREATE (n:Test) RETURN id(n)
                       ^
```

Therefore, I'll close the issue for now. But please feel free to keep commenting if something is unclear. We can also reopen the issue later should I've misunderstood your feature request.

**Comment by na-wapf** [comment]
@robsdedude  thankyou for responding so quickly!
mmm, I am not sure why my attempt didn't work then.
I wonder does the warning need to be caught inside the transaction? I have a layer of abstraction that may be the issue. 
Thanks again

**Comment by robsdedude** [comment]
> I wonder does the warning need to be caught inside the transaction? I have a layer of abstraction that may be the issue.

No, you could also filter/record it further up. I've just narrowed it down to the smallest possible area to reliably catch it.

**Comment by na-wapf** [comment]
@robsdedude  please re-open; I have found it is actually sending warnings to `stderr`?
See example below I was unable to catch warnings:

```python
import warnings
from contextlib import redirect_stderr

def raise_dummy_warning():
    warnings.warn("raise at least one warning, to be sure we can capture it")

with Path("OUTPUT_STDERR").open("w") as out_stderr:
    with Path("OUTPUT_WARNINGS").open("w") as out_warnings:
        with redirect_stderr(out_stderr):
            with warnings.catch_warnings(record=True) as warns:
                
                raise_dummy_warning()

                # run some neo4j query

                for warn in warns:
                    out_warnings.write(f"{warn}\n")
```

OUTPUT_STDERR

```text
Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownRelationshipTypeWa...
Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownPropertyKeyWarning...
Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownPropertyKeyWarning...
Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownPropertyKeyWarning...
```

OUTPUT_WARNINGS

```text
{message : UserWarning('raise at least one warning, to be sure we can capture it'), category : 'UserWarning', filename : 'C:\\Users\\...\\AppData\\Local\\Temp\\ipykernel_78432\\....py', lineno : 5, line : None}
```

My helper library looks something like the code below... I dont see how my wrapper is preventing warnings from working though. Must be Jupyter Notebooks?

```python
@dataclass
class Neo4jManager:
    neo4j_url:str
    neo4j_database:str
    auth:Auth

    @contextmanager
    def driver(self):
        token = self.auth.get_valid_token()
        with GraphDatabase.driver(self.neo4j_url, auth=token) as driver:
                try:
                    yield driver
                finally:
                    pass

    @contextmanager
    def session(self):
        with self.driver() as driver:
            with driver.session(database=self.neo4j_database) as session:
                try:
                    yield session
                finally:
                    pass
    
    def _read_generic[T](
            self,
            cypher_query:str,
            parameters:Optional[dict],
            transformer:Callable[[neo4j.Result], T]
        ) -> T:
        with self.session() as session:
            def transaction(tx:ManagedTransaction):
                return transformer(tx.run(cast(LiteralString, cypher_query), parameters))
            return session.execute_read(transaction)
    
    def read_pandas(
            self,
            cypher_query:str,
            parameters:Optional[dict] = None,
            expand:bool            = False,
            parse_dates:bool       = False
    ) -> DataFrame:
        return self._read_generic(
            cypher_query = cypher_query,
            parameters    = parameters,
            transformer   = lambda result: result.to_df(
                expand=expand,
                parse_dates=parse_dates
            )
        )
```

Acknowledging that this is a mostly redundant wrapper meant to improve the experience for interactive jupyter notebook sessions, especially making Auth easy in our usecase... the full code has other helpers, including one that patches a `BREAKPOINT` keyword into cypher 😉

**Comment by robsdedude** [comment]
Since the code snippet is not complete, I cannot run it without making up some queries. So I'll answer this theoretically.

Try adding this to the top of you experiment
```python
# disable driver logs for less noise
logging.getLogger("neo4j").setLevel(logging.CRITICAL)
```

As you've linked in your initial issue description: the driver uses both logging and `warnings.warn` to raise visibility of server notifications. By default, both logging (on `WARNING` level and above) and `warnings.warn` is printed to stderr.
