### ISSUE TITLE
"Properties" property is missing

### ISSUE THREAD

**Issue by stefan-veljkovic** [neo4j/neo4j-python-driver#1084]
# Bug Report

Could you please check if Node class has property "properties"?
According to documentation Neo4j driver 5.23 should have "properties" property inside of Node class which I haven't seen the version has.
<img width="331" alt="image" src="https://github.com/user-attachments/assets/9f61ed8a-8d65-4478-bb64-28efe41619ce">

# My Environment
Python Version: 
Driver Version: 
Server Version and Edition: 
Operating System: 
Python version: 3.11
Driver version: 5.23.0
Operating system: WIndows 10

Solution that works for me: 
<img width="543" alt="image" src="https://github.com/user-attachments/assets/5ea83663-5955-4027-9a32-c202866c2dbe">

**Comment by robsdedude** [comment]
Hi and thanks for reaching out. I think this might be a misunderstanding of the docs.

`properties` is listed unter "Parameters" here. It's not an attribute or property of `Node`. Instead, users are supposed to use the `Node` itself, almost like it were the properties dict itself.

```python
n: Node = ...
n2: Node = ...

len(n)  # same as len(n._properties)
iter(n)  # same as iter(n._properties.values()) NOTE: iter over values, not keys like dicts do
n[key]  # same as n._properties[key]
key in ne  # same as key in n._properties
n.get(key, default=None)  # same as n._properties.get(key, default=None)
n.keys()  # ...
n.values()  # ...
n.items()  # ...

# ! NOT simple forwarding to properties !
n == n2  # NOT the same as n._properties == n2._properties
n != n2  # ...
hash(n)  # NOT the same as hash(n._properties)
```

I'll close the issue for now as I'm unsure how to improve the driver or the docs here. However, please feel free to keep commenting if you have further questions regarding this or if you can think of something that could be improved here.
