### ISSUE TITLE
Possible typo in documentation, Python driver example code

### ISSUE THREAD

**Issue by danielostling** [neo4j/neo4j-python-driver#1091]
# Bug Report

Looking at the example at https://neo4j.com/docs/api/python-driver/current/api.html#session-construction it seems like the statement

`with GraphDatabase(uri, auth=(user, password)) as driver:` 

should be 

`with GraphDatabase.driver(uri, auth=(user, password)) as driver:`

# My Environment
Python Version: 
Driver Version: 
Server Version and Edition: 
Operating System:

**Comment by robsdedude** [comment]
Good spot. Thanks for the report :bow:
