### ISSUE TITLE
AsyncDriver got Future <Future pending> attached to a different loop when driver is cached

### ISSUE THREAD

**Issue by mkashwin** [neo4j/neo4j-python-driver#1095]
I search the issues and the community. The closest  issue I got was  [950](https://github.com/neo4j/neo4j-python-driver/issues/950)

As advised in best practices , I am caching the driver across calls for performance reasons as mentioned in the [guidelines](https://community.neo4j.com/t/neo4j-driver-best-practices/52065) 
when I have multiple calls to the driver  i get the error 
` cb=[_run_until_complete_cb() at /usr/local/lib/python3.12/asyncio/base_events.py:182]> got Future <Future pending> attached to a different loop`

I have attached the minimal reproducer in zip 
created a pytest which invokes the driver and verifies connectivity.
the test depends on a fixture which also  obtains the driver to insert test data into the database

# My Environment
Python Version: Python 3.12.3 (main, Apr 24 2024, 14:45:49) [GCC 10.2.1 20210110]
Driver Version: Version: 5.23.1
Server Version and Edition: Neo4j Server version: 5.23.0 (community)
                                              Build number: 224
                                              Build date: 10/06/2024
Operating System: Description:    Debian GNU/Linux 11 (bullseye) . Docker running inside Mac environment
[issue_reproducer.zip](https://github.com/user-attachments/files/17091177/issue_reproducer.zip)

**Comment by robsdedude** [comment]
Hello and thanks for reaching out. I appreciate the reproducer a  lot. But could you possibly share it as plain text? E.g., GitHub gist, a GitHub repository, or code blocks (could use [collapsibles](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections) if it's much) in this issue? I'm not a fan of downloading untrusted zip files.

**Comment by mkashwin** [comment]
1. Setup the minimal environment

  ```bash
  pip install neo4j pytest-asyncio pytest
  ```
1. Create folder test. within test create folder minimal_reproduce
1. Copy test_graph_db.py and graph_db.py to minimal_reproduce
 
<details>
<summary>GraphDB Handler implementing Singleton for the AsyncDriver and its test class</summary>

## graph_db.py

```python
import asyncio
import logging

import neo4j
from neo4j import AsyncDriver, AsyncGraphDatabase, Record

LOGGER = logging.getLogger(__name__)

MAX_RETRIES = 5
SLEEP_BTW_ATTEMPT = 10


class GraphDB:
    """
    Encapsulates the connection and queries to the graph database.
    Provides methods to get and release the Neo4j async driver.
    """

    # Class variable to hold the shared driver for the graph DB
    _graphdb_driver: AsyncDriver = None

    @classmethod
    async def get_graphdb_driver(cls, retry: int = 0) -> AsyncDriver:
        """
        Returns the Neo4j async driver which is the connection to the database.

        Validates if the current driver is still connected, and if not, creates a new connection.
        The driver is cached and reused for subsequent requests to avoid creating multiple connections.
        Parameters
        ----------
        retry: int
            Optional parameters to retry making a connection in case of errors.
            The max number of retry is `MAX_RETRIES`
            The time between attempts is  `SLEEP_BTW_ATTEMPT` seconds

        Returns:
            AsyncDriver: The Neo4j async driver.
        """
        LOGGER.debug("GraphDB driver requested")
        if cls._graphdb_driver is None:
            LOGGER.info("Creating a new GraphDB driver")
            cls._graphdb_driver = AsyncGraphDatabase.driver(
                uri="bolt://localhost:7687",
                auth=("neo4j", "4sa3suctLdRuiL1l0bE8HPQKnAHsL1dI6ryrpsLhQ"),
                # auth=("neo4j", "password"),
                database=neo4j.DEFAULT_DATABASE,
            )
        try:
            await cls._graphdb_driver.verify_connectivity()
            LOGGER.debug("GraphDB driver connectivity verified")
        except Exception as ex:
            LOGGER.error("Failed to verify GraphDB driver connectivity: %s", str(ex), stack_info=True, exc_info=True)
            # In case of connectivity failure, close the existing driver and create a new one
            await cls.release_graphdb_driver()
            if retry >= MAX_RETRIES:
                LOGGER.error("No. of retries exceeded %s", str(MAX_RETRIES), stack_info=True, exc_info=True)
                raise ex  # Re-raise the exception after cleanup

            await asyncio.sleep(SLEEP_BTW_ATTEMPT)
            cls._graphdb_driver = await cls.get_graphdb_driver(retry + 1)
            LOGGER.info("Trying to Reconnect to GraphDB driver")

        return cls._graphdb_driver

    @classmethod
    async def release_graphdb_driver(cls):
        """
        Closes the Neo4j async driver and releases the connection.
        Ensures that any exceptions during the close process are logged.
        """
        if cls._graphdb_driver is not None:
            LOGGER.debug("Releasing GraphDB driver")
            try:
                await cls._graphdb_driver.close()
                LOGGER.info("GraphDB driver closed successfully")
            except Exception as ex:
                LOGGER.error("Error closing the GraphDB driver: %s", str(ex), stack_info=True, exc_info=True)
            finally:
                cls._graphdb_driver = None
        else:
            LOGGER.warning("Trying to close an already closed driver")

    async def execute_read_query(self, query: str, *args, **kwargs) -> list[Record]:
        """
        Executes a (CQL) query with the provided positional and keyword parameters.

        Args:
            query (str): The CQL query to execute. Using the auto commit feature for transaction
            *args: Positional parameters for the CQL query.
            **kwargs: Keyword parameters for the CQL query.

        Returns:
            list: The results of the query.
        """

        LOGGER.debug("Executing query: %s with args: %s and kwargs: %s", query, args, kwargs)
        driver = await self.get_graphdb_driver()

        async def read(read_tx, query: str, *args, **kwargs) -> list[Record]:
            result = await read_tx.run(query, *args, **kwargs)
            records: list[Record] = [record async for record in result]
            return records

        async with driver.session() as session:
            try:
                records = await session.execute_read(read, query=query, *args, **kwargs)  # noqa: B026

                LOGGER.debug("Query executed successfully, retrieved records: %s", records)
                return records
            except Exception as ex:
                LOGGER.error("Error executing query: %s", str(ex), stack_info=True, exc_info=True)
                raise
            finally:
                await session.close(
```

The test case has a small hack to include the current folder in the path
to execute the tests copy both files into a folder test/minimal_reproduce

## test_graph_db.py

```python
"""
Tests to reproduce error of Future <Future pending> attached to a different loop") AsyncGraphDatabase.driver
"""
import sys
from pathlib import Path

import pytest
import pytest_asyncio

test_folder = (Path(__file__).resolve().parent.parent.parent / "test").resolve()
sys.path.insert(0, str(test_folder))
# @FIXME Hack done to be able to import utility modules in the tests directories
# @See https://docs.pytest.org/en/7.1.x/explanation/pythonpath.html importlib
from minimal_reproduce.graph_db import GraphDB  # noqa: E402


@pytest_asyncio.fixture(scope="module")
async def setup_graphdb_data():
    """Fixture to set up data in the GraphDB from the test_data.cypher file."""
    # Read the Cypher script as read only
    test_data: list[str] = [
        """
CREATE p = (charlie:Person:Actor {name: 'Charlie Sheen'})-[:ACTED_IN {role: 'Bud Fox'}]->(wallStreet:Movie {title: 'Wall Street'})<-[:DIRECTED]-(oliver:Person:Director {name: 'Oliver Stone'}), 
(wallStreet)<-[:ACTED_IN {role: 'Gordon Gekko'}]-(michael:Person:Actor {name: 'Michael Douglas'})
RETURN length(p)
        """
    ]
    # Execute each query separately
    driver = await GraphDB.get_graphdb_driver()
    async with driver.session() as session:
        for query in test_data:
            if query.strip():  # Make sure the query is not empty
                await session.run(query=query)

    # Yield control to the test
    yield

    # Teardown code i.e. clearing the database)
    async with driver.session() as session:
        await session.run("MATCH (n) DETACH DELETE n;")
    # Release the driver
    await GraphDB.release_graphdb_driver()


@pytest.mark.asyncio
@pytest.mark.integrationtest
@pytest.mark.parametrize(
    "dummy",  # to simulate multiple runs
    [
        ("dummy1"),
        ("dummy2"),
        (None),
    ],
)
async def test_graph_db(setup_graphdb_data, dummy: str):  # noqa: ARG001
    driver = await GraphDB.get_graphdb_driver()  # noqa: F841

```

</details>

**Comment by robsdedude** [comment]
Thanks again for the reproducer.

This is not actually an issue with the driver but with the things `pytest-asyncio` does in the background. If not told otherwise, it will spawn a new event loop per test. That sets you up for a bad time if you're caching an async object over multiple tests (`@pytest_asyncio.fixture(scope="module")`) as it will create the object with one running event loop, but run further tests with other event loops. You can read more about it here: https://pytest-asyncio.readthedocs.io/en/stable/concepts.html

The easiest fix in my opinion is not to share the driver between tests. Sharing the driver sure is a great idea in production environments, but this here is test code. Soooo... :shrug: Either way, when sharing, it's paramount not to share drivers between loops should you be using multiple event loops (which, outside of testing, I assume is a rather rare requirement).

If you want to fix your test, you could tell `pytest-asyncio` to share the event loop across the module (i.e., as long as the driver is shared), by changing the fixture decorator to `@pytest_asyncio.fixture(scope="module", loop_scope="module")` and the test decorator to `@pytest.mark.asyncio(loop_scope="module")`. Further, there's the config option [`asyncio_default_fixture_loop_scope`](https://pytest-asyncio.readthedocs.io/en/stable/reference/configuration.html#asyncio-default-fixture-loop-scope) which sounds like it should be able to get you out of this situation as well, but I couldn't get it to work with it so maybe I'm misunderstanding what it's supposed to do.

Side note: if you ask me, it feels like `pytest-asyncio` should be able to infer that if the async fixture is scoped to `module` so should probably be the event loop, but maybe that's not possible given pytest's API or similar. I don't know much in terms of details. So maybe you want to raise an issue/discussion on their side, if you want to dig deeper.

I'll close this issue as it's not a driver bug. But please feel free to keep commenting if you have further questions/thoughts.
