### ISSUE TITLE
    raise ServiceUnavailable("Unable to retrieve routing information") neo4j.exceptions.ServiceUnavailable: Unable to retrieve routing information

### ISSUE THREAD

**Issue by zyrdegit** [neo4j/neo4j-python-driver#1114]
# My Environment
Python Version: <3.11.7>
Driver Version: <5.3.0>
Server Version and Edition: < Neo4j version 5 aura>
Operating System: <Ubuntu 20.04>

**Comment by robsdedude** [comment]
Hi and thanks for reaching out.

Please provide more information. Why do you think this is a bug? What were you doing to get the error? What did you expect to driver to do instead?

If you're unsure whether this is a bug but rather want help with figuring out how to set-up neo4j and get a driver to connect to the DBMS, this issue tracker is not the right place to ask. Please use one of the following channels instead:
 - Neo4j Online Community: https://community.neo4j.com/
 - StackOverflow: https://stackoverflow.com/questions/tagged/neo4j+python
 - Discord: https://discord.gg/neo4j
 - Neo4j Support Portal if you are an enterprise customer:
   https://support.neo4j.com/

or check the documentation:

 - API documentation: https://neo4j.com/docs/api/python-driver/current/ 
 - Driver manual: https://neo4j.com/docs/python-manual/current/

**Comment by zyrdegit** [comment]
i run this :


GRAPHRAG_FOLDER="/home/Desktop/RAG/GraphragTest-main/ragtest/inputs/artifacts"

NEO4J_URI="neo4j+s://ba18adfa.databases.neo4j.io:7687"
NEO4J_USERNAME="neo4j"
NEO4J_PASSWORD="zyr521000"
NEO4J_DATABASE="neo4j"



driver = GraphDatabase.driver(NEO4J_URI, auth=(NEO4J_USERNAME, NEO4J_PASSWORD),connection_timeout=60)



statements = """
create constraint document_id if not exists for (d:__Document__) require d.id is unique;
create constraint chunk_id if not exists for (c:__Chunk__) require c.id is unique;
create constraint entity_id if not exists for (e:__Entity__) require e.id is unique;
create constraint entity_title if not exists for (e:__Entity__) require e.name is unique;
create constraint entity_id if not exists for (c:__Community__) require c.community is unique;
create constraint entity_title if not exists for (e:__Covariate__) require e.title is unique;
create constraint related_id if not exists for ()-[rel:RELATED]->() require rel.id is unique;
""".split(";")
for statement in statements:
    if len((statement or "").strip()) > 0:
        print(statement)
        driver.execute_query(statement)



and then get this:raise ServiceUnavailable("Unable to retrieve routing information") neo4j.exceptions.ServiceUnavailable: Unable to retrieve routing information

**Comment by robsdedude** [comment]
Can you please post the full stack trace of that error along with driver debug logs ([here](https://neo4j.com/docs/api/python-driver/current/api.html#logging)'s how to turn them on).

**Comment by robsdedude** [comment]
Since I've not heard back in a while and don't think this is an actual bug in the driver, I'll close the issue. Though, please feel free to keep commenting.

**Comment by KwokRoot** [comment]
Python ver：3.12.9
Driver ver：5.28.1
AuraDB ver: 2025.02

Official Example CODE：
```
Unable to retrieve routing information
Traceback (most recent call last):
  File "admin\python312_test\test_neo4j\test_neo4j.py", line 25, in <module>
    driver.verify_connectivity()
  File "admin\python312_test\venv\Lib\site-packages\neo4j\_sync\driver.py", line 974, in verify_connectivity
    self._get_server_info(session_config)
  File "admin\python312_test\venv\Lib\site-packages\neo4j\_sync\driver.py", line 1185, in _get_server_info
    return session._get_server_info()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "admin\python312_test\venv\Lib\site-packages\neo4j\_sync\work\session.py", line 173, in _get_server_info
    self._connect(READ_ACCESS, liveness_check_timeout=0)
  File "admin\python312_test\venv\Lib\site-packages\neo4j\_sync\work\session.py", line 131, in _connect
    super()._connect(
  File "admin\python312_test\venv\Lib\site-packages\neo4j\_sync\work\workspace.py", line 161, in _connect
    self._pool.update_routing_table(
  File "admin\python312_test\venv\Lib\site-packages\neo4j\_sync\io\_pool.py", line 804, in update_routing_table
    raise ServiceUnavailable("Unable to retrieve routing information")
neo4j.exceptions.ServiceUnavailable: Unable to retrieve routing information
```

JAVA Driver no problem，It indicates that the cause is not network . Want to know the reason, looking forward to reply and repair, thanks .

@robsdedude

**Comment by robsdedude** [comment]
Please provide driver debug logs.

**Comment by robsdedude** [comment]
Hi. Can you please provide [driver debug logs](https://neo4j.com/docs/api/python-driver/current/api.html#logging)?

**Comment by KwokRoot** [comment]
> Hi. Can you please provide [driver debug logs](https://neo4j.com/docs/api/python-driver/current/api.html#logging)?

debug logs：https://github.com/neo4j/neo4j-python-driver/issues/1114#issuecomment-2726215278

code：

import dotenv
import os

from neo4j import GraphDatabase, Auth

load_status = dotenv.load_dotenv("Neo4j-cec961a0-Created-2025-03-12.txt")
if load_status is False:
    raise RuntimeError('Environment variables not loaded.')

URI = os.getenv("NEO4J_URI")
AUTH = (os.getenv("NEO4J_USERNAME"), os.getenv("NEO4J_PASSWORD"))

with GraphDatabase.driver(URI, auth=AUTH) as driver:
    driver.verify_connectivity()
    print("Connection established.")

**Comment by robsdedude** [comment]
> > Hi. Can you please provide [driver debug logs](https://neo4j.com/docs/api/python-driver/current/api.html#logging)?
>
> debug logs：https://github.com/neo4j/neo4j-python-driver/issues/1114#issuecomment-2726215278

Thanks. That's a stack trace. But no debug logs. At least I couldn't find any logs in that linked comment.

**Comment by KwokRoot** [comment]
AuraDB Version:2025.03 no problem, Thanks

**Comment by peeyushsahu** [comment]
Hello All, 

I am trying to connect to Aura instance from a redhat virtual machine. As per the firewall team neo4j ip and port are whitelisted. I am struggling with similar error. @robsdedude hopefully you can help.

Script:
watch("neo4j", out=sys.stdout) #Output debug to stdout
watch("neo4j", out=open('debugLogs.txt', 'w')) #Output debug to logfile

#### URI examples: "neo4j://localhost", "neo4j+s://xxx.databases.neo4j.io"
URI = "neo4j+s://c1199d5c.databases.neo4j.io" # also tried neo4j+sso same error

AUTH = ("neo4j", "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx")

with GraphDatabase.driver(URI, auth=AUTH) as driver:
    driver.verify_connectivity()

#### Packages
python==3.10
neo4j==5.24.0

####Debug:
(patentextraction) [adm__XXXX]$ python aura_test.py
[DEBUG   ] [Thread 140719901885120] [Task None           ] 2025-07-17 09:06:04,474  [#0000]  _: <POOL> created, routing address IPv4Address(('c1199d5c.databases.neo4j.io', 7687))
[DEBUG   ] [Thread 140719901885120] [Task None           ] 2025-07-17 09:06:04,475  [#0000]  _: <WORKSPACE> resolve home database
[DEBUG   ] [Thread 140719901885120] [Task None           ] 2025-07-17 09:06:04,475  [#0000]  _: <POOL> attempting to update routing table from IPv4Address(('c1199d5c.databases.neo4j.io', 7687))
[DEBUG   ] [Thread 140719901885120] [Task None           ] 2025-07-17 09:06:04,475  [#0000]  _: <RESOLVE> in: c1199d5c.databases.neo4j.io:7687
[DEBUG   ] [Thread 140719901885120] [Task None           ] 2025-07-17 09:06:04,476  [#0000]  _: <RESOLVE> dns resolver out: xx.xx.xx.xx:7687
[DEBUG   ] [Thread 140719901885120] [Task None           ] 2025-07-17 09:06:04,476  [#0000]  _: <POOL> _acquire router connection, database=None, address=ResolvedIPv4Address((' xx.xx.xx.xx, 7687))
[DEBUG   ] [Thread 140719901885120] [Task None           ] 2025-07-17 09:06:04,476  [#0000]  _: <POOL> trying to hand out new connection
[DEBUG   ] [Thread 140719901885120] [Task None           ] 2025-07-17 09:06:04,493  [#0000]  C: <OPEN> xx.xx.xx.xx:7687
[DEBUG   ] [Thread 140719901885120] [Task None           ] 2025-07-17 09:06:04,518  [#8E58]  C: <SECURE> c1199d5c.databases.neo4j.io
[DEBUG   ] [Thread 140719901885120] [Task None           ] 2025-07-17 09:06:04,544  [#0000]  C: <CLOSE> xx.xx.xx.xx:7687
[DEBUG   ] [Thread 140719901885120] [Task None           ] 2025-07-17 09:06:04,544  [#0000]  S: <CONNECTION FAILED> xx.xx.xx.xx:7687 BoltSecurityError: [ConnectionResetError] Connection Failed. Please ensure that your database is listening on the correct host and port and that you have enabled encryption if required. Note that the default encryption setting has changed in Neo4j 4.0. See the docs for more information. Failed to establish encrypted connection. (code 104: Connection reset by peer)
[DEBUG   ] [Thread 140719901885120] [Task None           ] 2025-07-17 09:06:04,545  [#0000]  _: <POOL> deactivating address ResolvedIPv4Address((' xx.xx.xx.xx, 7687))
[DEBUG   ] [Thread 140719901885120] [Task None           ] 2025-07-17 09:06:04,545  [#0000]  _: <POOL> table={}
[DEBUG   ] [Thread 140719901885120] [Task None           ] 2025-07-17 09:06:04,545  [#0000]  _: <POOL> failed to fetch routing info from ResolvedIPv4Address((' xx.xx.xx.xx, 7687))
[DEBUG   ] [Thread 140719901885120] [Task None           ] 2025-07-17 09:06:04,545  [#0000]  _: <POOL> deactivating address IPv4Address(('c1199d5c.databases.neo4j.io', 7687))
[DEBUG   ] [Thread 140719901885120] [Task None           ] 2025-07-17 09:06:04,545  [#0000]  _: <POOL> table={}
[ERROR   ] [Thread 140719901885120] [Task None           ] 2025-07-17 09:06:04,545  Unable to retrieve routing information
[DEBUG   ] [Thread 140719901885120] [Task None           ] 2025-07-17 09:06:04,545  [#0000]  _: <POOL> close

####Error:
Traceback (most recent call last):
  File "/home/x/projects/epodataupload/test/aura_test.py", line 26, in <module>
    driver.verify_connectivity()
  File "/home/x/miniconda3/envs/patent/lib/python3.10/site-packages/neo4j/_sync/driver.py", line 1067, in verify_connectivity
    self._get_server_info(session_config)
  File "/home/x/miniconda3/envs/patent/lib/python3.10/site-packages/neo4j/_sync/driver.py", line 1281, in _get_server_info
    return session._get_server_info()
  File "/home/x/miniconda3/envs/patent/lib/python3.10/site-packages/neo4j/_sync/work/session.py", line 172, in _get_server_info
    self._connect(READ_ACCESS, liveness_check_timeout=0)
  File "/home/x/miniconda3/envs/patent/lib/python3.10/site-packages/neo4j/_sync/work/session.py", line 130, in _connect
    super()._connect(
  File "/home/x/miniconda3/envs/patent/lib/python3.10/site-packages/neo4j/_sync/work/workspace.py", line 165, in _connect
    self._pool.update_routing_table(
  File "/home/x/miniconda3/envs/patent/lib/python3.10/site-packages/neo4j/_sync/io/_pool.py", line 802, in update_routing_table
    raise ServiceUnavailable("Unable to retrieve routing information")
neo4j.exceptions.ServiceUnavailable: Unable to retrieve routing information

 Please let me know if any other information would be helpful.

Best regards,
Peeyush

**Comment by robsdedude** [comment]
> also tried neo4j+sso same error

It's `+ssc`, not `+sso`.

Have you read this comment of mine? https://github.com/neo4j/neo4j-python-driver/issues/1114#issuecomment-2459031949
This issue tracker is not the ideal place for support questions like this.

Anyway, try running this from the same machine you're having trouble on connecting to the DMBS (you might need to install ncat, you might need to replace the host with your DBMS)
```bash
echo -e '\x60\x60\xb0\x17\x00\x00\x01\xFF\x00\xFF\xFF\x05\x00\xFF\xFF\x04\x00\x00\x00\x03' | ncat --ssl c1199d5c.databases.neo4j.io -v 7687 | hexdump -ve '"%07.7_ax  " 16/1 "%02x " "\n"'
```
If this fails, it's not the driver but the system's or network's configuration.

What is does is do a [Bolt handshake](https://neo4j.com/docs/bolt/current/bolt/handshake/) with the server and dump the result to stdout.
