### ISSUE TITLE
Neo4j community connection failed with " ServiceUnavailable: Failed to establish connection in 300ms"

### ISSUE THREAD

**Issue by XJJ1213** [neo4j/neo4j-python-driver#1116]
I'm using neo4j community edition for database operations, I've started inside cmd, but I can't log in in the visual interface. I've switched multiple versions like 5.19, 5.12, 4.x, etc., all with this issue
![image](https://github.com/user-attachments/assets/e79030b6-f2f9-4b59-a213-fff04eb9502a)

![image](https://github.com/user-attachments/assets/7192c738-5cf3-4f5e-a380-0c2cb161ab5d)

**Comment by robsdedude** [comment]
Hello and thanks for reaching out.

This report appears to have nothing to do with the Python driver whatsoever. For general questions about usage, deployment, and/or set-up, please ask in one of these places that you thing fits bets:
    - Neo4j Online Community: https://community.neo4j.com/
    - StackOverflow: https://stackoverflow.com/questions/tagged/neo4j+python
    - Discord: https://discord.gg/neo4j
    - Neo4j Support Portal if you are an enterprise customer: https://support.neo4j.com/
    
I'll close this issue, but please feel free to keep commenting if you still think this is a bug in the driver.
