### ISSUE TITLE
acquireWriteLock

### ISSUE THREAD

**Issue by jimanvlad** [neo4j/neo4j-python-driver#178]
Hi,

I am trying to use Tracastions in a multi-processing environment. However, at the moment if any 2 processes want to commit at the same time, they one of them will error out as there is a lock in place.

I see that in the Java driver, one can check for a lock with tx.acquireWriteLock(). This would be a good way to conditionally commit transactions in different processors.

Is there an equivalent in the Python driver?

Vlad

**Comment by technige** [comment]
There is no `acquireWriteLock` method in the Java driver, or indeed any explicit lock control. Are you looking at the core API docs instead?

Your best bet when using the drivers would be to install APOC and use one of its locking procedures:
https://neo4j-contrib.github.io/neo4j-apoc-procedures/#_locking

**Comment by jimanvlad** [comment]
Hi,

That doesn't look like it would help me with my problem.Much like a threading.Lock() object, I am looking to monitor whether I am good to commit a bulk transaction, or wait until read otherwise.

Vlad

**Comment by zhenlineo** [comment]
Neither session or transaction is supposed to be used by more than one thread. Closing this issue.
