### ISSUE TITLE
Pass compiled Cypher code to another function

### ISSUE THREAD

**Issue by jimanvlad** [neo4j/neo4j-python-driver#179]
Hi, is it possible to pre-compile the Cypher query and store it somewhere before committing (in Python)?

For example (tx is a transaction):
```
tx.run("""
     MERGE (account:Account {account_key: {Account_Key}}
     SET account.name = {Name}
     """, {"Account_Key":1, "Name":"First Second"}}))
tx.commit()
```
I want to save the compiled query that is now in tx.run, to pass it to another function for a later commit.

Effectively I want to create a list of queries to run, and then commit them at a later point.

Vlad

**Comment by technige** [comment]
What level of compilation are you after? The Neo4j server recognises identical queries (by exact string match) and uses a pre-compiled version automatically if it can. You haven't got to do anything explicit.

Note that for this to kick in, the statement must be the same but the parameters can vary.

**Comment by jimanvlad** [comment]
Hi,

I'm basically looking to replicate the MongoDB functionality, with Neo4J:

```
from pymongo import UpdateOne

operations = [
    UpdateOne({ "field1": 1},{ "$push": { "vals": 1 } },upsert=True),
    UpdateOne({ "field1": 1},{ "$push": { "vals": 2 } },upsert=True),
    UpdateOne({ "field1": 1},{ "$push": { "vals": 3 } },upsert=True)
]
result = collection.bulk_write(operations)
```

For now, I managed to pass my `tx` object as a function parameter to get around this.

Vlad

**Comment by technige** [comment]
Then you will probably find transaction functions helpful:
https://neo4j.com/docs/developer-manual/current/drivers/sessions-transactions/#driver-transactions-transaction-functions

(There are a few more examples in this demo app -> https://github.com/technige/neopress.py)

These let you wrap up a unit of work in a function and, in a clustered environment, can also provide retry capabilities.

**Comment by jimanvlad** [comment]
Hi,

In your example:

```
def save_article(self, article):
        with self.driver.session() as session:
            return session.write_transaction(article.save)
```

I assume the above generates and returns the unit of work right? How do I then commit a list of units of work when I get enough of them?

Because with a construct like with `session.begin_transaction() as tx:`, the only way to commit my work is using `tx.commit()`, which is dependent on my transaction, rather than something like `neo4j.commit([list_of_units_of_work])`.

Vlad

**Comment by zhenlineo** [comment]
Hi @jimanvlad,

Why do you want to commit a list of unit of work rather than commit each of them when they are ready? May I ask what do you want to achieve here?

Say you want to commit `work1`, `work2`, `work3` in a "bulk commit", then what do you expect to happen if `work2` failed? do you want to rollback `work1` too? If so then you should just put all of them into one transaction. If you expect `work1` and `work3` commit successfully, then you need to put them into different transactions. What's the problem to loop over the list of unit of work and commit them separately? 

Regards,
Zhen

**Comment by zhenlineo** [comment]
Hi @jimanvlad,

I am closing this issue as we have not heard from you for a while. Please reach us out again if you still have the problem.

Cheers,
Zhen
