### ISSUE TITLE
TypeError: '>=' not supported between instances of 'int' and 'NoneType' when running the gc

### ISSUE THREAD

**Issue by tardyp** [neo4j/neo4j-python-driver#184]
How to reproduce easily

pip install pytest neo4j-driver

write a file 'test_neo.py' :
```python
from neo4j.v1 import GraphDatabase, basic_auth
import os

url = os.environ["NEO4J_URL"]
auth = os.environ["NEO4J_AUTH"].split(":")
d = GraphDatabase.driver(url, auth=basic_auth(*auth), encrypted=False)
s = d.session()


def test_neo():
    with s.begin_transaction() as tx:
        tx.run("MATCH (n) RETURN n LIMIT 1")
```

```
0 % pytest testneo.py
============================================================================================================================ test session starts =============================================================================================================================
platform darwin -- Python 3.6.2, pytest-3.2.2, py-1.4.34, pluggy-0.4.0
rootdir: /Users/az02096/dev/nestor/gitlab-celery, inifile:
plugins: celery-4.1.0
collected 1 item

testneo.py .

========================================================================================================================== 1 passed in 0.13 seconds ==========================================================================================================================
Exception ignored in: <bound method Driver.__del__ of <neo4j.v1.direct.DirectDriver object at 0x1088400f0>>
Traceback (most recent call last):
  File "[..].venv/lib/python3.6/site-packages/neo4j/v1/api.py", line 151, in __del__
  File "[..].venv/lib/python3.6/site-packages/neo4j/v1/api.py", line 193, in close
  File "[..].venv/lib/python3.6/site-packages/neo4j/bolt/connection.py", line 439, in close
  File "[..].venv/lib/python3.6/site-packages/neo4j/bolt/connection.py", line 428, in remove
  File "[..].venv/lib/python3.6/site-packages/neo4j/bolt/connection.py", line 346, in close
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/logging/__init__.py", line 1305, in info
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/logging/__init__.py", line 1546, in isEnabledFor
TypeError: '>=' not supported between instances of 'int' and 'NoneType'
Exception ignored in: <bound method Connection.__del__ of <neo4j.bolt.connection.Connection object at 0x1099fb9e8>>
Traceback (most recent call last):
  File "[..].venv/lib/python3.6/site-packages/neo4j/bolt/connection.py", line 190, in __del__
  File "[..].venv/lib/python3.6/site-packages/neo4j/bolt/connection.py", line 346, in close
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/logging/__init__.py", line 1305, in info
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/logging/__init__.py", line 1546, in isEnabledFor
TypeError: '>=' not supported between instances of 'int' and 'NoneType'
```

Looks like similar issue here:
https://github.com/johanlundberg/neo4j-django-tutorial/issues/10

I am not sire exactly, but it looks like somehow the INFO variable is reset to None at some point. I am not sure if this is because of neo4j-driver or because of pytest

**Comment by zhenlineo** [comment]
With this fix https://github.com/neo4j/neo4j-python-driver/pull/188 I could successfully run your example with pytest on python 3 without any problem, while on python 2 I still receive some issues to close all resources properly. It seems pytest or python2 is destroying some resources earlier than it should be. While if I run your example as a python script, then I will not get any error now.

So the best practice I would suggest is: mange the resources properly, a.k.a close the driver yourself rather than relying on closing when the object is out of scope.

**Comment by zhenlineo** [comment]
Hi @tardyp,

I am closing this issue as we've already fixed what we could fix in #188 

The key is still to close the resources. It is still suggested to explicitly to close driver/session/tx to avoid any possible connection leaks in your app.

If you still have any problem regarding this card, be free to reopen it.

Cheers,
Zhen

**Comment by TvoroG** [comment]
Hi!
I stuck with the same issue:
```
Exception ignored in: <bound method Connection.__del__ of <neo4j.bolt.connection.Connection object at 0x7f14961e61d0>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/neo4j/bolt/connection.py", line 212, in __del__
  File "/usr/local/lib/python3.6/site-packages/neo4j/bolt/connection.py", line 385, in close
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1305, in info
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1546, in isEnabledFor
TypeError: '>=' not supported between instances of 'int' and 'NoneType'
```
Every time django server is reloading or tests finished this message appears.
As @zhenlineo sad problem is incorrect resource managing. In my case it is driver managing. I don't know how properly manage driver in server application. At least it's not so clear.

As a workaround I use `atexit` module:
```python
import atexit
driver = GraphDatabase.driver(...)
atexit.register(lambda: driver.close())
```

**Comment by jeicoo** [comment]
Got the same issue as well.
I am using neo4j-driver version 1.5.2
@zhenlineo is your already included in the version above? Thank you

**Comment by zhenlineo** [comment]
@jeicoo It should be. You shall not get the error on Python3.
Which python version you are using?
Will you still get the problem if you explicitly close the driver?

**Comment by jeicoo** [comment]
@zhenlineo thank you for the response!
I am using Python 3.6.
Unfortunately, I am not closing the driver explicitly as I don't know where to close it in Pyramid framework. I initialized the driver in the module level with the main function.

**Comment by zhenlineo** [comment]
@jeicoo The key is still to shut down the driver properly. I found this simple solution to work around the fact that there is no shutdown event in pyramid [here](https://stackoverflow.com/questions/7484366/run-code-at-pyramid-shutdown?answertab=votes#tab-top) (The same as @TvoroG 's suggestion too)

Let us know if this solves your problem.

**Comment by jeicoo** [comment]
@zhenlineo yes, as you mentioned in the previous comment to shut down the driver properly. I will keep that in mind.

Thank you for the link that you gave! It looks like that will solve my problem. I was hoping to find the solution to this issue but you showed me on how to handle exit event in pyramid as well. Much appreciated!

@TvoroG  thank you for sharing your solution!

Will let you guys know once I solved my problem.

**Comment by jeicoo** [comment]
@zhenlineo the workaround you gave worked for me! Thanks a lot!
