### ISSUE TITLE
Cannot run LOAD CSV query across multiple sessions in the same application.

### ISSUE THREAD

**Issue by ihatemundays** [neo4j/neo4j-python-driver#187]
Using Neo4j 3.0.7.

I'm having trouble with LOAD CSV queries and multiple session in the same application. It looks like if you run a LOAD CSV query through a driver session, the connection locks the entire Neo4j import folder, not just the files you are loading. This becomes problematic when I want to bulk load data with multiple requests in my Python application. I've tried closing the driver's pool of sessions manually, but to no avail. My process will still hang on the second session that attempts to load CSV files.

As an aside, I believe this problem occurs primarily because of the connection not completely being closed on deletion or garbage collection, but on a complete break of the application.

Is there an "easy fix" that I can implement to resolve this issue without upgrading the Neo4j server?

**Comment by zhenlineo** [comment]
Hi,

May I ask what os your are running your server? Do you have periodic commit while you are using LOAD CSV? Are you only use one CSV file in each of your queries?

I am not fully sure about why the server connection will lock the entire import folder, while if that's the case, It is probably a server bug. 
Could you give us more info for reproduce your error? such as server version, os the server is running, python driver version, LOAD CSV cypher query, and structure of your import folder and how you use each of the files inside.

Thanks,
Zhen

**Comment by ihatemundays** [comment]
Sure thing, although the architecture is a little complex, so bare with me.

I'm using CentOS 7.3.1611 Docker containers between both the caller (Python application) and the callee (Neo4j server). The volume for the import folder is shared among both containers through my Docker compose file, so the Python application can create the import files directly in the Neo4j import folder and load them.

I've tried it the following ways:
1. Through a behave test. I can run my test once; however, if I duplicate the steps in the test, it always runs perfectly fine for the first run. It never works for any subsequent runs.
2. Through ipython. Running commands directly (bypassing my code altogether) still works perfectly the first time. Subsequent calls on new sessions hang.
3. Through the Flask application using my process. I restart the Flask application and the process always works the first time, but always hangs afterward.
4. If I drop the single line that calls the query, my process builds the import files correctly, regardless of how many steps I run This led me to believe that it has something to do with the session/connection and some sort of locking that occurs with it.

**Comment by zhenlineo** [comment]
Can you try one thing: Do not let your python app build your csv file but run queries with an existing csv instead. I highly doubts if some app process locks the csv import folder rather than the server who locks it.

The driver itself will never open a csv file. It just pass the file name to the server, the server will then open the file and read each line inside. So for the whole process the driver never touches the files. By following the suggestion I give above and repeat your tests, then you will know if it was the server or your app that locks the files.

Regards,
Zhen

**Comment by ihatemundays** [comment]
My application runs a set of LOAD CSV queries at a time. It creates the CSV files and runs a query set. I believe this is how you were asking me to test it??? If so, then I agree, this proves that it is "on the server" as you said; however, the Neo4j server appears to be maintaining a lock on the import folder as part of the query set and the open connection/session provided via the driver. It would explain why it always works the first time, and never any of my subsequent times.

**Comment by ihatemundays** [comment]
This might (and probably is) a local issue. I looked deeper, and it looks like where it's meant to close file handlers, it isn't. I need to look deeper into my application, but I'm pretty much considering this issue closed. Sorry for the distraction.

**Comment by ihatemundays** [comment]
This was a local issue. Sorry about that.

**Comment by zhenlineo** [comment]
no problem.
