### ISSUE TITLE
Logger should not log credentials

### ISSUE THREAD

**Issue by gingerjoos** [neo4j/neo4j-python-driver#190]
The Connection class logs the neo4j password

```
[2017-10-17 09:58:40,703: INFO/ForkPoolWorker-2] C: INIT (u'neo4j-python/1.2.1', {'credentials': 'PASSWORD', 'scheme': 'basic', 'principal': 'neo4j'})
```
The best practice in this case is to hide the credentials. For eg., celery does this -
```
[2017-10-17 10:19:04,333: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
```

**Comment by technige** [comment]
Which version of the driver are you using? This was fixed back in June:
https://github.com/neo4j/neo4j-python-driver/pull/171

**Comment by technige** [comment]
Oh, 1.2.1, I can see :)

I recommend you upgrade.

**Comment by gingerjoos** [comment]
Oops! Sorry for wasting your time. Was being installed as a dependency of https://github.com/robinedwards/django-neomodel . Will raise a ticket to upgrade version there.
