### ISSUE TITLE
Write transaction hangs program when invalid value is passed as parameter without error

### ISSUE THREAD

**Issue by mjmare** [neo4j/neo4j-python-driver#193]
I have this function that is called in a write transaction:
```
from uuid import uuid4

:
    def add_technique(tx, title, topic):
        tx.run("MERGE (t:Technique {title: $title, uuid: $uuid}) "
               "MERGE (topic:Topic {name: $topic}) "
               "MERGE (t)-[:BELONGS_TO]->(topic)",
               topic=topic, title=title, uuid=uuid4())

:
    with driver.session() as session:
        for s in sections:
                session.write_transaction(add_technique, s['title'], s['topic'])
:
```
Please note that the third parameter *uuid* of the cypher statement is passed an incorrect type because uuid4() returns a uuid.UUID instance, not a string as I thought. 
When running the program it hangs on the first call to tx.run. No exceptions or messages. The only option is to kill the program.
When the paramater value is corrected to str(uuid4()) everything is fine. 

Using Neo4j community v3.2
Python driver 1.5.0
Python 3.6.3 on OSX

**Comment by zhenlineo** [comment]
#200 fixes this issue and #199 add related tests for it.
These fixes will come in next patch release 1.5.2.

**Comment by zhenlineo** [comment]
The new [1.5.2 driver](https://pypi.python.org/pypi/neo4j-driver/1.5.2) has the fix for this bug :)

**Comment by mjmare** [comment]
Cool!
