### ISSUE TITLE
Session.run() method DOES NOT run a cypher statement within an auto-commit transaction.

### ISSUE THREAD

**Issue by erikyao** [neo4j/neo4j-python-driver#195]
Hi neo4j-python-driver developers, 

I was using `BoltSession` and found that its `run()` method just posts two messages, `RUN` and `PULL-ALL`, to its connection message queue, not exactly functioning as [your document](https://neo4j.com/docs/api/python-driver/current/session.html#neo4j.v1.Session.run) says:

> Run a Cypher statement within an auto-commit transaction.

This is really misleading since I have a long query which may not finish before my script quits. It's better to revise your document and recommend other users to use the following practice:

```python
with session.begin_transaction():
    tx.run("query")
```

Thanks!
Yao

**Comment by erikyao** [comment]
Sorry I may have had some misunderstanding towards the term "auto-commit". It just states that there will be an automatically created transaction for the query involved and it will commit automatically too. It's not guaranteed that query will be executed immediately, is it?

I think a better statement would be:

> Run a Cypher statement in auto-commit mode.

Thanks!

**Comment by zhenlineo** [comment]
Hi @erikyao,

When you use `session.run`, two messages `run` and `pull-all` will be sent to the server. The moment the server receives these two messages, the server will automatically creates a transaction and run the cypher statement inside this transaction. 

It is true that session.run will not ensure that your transaction is finished when run returns, while if you consume all your session run result or close your session, then it will be guaranteed to have your transaction finished. And it is highly recommended to always consume results and close sessions. You could also find more docs [here](https://neo4j.com/docs/developer-manual/current/drivers/sessions-transactions/)

Cheers,
Zhen

**Comment by erikyao** [comment]
Thanks, @zhenlineo! We have a long CREATE query so we didn't consume the result. We already learned the lesson.
