### ISSUE TITLE
Connection keeps getting reset with UWSGI-NGINX

### ISSUE THREAD

**Issue by rdhara** [neo4j/neo4j-python-driver#196]
Hello,

I've been struggling with this issue for weeks. It seems the driver keeps resetting connections to my web app. I keep getting this error seemingly randomly when I try to make requests using the driver from a Flask app using UWSGI and NGINX:
```
Nov 19 13:08:44 ip-172-31-15-241 uwsgi[22867]: Exception ignored in: 'neo4j.bolt._io.ChunkedInputBuffer.receive'
Nov 19 13:08:44 ip-172-31-15-241 uwsgi[22867]: Traceback (most recent call last):
Nov 19 13:08:44 ip-172-31-15-241 uwsgi[22867]:   File "/usr/lib/python3.5/ssl.py", line 929, in recv_into
Nov 19 13:08:44 ip-172-31-15-241 uwsgi[22867]:     return self.read(nbytes, buffer)
Nov 19 13:08:44 ip-172-31-15-241 uwsgi[22867]:   File "/usr/lib/python3.5/ssl.py", line 791, in read
Nov 19 13:08:44 ip-172-31-15-241 uwsgi[22867]:     return self._sslobj.read(len, buffer)
Nov 19 13:08:44 ip-172-31-15-241 uwsgi[22867]:   File "/usr/lib/python3.5/ssl.py", line 575, in read
Nov 19 13:08:44 ip-172-31-15-241 uwsgi[22867]:     v = self._sslobj.read(len, buffer)
Nov 19 13:08:44 ip-172-31-15-241 uwsgi[22867]: ConnectionResetError: [Errno 104] Connection reset by peer
```

This causes the whole application to hang but will clear itself up after some time. I can post additional logs from NGINX if it will be helpful in solving the issue. Please let me know if you have any ideas!

**Comment by zhenlineo** [comment]
Hi @rdhara,

Please check when the error happens, 
1) if there is any error in the server log? 
2) if there is any error or warning printed out in nginx logs such as not enough thread or memory?
3) if your app is under really heavy load?

If you could reproduce this error with some simple code, please do share with us.
Additional nugix logs or tcp dumps around the time when the error happens are very welcome. 

Zhen

**Comment by rdhara** [comment]
Hello,

I am able to get around the problem by simply establishing a new connection every request (which I know is non-ideal, but it works as a temporary patch). I'm assuming that after the `timeout` specified when making a connection with the driver that the connection is discarded? Or will this eventually lead to an unsustainable number of open threads?

**Comment by zhenlineo** [comment]
Hi @rdhara,

It sounds like your server is killing connection after some timeout. Then here is what you are looking for https://neo4j.com/docs/developer-manual/3.3/drivers/client-applications/#driver-config-connection-pool-management

**Comment by zhenlineo** [comment]
@rdhara Do you still have the problem? Is it related to your connection timeout settings on the server and client side?

**Comment by zhenlineo** [comment]
Hi @rdhara,

We have not hear more from you regarding this issue, I am assuming you are okay with the suggested configuration options for your deployment. 

Please be free to reopen this issue if you have more problems with this issue.
Cheers,
Zhen

**Comment by iwarin** [comment]
I'm running into this problem as well.

```Exception ignored in: 'neo4j.bolt._io.ChunkedInputBuffer.receive'
Traceback (most recent call last):
File "/usr/local/lib/python3.6/ssl.py", line 1002, in recv_into
return self.read(nbytes, buffer)
File "/usr/local/lib/python3.6/ssl.py", line 865, in read
return self._sslobj.read(len, buffer)
File "/usr/local/lib/python3.6/ssl.py", line 625, in read
v = self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer
[2017-12-19 07:15:40,172] ERROR in app: Exception on /api/v1/customer [GET]
Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
return cors_after_request(app.make_response(f(*args, **kwargs)))
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
raise value
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/usr/local/lib/python3.6/site-packages/flask_classy.py", line 200, in proxy
response = view(**request.view_args)
File "/usr/local/lib/python3.6/site-packages/flask_apispec/annotations.py", line 117, in wrapped
return wrapper(*args, **kwargs)
File "/usr/local/lib/python3.6/site-packages/flask_apispec/wrapper.py", line 23, in __call__
response = self.call_view(*args, **kwargs)
File "/usr/local/lib/python3.6/site-packages/flask_apispec/wrapper.py", line 39, in call_view
return self.func(*args, **kwargs)
File "/code/app/api/util/paginate.py", line 27, in run
results = func(*args, **kwargs)
File "/code/app/api/util/sort.py", line 36, in run
return results.all()
File "/usr/local/lib/python3.6/site-packages/neomodel/match.py", line 431, in all
return self.query_cls(self).build_ast()._execute()
File "/usr/local/lib/python3.6/site-packages/neomodel/match.py", line 411, in _execute
results, _ = db.cypher_query(query, self._query_params)
File "/usr/local/lib/python3.6/site-packages/neomodel/util.py", line 26, in wrapper
return func(self, *args, **kwargs)
File "/usr/local/lib/python3.6/site-packages/neomodel/util.py", line 98, in cypher_query
response = session.run(query, params)
File "/usr/local/lib/python3.6/site-packages/neo4j/v1/api.py", line 340, in run
self._connection.fetch()
File "/usr/local/lib/python3.6/site-packages/neo4j/bolt/connection.py", line 283, in fetch
return self._fetch()
File "/usr/local/lib/python3.6/site-packages/neo4j/bolt/connection.py", line 300, in _fetch
self._receive()
File "/usr/local/lib/python3.6/site-packages/neo4j/bolt/connection.py", line 338, in _receive
raise self.Error("Failed to read from defunct connection {!r}".format(self.server.address))
neo4j.exceptions.ServiceUnavailable: Failed to read from defunct connection Address(host=xxxxxx, port=xxxx)
```

I don't have this problem developing locally with neo4j container but I run into this very frequently with GrapheneDB. It's usually happen when I leave the web application idle for about 5 mins. Then trying to make a query.

**Comment by zhenlineo** [comment]
Hi @iwarin,

It sound very likely that GrapheneDB or the container holding it has some connection life time setting or connection idle timeout settings to kill connections after 5mins. I would suggest you to have a look in your system for such configuration and enlarge them accordingly.

By default this driver will close connections after created 1h.

For normal use, I suggest config your GrapheneDB or service container to have max_connection_lifetime = 2h, max_connection_idle_timeout = 2h. 

You could verify if it is somewhere in your system enforce to kill connections between server and driver by creating a driver with max_connection_lifetime = 5. 

```
self._driver = GraphDatabase.driver(uri, auth=(user, password), max_connection_lifetime=5)
```

Read more in this [doc link](https://neo4j.com/docs/developer-manual/3.3/drivers/client-applications/#driver-config-connection-pool-management).

**Comment by rdhara** [comment]
Hi @zhenlineo sorry for the delayed reply. The only way I could resolve the problem was to reconnect per request (which is fine, since our app is pretty lightweight and is for demonstration purposes only). In response to your earlier questions

1.  There is no error in the server log (except that the pipe was broken)
2. Nginx logs are blank
3. No, the load is negligible.

There seem to be certain incompatible settings (such as `lazy`) on UWSGI and connection pooling. The pooling technique seems to work fine on other DB connections (such as SQLAlchemy) although switching to pooling as you suggested made the error rate go down considerably (still happens every now and then).

**Comment by aforwardz** [comment]
@zhenlineo Thanks your answer a lot! I loss hours in this same issue. After adding `max_connection_lifetime=5` as you suggest, it works! What I am confused is that this problem came out suddenly cause that my api runs in a goog state without that parameter before

**Comment by zhenlineo** [comment]
hi @aforwardz, it is mostly likely that your deploy environment has some connection timeout enforced recently. The driver or the neo4j server does not kill connections.
