### ISSUE TITLE
Why the acquire method in connection.py is empty but doesn't have pass?

### ISSUE THREAD

**Issue by leopeng1995** [neo4j/neo4j-python-driver#198]
https://github.com/neo4j/neo4j-python-driver/blob/1.6/neo4j/bolt/connection.py#L470

**Comment by zhenlineo** [comment]
Hi @leopeng1995 

That's the base method, it will always be overridden in `DirectConnectionPool` and `RoutingConnectionPool`

**Comment by leopeng1995** [comment]
All right. But it will be an error in a modern IDE.

**Comment by technige** [comment]
As @zhenlineo says, this is a base method and is perfectly valid Python: the docstring counts as a void statement, so the function isn't actually empty. Try this at the Python console:

```
technige@neovo:~$ python
Python 2.7.13 (default, Jan 19 2017, 14:48:08) 
[GCC 6.3.0 20170118] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> def foo():
...     """ This function is empty. """
... 
>>> foo()
>>> 
```

I'm not sure which IDE you are using but we use PyCharm and that has no problem with this layout. I'm guessing this must be an IDE issue on your side.

**Comment by leopeng1995** [comment]
Alright, that's should be my mistake. Thanks for your help :-)
