### ISSUE TITLE
'module' object is not callable

### ISSUE THREAD

**Issue by rotten** [neo4j/neo4j-python-driver#2]
I thought I'd experiment with this alpha utility because I'm finding the REST service has too much overhead for the many thousands of quick queries I need to run.

I tried this with both Python 2.7 and python 3.4, since it isn't clear which python flavor it is supposed to be used with.

After cloning the repo, I started by following the steps in the readme:

'''
$  python3
Python 3.4.0 (default, Jun 19 2015, 14:20:21)
[GCC 4.8.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path.append('/home/rotten/src/neo4j-python-driver')
>>> import neo4j
>>> driver = neo4j.driver("bolt://myneo4jserver")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'module' object is not callable
'''

I get the same complaint about it being a module with both python versions.

'''
>>> type(neo4j.driver)
<class 'module'>
>>> neo4j.driver.__file__
'/home/rotten/src/neo4j-python-driver/neo4j/driver.py'
'''

What am I missing?

**Comment by technige** [comment]
The package name is wrong. You need:

```
from neo4j.v1 import GraphDatabase
driver = GraphDatabase.driver("bolt://localhost")
```
