### ISSUE TITLE
ServiceUnavailable Defunct Connection Address - AWS Internal load balancer

### ISSUE THREAD

**Issue by gpierrick** [neo4j/neo4j-python-driver#205]
Hi,

We're getting this error from Neo4j refusing to connect every couple of minutes when we point the driver to the load balancer (aws elb classic). When we point the driver to one instance internal IP it works fine

 <class 'neo4j.exceptions.ServiceUnavailable'>: Failed to read from defunct connection Address

Any help would be much appreciated.

**Comment by zhenlineo** [comment]
Hi @gpierrick,

Do you have a timeout on connections at your load balancer? By default, load balancer will kill long idle connections after a while. If so, try to adjust your timeout and `connection lifetime` in the driver config settings.

For example:
```
* Change connection idle timeout on load balancer to be 1.5h
* Config python driver:
driver = GraphDatabase.driver(uri, auth=(user, password), max_connection_lifetime=3600) # 1h
```
Read more about connection lifetime [here](https://neo4j.com/docs/developer-manual/3.3/drivers/client-applications/#driver-config-connection-pool-management)

And available config parameters in this driver in this [file](https://github.com/neo4j/neo4j-python-driver/blob/1.6/neo4j/config.py#L58)

**Comment by gpierrick** [comment]
Thanks @zhenlineo for the quick answer. I've updated AWS ELB to 4000 (max allowed)
Looking at the link you sent, the driver seems to have 3600 as default correct?

Would this set up work? What would happen after 4000 seconds? Can the driver handle this gracefuly?

**Comment by zhenlineo** [comment]
The driver maintains a pool. When driver wants to run a query (`session.run`) or starts a tx (`session.beginTx`), it will try to obtain a connection from the pool. Then the driver will go over the connections in the pool one by one until it grabs a connection that is still in a good state. If the driver found a connection is expired, it will directly call `close` on this socket and then move to check next connection in the pool.

You should not see any error, and hopefully no noticeable delay.

Let us know if you got any unexpected error.
Zhen

**Comment by zhenlineo** [comment]
Hi @gpierrick,

We have not hear you more regarding this issue. I am assuming that you are happy with the current configuration. I am considering this issue as solved now. Please be free to let us know if you have more problems or more doubts regarding the problem you have.

Cheers,
Zhen

**Comment by gpierrick** [comment]
Hi Zhen,

I actually had to pause production for other reasons so I haven't verified the new configuration.

Thanks
