### ISSUE TITLE
[Query] Efficient way to batch write

### ISSUE THREAD

**Issue by manojgudi** [neo4j/neo4j-python-driver#213]
Hey what's the most efficient way to batch write to neo4j using this driver?
I went through the docs for v1.5, and this seems to be one way:

```python 
multipleCreate = "create (n:Person {name:\"abc\"})create (m:Person {name:\"pqr\"})"
def print_friends_of(name):
    with driver.session() as session:
        with session.begin_transaction() as tx:
            print(tx, dir(tx))
            tx.run(multipleCreate)
```

As shown above, the user has to maintain everything about the batching process (batch size, constructing batch query etc).
Is there an easier way for creating batch transaction and committing it at the end (like [here)](http://neo4j-rest-client.readthedocs.io/en/latest/transactions.html?highlight=tx.append)

**Comment by lutovich** [comment]
Hi @manojgudi,

Driver does not expose such functionality in the interface. You could use `UNWIND` Cypher clause to provide query once with all needed params. See [this developer manual section](https://neo4j.com/docs/developer-manual/current/cypher/syntax/parameters/#cypher-parameters-create-multiple-nodes-with-properties).

Example might look like:

```python
query = "UNWIND $names AS n CREATE (p:Person {name: n})"
names = ["abc", "pqr"]
with driver.session() as session:
    with session.begin_transaction() as tx:
        tx.run(query, names=names)
```

Hope this helps.

**Comment by manojgudi** [comment]
Thanks for the prompt reply @lutovich !
The CREATE/MERGE queries are little more complicated than what I posted above, lemme see if I can modify it with `UNWIND`
Is support for batch operations in the roadmap?

**Comment by lutovich** [comment]
@manojgudi I'm not quite sure about batch operations in the roadmap. We discussed at some point a possibility of having `#run()` method that accepts a query and a list of params to execute with. It is essentially `UNWIND` but does not require users to modify the query. Do you think this might be useful?

@nigelsmall maybe you could share more thoughts on batch operations?

**Comment by manojgudi** [comment]
@lutovich Yes it would be super useful. For example, I am trying to consume messages from a queue; and since we fetch messages in batches from the queue, I might as well process and write those messages in a batch-mode in neo4j.

**Comment by technige** [comment]
@manojgudi I'd like to understand more about what you're trying to achieve here. Batching could refer to one of several things, such as reducing duplication of similar Cypher statement or explicit control of network sync. We do some of this automatically inside the driver so it would be good to understand where this isn't working for you.

**Comment by technige** [comment]
Closing as no more information available.

**Comment by nickithewatt** [comment]
This would be quite helpful for us too actually...

We have a scenario where we are having to do bulk ingestion, however the ingestion process itself is pretty idempotent and deterministic and should not create duplicates etc. It does however take its time if there is a lot to ingest and we would prefer to just have the ability to do a bulk / batch update and gain the speed - in this case we do not need transactional guarantees.

**Comment by maaland** [comment]
any new info here? @nickithewatt I have the same need as you, did you find a good way to do this?

**Comment by robsdedude** [comment]
You may have a look at our docs about importing data in general [https://neo4j.com/docs/getting-started/data-import/](https://neo4j.com/docs/getting-started/data-import/). Hopefully you can find something that suits your needs there.
