### ISSUE TITLE
Conditions for "Transaction rolled back even if marked as succesful"

### ISSUE THREAD

**Issue by aanastasiou** [neo4j/neo4j-python-driver#217]
Hello

I am dealing with [this](https://github.com/neo4j-contrib/neomodel/issues/303) issue on Neomodel whose underlying cause seems to be extending to the Neo4J driver.

Although I have been prompted to report it as an issue here, I am not entirely convinced that this is a driver issue.

I would therefore appreciate some insight into why a `Neo.ClientError.Schema.ConstraintValidationFailed` might also be triggering a `ClientError` exception.

I suspect that it has something to do with the internal state of the driver / dbms and therefore it might be something that [we need to take into account when gracefully handling exceptions within Neomodel.](https://github.com/neo4j-contrib/neomodel/blob/master/neomodel/util.py#L134)

All the best

P.S. Although this exception is raised and [according to the error codes](https://neo4j.com/docs/developer-manual/current/reference/status-codes/) the transaction is supposed to have been rolled back, the transaction is actually committed. In this case what I would also like to ask is if we can safely ignore this particular exception if it comes up on a commit (?) (But still raise anything else that might have good reasons to happen during a commit (?))

**Comment by jexp** [comment]
@aanastasiou would it be possible to extract the issue into something reproducible outside of neomodel? Or at least share a test case that creates this issue so that the drivers team can just run this and report back? 

Thank you,

Michael

**Comment by aanastasiou** [comment]
@jexp there is a brief test case [here](https://github.com/neo4j-contrib/neomodel/issues/303), but I tried to replicate the error using ONLY neo4j calls with the following snippet.

I cannot tell if the driver is a contributing factor here. I **think** I understand what is going on (which I explain after the snippet) but if you can confirm / reject this explanation I guess it would be helpful too:

```
import os
import neomodel
import neo4j

# Set up a very simple model for the tests
class PersonalRelationship(neomodel.StructuredRel):
    """
    A very simple relationship between two basePersons that simply records 
    the date at which an acquaintance was established.
    This relationship should be carried over to anything that inherits from 
    basePerson without any further effort.
    """
    on_date = neomodel.DateProperty(default_now = True)
    
class BasePerson(neomodel.StructuredNode):
    """
    Base class for defining some basic sort of an actor.
    """
    name = neomodel.StringProperty(required = True, unique_index = True)
    friends_with = neomodel.RelationshipTo("BasePerson", "FRIENDS_WITH", model = PersonalRelationship)
    
class TechnicalPerson(BasePerson):
    """
    A Technical person specialises BasePerson by adding their expertise
    """
    expertise = neomodel.StringProperty(required = True)
    
class PilotPerson(BasePerson):
    """
    A pilot person specialises BasePerson by adding the type of airplane they can operate
    """
    airplane = neomodel.StringProperty(required = True)

if __name__ == "__main__":
    driver = neo4j.v1.GraphDatabase.driver("bolt://localhost:7687",auth=(os.environ["NEO4J_USERNAME"],os.environ["NEO4J_PASSWORD"]))
    session = driver.session()
    
    session.run("CREATE (a:TechnicalPerson:BasePerson{{name:'{}', expertise:'{}'}})".format("Grumpy", "Grumpiness"))
    
    with session.begin_transaction() as tx:              
        try:
            try:
                response = tx.run("CREATE (a:TechnicalPerson:BasePerson{{name:'{}', expertise:'{}'}}) return id(a)".format("Grumpy", "Grumpiness"))
                #TEST POINT: COMMENT THE NEXT LINE
                results,meta = [list(r.values()) for r in response], response.keys()
            except neo4j.v1.CypherError as ce:
                if ce.code == u'Neo.ClientError.Schema.ConstraintValidationFailed':
                    if 'already exists with label' in ce.message:
                        raise neomodel.exception.UniqueProperty(ce.message)
                    raise neomodel.exception.ConstraintValidationFailed(ce.message)
                else:
                    exc_info = sys.exc_info()
                    if sys.version_info >= (3, 0):
                        raise exc_info[1].with_traceback(exc_info[2])
                    else:
                        raise exc_info[1]
        except neomodel.exception.UniqueProperty:
            r = [item for item in tx.run("MATCH (a:TechnicalPerson:BasePerson{{name:'{}', expertise:'{}'}}) return a".format("Grumpy", "Grumpiness"))]
```

**To reproduce:**
1. Save the above as `someFile.py`
1. `neomodel_install_labels --db bolt://$NEO4J_USERNAME:$NEO4J_PASSWORD@localhost:7687 someFile.py` (This is still needed to apply the constraints)
1. `python someFile.py`

This returns `ClientError: Transaction rolled back even if marked as successful`


I am not really sure what the problem is here because of the following behaviour:

1. If you try to comment `TEST POINT`, then the driver generates `ConstraintError: Node(###) already exists with label `TechnicalPerson` and property `name` = 'Grumpy'`. So far so good. The trouble is that this is **uncatchable**. This is a ConstraintError but if you try to `except:` (**from within `someFile.py`**) it simply does not go into it. It raises the exception within `neo4j/v1/result.py` and that's it, it exits right there.

2. If you **don't** comment `TEST POINT`, then the driver DOES NOT raise a ConstraintError on `tx.run` (!) but when you try to retrieve `results` it returns the completely misleading `Transaction rolled back even if marked as successful`.

My question right now is this: Should we expect that **any** exception within a transaction terminates it? Because if this is the intended behaviour from the point of view of the neo4j driver then this simply needs to be mentioned in the `neomodel` documentation and in a way, it would also cancel the `with transaction:` pattern. Because, anything that might go wrong in a transaction would cancel the whole block of operations(?).

In my use case for example, I might have 1500 writes before I come across one that violates the constraint and that rolls back everything. And there is no way around it too, EXCEPT, determining beforehand the unique writes and creating a transaction block just for them. But that is not always possible.

**Comment by technige** [comment]
I may have missed some of the detail of the problem as I'm reading this on my phone and can't try out any of the code you post. However in terms of the specific question you ask at the end, it is the case that any exception within a transaction will terminate it.

**Comment by aanastasiou** [comment]
I have seen your response and thank you very much for confirming this. In the short term, it would change the way we interact with the driver whether via neomodel or directly. I would however also welcome a revised comment once you had more time to review the behaviour I am outlining here, perhaps going through the example. I cannot say with confidence that I am clear about the cause of the error and I don't want to keep repeating the same approach.

**Comment by technige** [comment]
Please drop me a line via email if possible (nigel at neo4j dot com). I think we would benefit from arranging a higher bandwidth conversation around this. Also, I'm interested in talking more about neomodel in general.

**Comment by aanastasiou** [comment]
Nigel, thank you very much for that brief chat, it was incredibly useful.

For the "record" :), the behaviour we are encountering here is reasonable given the way information is passed back and forth between the server and client (which can reside on entirely different end points within a network).

Specifically, the server does not inform the client on every little change of state, *except*,  when specific actions are carried out. 

This is why, in our case, the exception might be taking place within the `run`, but we only find out during the retrieval of the results. 

Synchronising state for all actions can be costly and this is why it is avoided. We can however trigger a synchronisation via the `sync` method of the `session` object and this is probably the best option here, now that we know that we might run into this problem.
