### ISSUE TITLE
Exception thrown running Django including manage.py migrate

### ISSUE THREAD

**Issue by andyp05** [neo4j/neo4j-python-driver#232]
I know there are a couple threads with this error. I have read them all.

Get the following error running django runserver or migrate. For runserver, the exception comes up on load, not on exit. I have tried latest stable and new alpha release. I get the same error. 

Is there a way to trap the exception on the close() event if already set to None?

I tried adding the following to my database class that handles all Neo4j calls.

```
    def __del__(self):
        if self.driver:
            self.driver.close()
```

Any suggestions would be appreciated. Thanks.

`Exception ignored in: <bound method Connection.__del__ of <neo4j.bolt.connection.Connection object at 0x000001F981177278>>
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\neo4j\bolt\connection.py", line 216, in __del__
  File "C:\Python36\lib\site-packages\neo4j\bolt\connection.py", line 389, in close
  File "C:\Python36\lib\logging\__init__.py", line 1293, in debug
  File "C:\Python36\lib\logging\__init__.py", line 1546, in isEnabledFor
TypeError: '>=' not supported between instances of 'int' and 'NoneType'`

**Comment by technige** [comment]
@andyp05 Thanks for reporting, I'll have a look at fixing this.

**Comment by technige** [comment]
Given that errors on object deletion can easily be ignored, this should do it:
https://github.com/neo4j/neo4j-python-driver/commit/2db03599b56ac58588558ebda4f02f67aca0194f
