### ISSUE TITLE
Neo4j-driver not imported

### ISSUE THREAD

**Issue by yasseraj** [neo4j/neo4j-python-driver#235]
I have installed neo4j-driver in a virtualenv with python 3.6, using pycharm's package installer, when I open the python shell and type:
`from neo4j.v1 import GraphDatabase`
the import works just fine. Now, when I create a python script file, and make sure it's using the virtualenv with the following content:
`from neo4j.v1 import GraphDatabase`
All I get is this error:
`No module named 'neo4j.v1'; 'neo4j' is not a package`
For the life of me, I can't figure where the problem is, I am on Mac OS Sierra.
Any help is much appreciated.

**Comment by technige** [comment]
Sounds like an import or PYTHONPATH mixup somewhere. If you do `pip freeze` from the console (within the venv) is it there? It should be if it's installed properly.

**Comment by Baschdl** [comment]
Had the same issue, our problem was that we had a module name `neo4j`

**Comment by yasseraj** [comment]
This is the result of pip freeze:
`(venv) MBP-de-yas:MongoDB yasos$ pip freeze`
`branca==0.2.0
certifi==2018.4.16
chardet==3.0.4
click==6.7
folium==0.5.0
geojson==2.3.0
geomet==0.2.0.post2
grako==3.99.9
idna==2.6
ijson==2.3
Jinja2==2.10
kiwisolver==1.0.1
MarkupSafe==1.0
mongoengine==0.15.0
neo4j-driver==1.5.3
parsewkt==0.1.dev0
pymongo==3.6.0
requests==2.18.4
scales==1.0.9
Shapely==1.6.4.post1
six==1.11.0
urllib3==1.22
`
I have tried to create another project which contained only 
`neo4j-driver==1.5.3
`
It works just fine, I can do the import and no problem, so I guess there's some kind of issue with one of those packages I have installed and are shown in first freeze, maybe they clash with the neo4j-driver.
I should have noted that am using pip 9.0.1

**Comment by yasseraj** [comment]
Ok, I didn't test it well, but when using neo4j without all those packages I showed in the previous message, it works just fine, so probably it's some clash between packages. I would consider this as solved by doing a cleanup in the virtualenv.
