### ISSUE TITLE
Getting a error when trying to run the Quick Example from the README

### ISSUE THREAD

**Issue by aaronlelevier** [neo4j/neo4j-python-driver#239]
When trying to run the [Quick Example](https://github.com/neo4j/neo4j-python-driver#quick-example):

```python
from neo4j.v1 import GraphDatabase

driver = GraphDatabase.driver("bolt://localhost:7687", auth=("neo4j", "password"))

def add_friends(tx, name, friend_name):
    tx.run("MERGE (a:Person {name: $name}) "
           "MERGE (a)-[:KNOWS]->(friend:Person {name: $friend_name})",
           name=name, friend_name=friend_name)

def print_friends(tx, name):
    for record in tx.run("MATCH (a:Person)-[:KNOWS]->(friend) WHERE a.name = $name "
                         "RETURN friend.name ORDER BY friend.name", name=name):
        print(record["friend.name"])

with driver.session() as session:
    session.write_transaction(add_friends, "Arthur", "Guinevere")
    session.write_transaction(add_friends, "Arthur", "Lancelot")
    session.write_transaction(add_friends, "Arthur", "Merlin")
    session.read_transaction(print_friends, "Arthur")
```

It returns:

```
Traceback (most recent call last):
  File "query.py", line 3, in <module>
    driver = GraphDatabase.driver("bolt://localhost:7687", auth=("neo4j", "password"))
  File "/Users/aaron/Documents/neo4j/venv/lib/python3.6/site-packages/neo4j/v1/api.py", line 128, in driver
    return driver_class(uri, **config)
  File "/Users/aaron/Documents/neo4j/venv/lib/python3.6/site-packages/neo4j/v1/direct.py", line 77, in __init__
    pool.release(pool.acquire())
  File "/Users/aaron/Documents/neo4j/venv/lib/python3.6/site-packages/neo4j/v1/direct.py", line 47, in acquire
    connection = self.acquire_direct(address)  # should always be a resolved address
  File "/Users/aaron/Documents/neo4j/venv/lib/python3.6/site-packages/neo4j/bolt/connection.py", line 427, in acquire_direct
    raise ValueError("Invalid IP address {!r}".format(address[0]))
ValueError: Invalid IP address 'fe80::1%lo0'
```

If you change the 2nd line to be a ip4 address for `localhost` to the IP address it works:

```python
driver = GraphDatabase.driver("bolt://127.0.0.1:7687", auth=("neo4j", "password"))
```

I saw this while using `pdb` to poke around:

```
> /Users/aaron/Documents/neo4j/venv/lib/python3.6/site-packages/neo4j/v1/direct.py(46)acquire()
-> for address in resolve(self.address):
(Pdb) self.address
Address(host='localhost', port=7687)
(Pdb) resolve(self.address)
[('::1', 7687, 0, 0), ('127.0.0.1', 7687), ('fe80::1%lo0', 7687, 0, 1)]
```

Not sure if the solution is to fix the README or change some other logic so that `localhost` works.

**Comment by technige** [comment]
Judging by your `resolve` output there, it looks like there's something screwy with how localhost is being resolved on your machine. The first two results look correct, the last one is completely odd and contains illegal characters for an IPv6 address. I'd start by looking for unusual entries in your hosts file. This doesn't look like an issue with either the driver or the example code.

**Comment by aaronlelevier** [comment]
@technige you were totally write. I did a google just now and saw in my `/etc/hosts` that odd entry `'fe80::1%lo0'`. 

I removed it and now all is working.  

Thank you for your reply. I will close this.

**Comment by technige** [comment]
A more enlightened colleague has pointed out that this is a valid (albeit esoteric) form of address used mainly for internal purposes. So it seems I've misinformed you. Sorry about that!

I'll do some more research and look at how we enable the drivers to deal with these addresses, possibly by simply ignoring them.

Apologies again for my earlier error.

**Comment by technige** [comment]
@aaronlelevier Which version of the driver have you been using?

**Comment by aaronlelevier** [comment]
@technige I was using `neo4j-driver==1.5.3`

**Comment by technige** [comment]
These addresses will now be skipped over (https://github.com/neo4j/neo4j-python-driver/commit/64b0c612cc66f1c79c084874886b0dcd25eff306)
