### ISSUE TITLE
Question: Convert to Python datetime

### ISSUE THREAD

**Issue by g3rd** [neo4j/neo4j-python-driver#246]
Hello,

How do I convert the `neotime.DateTime` instance to a Python `datetime.datetime` instance?

But what I really need is the epoch seconds. Or to do:

```
mydate.timestamp()
```

Right now I'm doing:

```python
import datetime
from neotime import DateTime

dt = DateTime(year=2018, month=9, day=26, hour=13, minute=31, second=5.0)
pdt = datetime.datetime(dt.year, dt.month, dt.day, dt.hour, dt.minute, int(dt.second))
timestamp = pdt.timestamp()
```

With this example, I'm losing milliseconds.

See: https://github.com/technige/neotime/issues/3

**Comment by technige** [comment]
Closing here as answered in https://github.com/neo4j-drivers/neotime/issues/3.
