### ISSUE TITLE
Breaking API changes

### ISSUE THREAD

**Issue by danodonovan** [neo4j/neo4j-python-driver#248]
It seems that `v1.6` has changes that break the `v1.5` API.

For example 
* `Node` objects no longer have a `properties` attribute
*  response `.values()` for more than one row returns the rows as `list`s not `tuple`s
*  other changes I'm yet to discover (?)

It would be nice if these changes were mentioned somewhere, maybe a [CHANGELOG](https://keepachangelog.com/en/1.0.0/) etc. ?

**Comment by danodonovan** [comment]
Ok - sorry, I see https://github.com/neo4j/neo4j-python-driver/wiki/1.6-changelog now  - but this doesn't seem to mention the API changes.

**Comment by technige** [comment]
Apologies for this. I'll get the changes documented.

**Comment by technige** [comment]
Items added to 1.6 changelog
