### ISSUE TITLE
neo4j.exceptions.ServiceUnavailable

### ISSUE THREAD

**Issue by aqzwy** [neo4j/neo4j-python-driver#254]
After a period of normal operation, the program went wrong.

neo4j.exceptions.ServiceUnavailable: Cannot acquire connection to Address(host=bolt_url, port=7687) 

There is no error in restarting the program. After a while, the same mistake will occur.

I use neo4j.v1-1.5.3

**Comment by technige** [comment]
Sorry, but there isn't enough information here to be able to help you. There could be many reasons why this happens: what is your network topology and what type of server (standalone, cluster) are you talking to? Is there any third party network services that kill idle connections? Do you use Bolt direct or routing? And how is your code structured around this failure? Do you get a stack trace?

**Comment by zhenlineo** [comment]
@aqzwy 

Closing this issue as missing information to continue.
Pls be free to reopen this issue with more information.
