### ISSUE TITLE
TransientError and performance bottleneck

### ISSUE THREAD

**Issue by MS-AvivG** [neo4j/neo4j-python-driver#264]
Hi fellows!

I have a persistent problem that I'm struggling to solve.
I run the following query:

    MATCH (person: Person {name: 'Mark'})
    WITH person
    UNWIND person.match_list AS match
    MATCH (pet: Animal) 
    WHERE pet.name_regex =~ match
    MERGE (person)-[:OWNS_PET]->(pet) 
    RETURN pet

The query matches a person by name (unique index) and unwinds its match_list, which is a list of regular expressions. Then for each regular expression, I check if any pet name matches (~10 regular expressions in match_list, ~20K Person nodes, ~30k Animal nodes, ~500k total nodes & relationships) and if I get a match I connect the Person and the Animal nodes.

However, this query has two drawbacks:

1. It is running very slow (more than 500ms to complete on 4 cores workstation 32GB RAM)
2. When I run it multithreaded I get the following exception:

```
    neo4j.exceptions.TransientError: ForsetiClient[3] can't acquire ExclusiveLock{owner=ForsetiClient[14]} on NODE(1889), because holders of that lock are waiting for ForsetiClient[3].
     Wait list:ExclusiveLock[
    Client[14] waits for [3]]
```

My stack is as follows:

- native graph python driver
- celery with gevent as pool

I will be glad to improve this query performance and/or fix the multithreading problem. 
Thanks :)

**Comment by technige** [comment]
@MS-AvivG This doesn't look like a driver bug. Could you perhaps post details in https://community.neo4j.com/ if you're after Cypher tuning advice.
