### ISSUE TITLE
Asyncio support

### ISSUE THREAD

**Issue by mjmare** [neo4j/neo4j-python-driver#272]
It would be nice to have async support in the Neo4j python driver.

**Comment by technige** [comment]
Duplicate of https://github.com/neo4j/neo4j-python-driver/issues/180 - this has already been added to our roadmap.

**Comment by technige** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Python Driver: drop support for Python 2](https://trello.com/c/j8YvoLHZ/278-python-driver-drop-support-for-python-2)
