### ISSUE TITLE
Python neo4j bolt driver loses connection after context switch

### ISSUE THREAD

**Issue by Sasorien** [neo4j/neo4j-python-driver#273]
Hello there, 

i still have a problem with this driver, that can't be answered on StackOverflow yet.
I hope here are some specialists that can help me out on this.

Summary:
I have a backend written in django which uses the neo4j bolt driver to communicate with the neo4j graph db.
I use a Singleton to handle the connection and the bolt driver closes the connection, whenever I access it from another location than where the connection was initially established (e.g. I open the connection in a view, access it in a signal and when I try to save in the view the connection is lost).

The full StackOverflow question with example code: https://stackoverflow.com/questions/53190676/python-neo4j-bolt-driver-loses-connection-after-context-switch

Some Additional infos according to the contributing guidelines i missed in the StackOverflow question:
We're operating on Windows10 and Mac OS Mojave and currently using Neo4j 3.4.5 as a single machine and Python 3.6.5.

**Comment by technige** [comment]
You mention a singleton to handle the "connection". Given that the driver has no public `Connection` object, what do you mean here? Are you using `Session` and `Transaction` objects as intended? Neither are thread-safe and should therefore not be passed between threads or kept as globals. The `Driver` object is the only one that should be used this way.

The manual and the API docs contain details and examples on how we've designed these objects to be used:
- https://neo4j.com/docs/developer-manual/current/drivers/
- https://neo4j.com/docs/api/python-driver/current/

**Comment by technige** [comment]
The post below might be useful on implementing a singleton correctly:
https://community.neo4j.com/t/neo4j-python-driver-service-unavailable/4111/13
