### ISSUE TITLE
empty result for simple MATCH query on non empty db

### ISSUE THREAD

**Issue by simkoc** [neo4j/neo4j-python-driver#275]
I am using:
neo4j-driver 1.7.1
python 3.6.7

It might be related to issue #134 - I am getting an empty result for just querying 3 arbitrary nodes from the database:

```
from neo4j import GraphDatabase


HOST = "bolt://localhost"
USER = "neo4j"
PASSWORD = "123456"


def connect(host=HOST, user=USER, pwd=PASSWORD):
    return GraphDatabase.driver(host, auth=(user, pwd))


def run_cypher_query(session, query):
    return session.run(query)


with connect() as driver:
    with driver.session() as sess:
        print(run_cypher_query(sess, "MATCH (m) RETURN m LIMIT 3").__dict__)
```

The result is

`{'_session': <neo4j.Session object at 0x7fd1a05be7f0>, '_hydrant': <neo4j.types.PackStreamHydrator object at 0x7fd1a058b518>, '_metadata': {'statement': 'MATCH (m) RETURN m LIMIT 3', 'parameters': {}, 'server': <neobolt.direct.ServerInfo object at 0x7fd191c366d8>, 'protocol_version': 3, 't_first': 0, 'fields': ['m']}, '_records': deque([]), '_summary': None}`

which cannot be as the database contains 251 nodes.

**Comment by technige** [comment]
What makes you think this signifies an empty result? The `'_records': deque([])` part?

You're not consuming the result, you're merely inspecting the internal attributes of the object returned from the `session.run` call, which will tell you nothing about the records themselves.

As per the manual and API docs, you'll need to iterate through the result object to consume the records. Using a `for record in result` structure or wrapping the result in a `list` are two ways to do this. You can alternatively use the `result.data()` method to extract everything into a list of dictionaries.

I suggest having a read of the following:
- https://neo4j.com/docs/driver-manual/current/cypher-values/#driver-result
- https://neo4j.com/docs/api/python-driver/1.7/results.html

**Comment by simkoc** [comment]
True, the given example was not extensive enough sorry for that. The actual representation of the problem however was:

```
with connect() as driver:
    with driver.session() as sess:
        print(run_cypher_query(sess, "MATCH (m) RETURN m LIMIT 3")._records.pop())
```

resulting in

`IndexError: pop from an empty deque`

However, using the iteration method it works, which is unexpected but neat.

Thank you for the quick answer.

**Comment by technige** [comment]
In Python, attributes starting with an underscore are internal by convention. Therefore, I'd strongly recommend against building any code that relies on these.
