### ISSUE TITLE
Query time is always returning as 0

### ISSUE THREAD

**Issue by bavalpey** [neo4j/neo4j-python-driver#296]
## Bolt driver 

I am trying to time the execution of queries in Neo4j.  There was a [stackoverflow post](https://stackoverflow.com/questions/49859311/how-to-get-the-execution-time-of-a-cypher-query-from-python) detailing how to do this, and I followed the steps for a simple query on my database.  I am getting back records, however, the time is always 0.  It also does not specify what unit the time should be in (anywhere in the limited documentation).
I run the same query on Neo4j directly and the execution time is around 1200ms.  Is there no way to get this number from the bolt connector?

**Neo4j Version:** 3.5.8 Community  
**Neo4j Mode**: Single instance  
**Driver version**: Python driver 1.7.1  
**Operating System:** Ubuntu 18.04.2 LTS

### Steps to reproduce
1. Start Neo4j
2. Connect to Neo4j using the GraphDatabase driver
3. Start a session and complete a transaction.
4. Call summary().result_available_after and summary().result_consumed_after and notice both are 0
### Expected behavior
The time should be at least greater than 0
### Actual behavior
The query time is 0

I can attach my code if necessary, but I essentially just followed the example posted on the stackoverflow post I mentioned.

**Comment by dennlinger** [comment]
I encounter a similar issue, although in my case the result is always `None`, which leaves me to wonder why it was not set correctly in the first place. The query does indeed return a valid result, though, so it is certainly not the fault of the query...

**Comment by martin-neotech** [comment]
https://github.com/neo4j/neo4j-python-driver/wiki/1.7-changelog#176
