### ISSUE TITLE
[Feature Request] Base Neo4j Exception

### ISSUE THREAD

**Issue by john-bodley** [neo4j/neo4j-python-driver#298]
Currently there are a number of [exceptions](https://github.com/neo4j/neo4j-python-driver/blob/4.0/neo4j/exceptions.py) which are derived directly from `Exception`: 

- `ConnectionExpired`
- `CypherError`
- `IncompleteCommitError`
- `ProtocolError`
- `SecurityError`
- `ServiceUnavailable`

which leads to a fairly verbose try/except clause if one specifically wants to catch Neo4j exceptions. I was wondering whether there should be a base Neo4j exception which these six exceptions are derived from, i.e., 

```
class Neo4jException(Exception):
   """ Base Neo4j exception. 
   """


class ProtocolError(Neo4jException):
    """ Raised when an unexpected or unsupported protocol event occurs.
    """

...
```

which would mean one could simply do, 

```
try:
    with GraphDatabase.driver(...).session() as session():
        ...
except Neo4jException:
    ...
```

**Comment by technige** [comment]
The exceptions are being revised as part of the next major release cycle. This will include a more sensible hierarchy for the exception classes.

**Comment by martin-neotech** [comment]
@john-bodley The alpha release of 4.0 have the new structure of errors:

```
Driver API Errors
=================
+ Neo4jError
  + ClientError
    + CypherSyntaxError
    + CypherTypeError
    + ConstraintError
    + AuthError
    + Forbidden
      + ForbiddenOnReadOnlyDatabase
    + NotALeader
  + DatabaseError
  + TransientError
    + DatabaseUnavailable

+ DriverError
  + TransactionError
    + TransactionNestingError
  + SessionExpired
  + ServiceUnavailable
    + RoutingServiceUnavailable
    + WriteServiceUnavailable
    + ReadServiceUnavailable
  + ConfigurationError
    + AuthConfigurationError
    + CertificateConfigurationError
  + ResultConsumedError
```
