### ISSUE TITLE
query to server Neo4j instance hangs without any error

### ISSUE THREAD

**Issue by Zhenshan-Jin** [neo4j/neo4j-python-driver#300]
- Neo4j version: Community 3.5.9
- Neo4j Mode: Single instance(docker)
- Driver version: python driver 1.7.4
- Operating system: Ubuntu 16.10 on GCP
- **Steps to reproduce**
1. send cypher query from a GCP VM to Azure VM, where the neo4j instance is hosted and the neo4j instance is hosted in a docker
- Expected behavior
create node/link and return the node id
- Actual behavior
The process hangs there without any response, no error until we kill the process.
It happens from time to time and when it happens the neo4j instance is still alive and I can send a query through neo4j browser.
The actual query is light if I run the query which hangs, it takes less than one second to run in the neo4j browser

We have been solving this issue for a while and haven't got a clue yet. Any suggestions about how to solve the issue or the way that we can look for to solve the issue is welcome!
Thank you in advance.

**Comment by technige** [comment]
Given the nature of the problem, this is very likely an infrastructural issue on your side. As such, we can't really offer any advice on how to fix it.

The driver uses regular TCP communications, so you should be able to monitor the network and carry out diagnostic tests using normal network tooling.
