### ISSUE TITLE
MATCH with neotime.Datetime params on value datetime("2019-10-30T07:54:02.129790999[UTC]")

### ISSUE THREAD

**Issue by huumq00731** [neo4j/neo4j-python-driver#306]
## Example bug report

Can not MATCH with datetime value: "2019-10-30T07:54:02.129790999[UTC]

**Neo4j Version:** : 3.5.11  Community  
**Neo4j Mode**: Single instance  
**Driver version**: Python driver 1.7.5  
(Python lib: neo4j==1.7.5, neobolt==1.7.15, neotime==1.7.4)
**Operating System:** Window 10 64bit

### Steps to reproduce
1. Start Neo4j.
2. Run a query with browser:
CREATE (t:TEST {update_date:datetime("2019-10-30T07:54:02.129790999[UTC]")})

3. Run python code
```javascript
from neo4j import GraphDatabase
from neobolt.security import ENCRYPTION_OFF

driver = GraphDatabase.driver("bolt://127.0.0.1:7687", auth=("neo4j", "mchc2019"), encrypted=ENCRYPTION_OFF)
with driver.session() as session:
    search_query = "MATCH (t:TEST) RETURN t"
    result = session.run(search_query)
    for record in result.records():
        print(record["t"])
        last_date = record["t"].get("update_date")
        
    search_query1 = "MATCH (t:TEST) WHERE t.update_date=$last_date RETURN t"
    result1 = session.run(search_query1, last_date=last_date)
    for record1 in result1.records():
        print(record1["t"])
```

### Expected behavior
Out put is:

<Node id=248 labels={'TEST'} properties={'update_date': neotime.DateTime(2019, 10, 30, 7, 54, 2.129790999, tzinfo=<UTC>)}>
Have record
<Node id=248 labels={'TEST'} properties={'update_date': neotime.DateTime(2019, 10, 30, 7, 54, 2.129790888, tzinfo=<UTC>)}>

### Actual behavior
Out put is:

<Node id=248 labels={'TEST'} properties={'update_date': neotime.DateTime(2019, 10, 30, 7, 54, 2.129790999, tzinfo=<UTC>)}>

**Comment by huumq00731** [comment]
Same problem with datetime value = "2019-10-31T05:41:16.065365999[UTC]"

**Comment by technige** [comment]
Looks like a possible rounding/precision issue, likely around passing `neotime.DateTime` values in as parameters. This issue can be more succinctly recreated using the code below:

```
>>> from neo4j import GraphDatabase
>>> d = GraphDatabase.driver("bolt://", auth=("neo4j", "password"))
>>> s = d.session()
>>> dt1 = s.run("RETURN datetime('2019-10-30T07:54:02.129790999[UTC]')").single().value()
>>> dt2 = s.run("RETURN $x", x=dt1).single().value()
>>> dt1
neotime.DateTime(2019, 10, 30, 7, 54, 2.129790999, tzinfo=<UTC>)
>>> dt2
neotime.DateTime(2019, 10, 30, 7, 54, 2.129790998, tzinfo=<UTC>)
```

**Comment by martin-neotech** [comment]
This have been fixed with PR https://github.com/neo4j/neo4j-python-driver/pull/412 for the upcoming 4.0.0 driver.

**Comment by martin-neotech** [comment]
@technige https://github.com/neo4j-drivers/neotime/pull/10

**Comment by martin-neotech** [comment]
For driver 1.7 that uses `neotime` this PR have been merged now. https://github.com/neo4j-drivers/neotime/pull/10
