### ISSUE TITLE
Underlying socket connection gone (_ssl.c:1866)

### ISSUE THREAD

**Issue by MrRace** [neo4j/neo4j-python-driver#317]
**Environment**：
**Neo4j Version:** 3.5.12 Community  
**Driver version**: Python driver 1.7.6  

I have lots of "MACTH" statements, after hundreds of  execution, error comes below:
ERROR：
```
Failed to write data to connection Address(host='X.X.X.X', port=7688) (Address(host='X.X.X.X', port=7688) ); ("0; 'Underlying socket connection gone (_ssl.c:1866)'")
Failed to write data to connection Address(host='X.X.X.X', port=7688) (Address(host='X.X.X.X', port=7688)); ("0; 'Underlying socket connection gone (_ssl.c:1866)'")
```
What should I do to avoid the error? Thanks a lot!

**Comment by martin-neotech** [comment]
The error message is being removed in an update to neobolt.
