### ISSUE TITLE
`session = driver.session()` pylint e1111

### ISSUE THREAD

**Issue by dcsan** [neo4j/neo4j-python-driver#321]
This works as documented:

      with driver.session() as session:

but my linter throws an error on this:

      session = driver.session()

      > Assigning result of a function call, where the function has no returnpylint(assignment-from-no-return)

[![enter image description here][1]][1]

I thought that [`with`](https://www.geeksforgeeks.org/with-statement-in-python/) was just a syntax sugar to handle closing handles etc.

Note that the code itself will run but the linter errors are really distracting.
Is there a way to fix the original codes such that the linter doesn't choke?

I'm trying to get a session object to use for multiple transactions (or the lifetime of my app)
https://neo4j.com/docs/api/python-driver/current/driver.html#neo4j.Driver.session

  [1]: https://i.stack.imgur.com/lwu6z.png

**Comment by martin-neotech** [comment]
> A session is a container for a sequence of transactions. Sessions borrow connections from a pool as required and so should be considered lightweight and disposable.

https://neo4j.com/docs/driver-manual/1.7/sessions-transactions/

A session object should be created and disposed of, do not use it as a long lived object through the app.

It is the pylint tool that reports a http://pylint-messages.wikidot.com/messages:e1111

**Read:** https://stackoverflow.com/questions/39847884/can-i-get-pycharm-to-suppress-a-particular-warning-on-a-single-line
