### ISSUE TITLE
How to connect to neo4j 4.0 using this driver?

### ISSUE THREAD

**Issue by naughtyGitCat** [neo4j/neo4j-python-driver#335]
Does driver 1.7.6 support neo4j4.0?

```bash
  File "/home/dba/db_neo4j/adapters/neo4j.py", line 24, in initialize_neo4j_pool
    password=Neo4jConfig.password))
  File "/home/dba/db_neo4j/python3/lib/python3.7/neo4j/__init__.py", line 120, in driver
    return Driver(uri, **config)
  File "/home/dba/db_neo4j/python3/lib/python3.7/neo4j/__init__.py", line 161, in __new__
    return subclass(uri, **config)
  File "/home/dba/db_neo4j/python3/lib/python3.7/neo4j/__init__.py", line 235, in __new__
    pool.release(pool.acquire())
  File "/home/dba/db_neo4j/python3/lib/python3.7/neobolt/direct.py", line 715, in acquire
    return self.acquire_direct(self.address)
  File "/home/dba/db_neo4j/python3/lib/python3.7/neobolt/direct.py", line 608, in acquire_direct
    connection = self.connector(address, error_handler=self.connection_error_handler)
  File "/home/dba/db_neo4j/python3/lib/python3.7/neo4j/__init__.py", line 232, in connector
    return connect(address, **dict(config, **kwargs))
  File "/home/dba/db_neo4j/python3/lib/python3.7/neobolt/direct.py", line 972, in connect
    raise last_error
  File "/home/dba/db_neo4j/python3/lib/python3.7/neobolt/direct.py", line 963, in connect
    s, der_encoded_server_certificate = _secure(s, host, security_plan.ssl_context, **config)
  File "/home/dba/db_neo4j/python3/lib/python3.7/neobolt/direct.py", line 854, in _secure
    s = ssl_context.wrap_socket(s, server_hostname=host if HAS_SNI and host else None)
  File "/home/dba/db_neo4j/python3/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/home/dba/db_neo4j/python3/lib/python3.7/ssl.py", line 850, in _create
    self.do_handshake()
  File "/home/dba/db_neo4j/python3/lib/python3.7/ssl.py", line 1108, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
```

**Comment by naughtyGitCat** [comment]
```bash
Collecting neo4j==4.0
  Could not find a version that satisfies the requirement neo4j==4.0 (from versions: 1.7.0b1, 1.7.0b2, 1.7.0b3, 1.7.0b4, 1.7.0rc1, 1.7.0rc2, 1.7.0, 1.7.1, 1.7.2, 1.7.3, 1.7.4, 1.7.5, 1.7.6)
No matching distribution found for neo4j==4.0
You are using pip version 18.1, however version
```

**Comment by naughtyGitCat** [comment]
Manually cp the 4.0 branch neo4j/ dir to my project dir fix it, but it sucks to deal with this dirty way🙃

**Comment by naughtyGitCat** [comment]
both make dist and make docs failed

**Comment by krisgeus** [comment]
I managed to create a distribution bij changing the `bin/dist-functions` a bit.

```
diff --git a/bin/dist-functions b/bin/dist-functions
index d83c296..dc4f26f 100644
--- a/bin/dist-functions
+++ b/bin/dist-functions
@@ -10,7 +10,7 @@ function get_package
 function set_package
 {
-    sed -i 's/^package = .*/package = "'$1'"/g' neo4j/meta.py
+    sed -i -e 's/^package = .*/package = "'$1'"/g' neo4j/meta.py
 }
 function get_version
@@ -20,7 +20,7 @@ function get_version
 function set_version
 {
-    sed -i 's/^version = .*/version = "'$1'"/g' neo4j/meta.py
+    sed -i -e 's/^version = .*/version = "'$1'"/g' neo4j/meta.py
 }
 function check_file
@@ -48,7 +48,7 @@ function set_metadata_and_setup
     ORIGINAL_VERSION=$(get_version)
     echo "Source code originally configured for package ${ORIGINAL_PACKAGE}/${ORIGINAL_VERSION}"
     echo "----------------------------------------"
-    tail -2 neo4j/meta.py
+    head -n 24 neo4j/meta.py | tail -2
     echo "----------------------------------------"
     # Temporarily override package metadata
@@ -56,7 +56,7 @@ function set_metadata_and_setup
     set_version "${VERSION}"
     echo "Source code reconfigured for package ${PACKAGE}/${VERSION}"
     echo "----------------------------------------"
-    tail -2 neo4j/meta.py
+    head -n 24 neo4j/meta.py | tail -2
     echo "----------------------------------------"
     # Create source distribution
@@ -70,7 +70,7 @@ function set_metadata_and_setup
     set_version "${ORIGINAL_VERSION}"
     echo "Source code reconfigured back to original package ${ORIGINAL_PACKAGE}/${ORIGINAL_VERSION}"
     echo "----------------------------------------"
-    tail -2 neo4j/meta.py
+    head -n 24 neo4j/meta.py | tail -2
     echo "----------------------------------------"
 }
```

**Comment by naughtyGitCat** [comment]
> I managed to create a distribution bij changing the `bin/dist-functions` a bit.
> 
> ```
> diff --git a/bin/dist-functions b/bin/dist-functions
> index d83c296..dc4f26f 100644
> --- a/bin/dist-functions
> +++ b/bin/dist-functions
> @@ -10,7 +10,7 @@ function get_package
>  function set_package
>  {
> -    sed -i 's/^package = .*/package = "'$1'"/g' neo4j/meta.py
> +    sed -i -e 's/^package = .*/package = "'$1'"/g' neo4j/meta.py
>  }
>  function get_version
> @@ -20,7 +20,7 @@ function get_version
>  function set_version
>  {
> -    sed -i 's/^version = .*/version = "'$1'"/g' neo4j/meta.py
> +    sed -i -e 's/^version = .*/version = "'$1'"/g' neo4j/meta.py
>  }
>  function check_file
> @@ -48,7 +48,7 @@ function set_metadata_and_setup
>      ORIGINAL_VERSION=$(get_version)
>      echo "Source code originally configured for package ${ORIGINAL_PACKAGE}/${ORIGINAL_VERSION}"
>      echo "----------------------------------------"
> -    tail -2 neo4j/meta.py
> +    head -n 24 neo4j/meta.py | tail -2
>      echo "----------------------------------------"
>      # Temporarily override package metadata
> @@ -56,7 +56,7 @@ function set_metadata_and_setup
>      set_version "${VERSION}"
>      echo "Source code reconfigured for package ${PACKAGE}/${VERSION}"
>      echo "----------------------------------------"
> -    tail -2 neo4j/meta.py
> +    head -n 24 neo4j/meta.py | tail -2
>      echo "----------------------------------------"
>      # Create source distribution
> @@ -70,7 +70,7 @@ function set_metadata_and_setup
>      set_version "${ORIGINAL_VERSION}"
>      echo "Source code reconfigured back to original package ${ORIGINAL_PACKAGE}/${ORIGINAL_VERSION}"
>      echo "----------------------------------------"
> -    tail -2 neo4j/meta.py
> +    head -n 24 neo4j/meta.py | tail -2
>      echo "----------------------------------------"
>  }
> ```

```bash
~/Github/neo4j-python-driver on  4.0! ⌚ 21:17:22
$ ./bin/make-dist 4.0
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "neo4j/__init__.py", line 56
    def driver(cls, uri, *, auth=None, acquire_timeout=None, **config):
                          ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "neo4j/__init__.py", line 56
    def driver(cls, uri, *, auth=None, acquire_timeout=None, **config):
                          ^
SyntaxError: invalid syntax
Source code originally configured for package /
----------------------------------------
package = "neo4j"
version = "4.0.dev0"
----------------------------------------
Source code reconfigured for package neo4j-driver/4.0
----------------------------------------
package = "neo4j-driver"
version = "4.0"
----------------------------------------
Traceback (most recent call last):
  File "setup.py", line 25, in <module>
    from neo4j.meta import package, version
  File "/Users/psyduck/Github/neo4j-python-driver/neo4j/__init__.py", line 56
    def driver(cls, uri, *, auth=None, acquire_timeout=None, **config):
                          ^
SyntaxError: invalid syntax
Checking file neo4j-driver-4.0.tar.gz... missing
Source code reconfigured back to original package /
----------------------------------------
package = ""
version = ""
----------------------------------------
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "neo4j/__init__.py", line 56
    def driver(cls, uri, *, auth=None, acquire_timeout=None, **config):
                          ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "neo4j/__init__.py", line 56
    def driver(cls, uri, *, auth=None, acquire_timeout=None, **config):
                          ^
SyntaxError: invalid syntax
Source code originally configured for package /
----------------------------------------
package = ""
version = ""
----------------------------------------
Source code reconfigured for package neo4j/4.0
----------------------------------------
package = "neo4j"
version = "4.0"
----------------------------------------
Traceback (most recent call last):
  File "setup.py", line 25, in <module>
    from neo4j.meta import package, version
  File "/Users/psyduck/Github/neo4j-python-driver/neo4j/__init__.py", line 56
    def driver(cls, uri, *, auth=None, acquire_timeout=None, **config):
                          ^
SyntaxError: invalid syntax
Checking file neo4j-4.0.tar.gz... missing
Source code reconfigured back to original package /
----------------------------------------
package = ""
version = ""
----------------------------------------
```

**Comment by krisgeus** [comment]
Which python version are you using. Python2 is not supported anymore, so you need to have python3

**Comment by krisgeus** [comment]
PR #336 Available

**Comment by technige** [comment]
Please don't use the 4.0 branch for anything other than casual reading. This is still very much an early work in progress and there is not yet a 4.0 release available.

Similarly, the release scripts are designed for 1.7 and have not yet been updated for 4.0. These are also generally for our internal use during the release process.

To use the Python driver with Neo4j, you can use the 1.7 driver in fallback mode. Note that encryption defaults have changed though, so while the 1.7 driver turns on encryption by default, this is no longer available by default in Neo4j 4.0. You will therefore have to connect with `encrypted=False`, which will (I believe) address the problem in the original post.

**Comment by naughtyGitCat** [comment]
Connect with  `encrypted=False`

means 

send user/pass unencrypted

or 

the server should disable the authenticate?

**Comment by naughtyGitCat** [comment]
> Please don't use the 4.0 branch for anything other than casual reading. This is still very much an early work in progress and there is not yet a 4.0 release available.
> 
> Similarly, the release scripts are designed for 1.7 and have not yet been updated for 4.0. These are also generally for our internal use during the release process.
> 
> To use the Python driver with Neo4j, you can use the 1.7 driver in fallback mode. Note that encryption defaults have changed though, so while the 1.7 driver turns on encryption by default, this is no longer available by default in Neo4j 4.0. You will therefore have to connect with `encrypted=False`, which will (I believe) address the problem in the original post.

Thanks, I use back 1.7 version driver And find that the 4.0 version driver at least slow than 1.7 version 10%.  

Test with 
```
1.7 driver => 4.0 server
1.7 driver => 3.5.12 server,
4.0 driver => 4.0 server,
4.0 driver => 3.5.12 server  
```

**Comment by hiiwave** [comment]
Hi, appreciated if you can answer:

1. Is there an ETA for driver 4.0 release?
2. Are we recommended to migrate to neo4j 4.0 from 3.x using driver 1.7?

Thanks.

**Comment by ninjakx** [comment]
@technige Using `encrypted = False` will give `AttributeError: 'NoneType' object has no attribute 'pool'`
