### ISSUE TITLE
[Feature Request] set and change database in python code

### ISSUE THREAD

**Issue by DachuanZhao** [neo4j/neo4j-python-driver#356]
- Neo4j version: Community4.0.0
- Neo4j Mode: Single instance
- Driver version: python 1.7.6
- Operating system: Ubuntu 18.04

How to set and change database in driver object ?
```
from neo4j import GraphDatabase

uri = "bolt://localhost:7687"
driver = GraphDatabase.driver(uri, auth=("neo4j", "password"), database="db_name")
```
Is there a ```database``` parameter in ```GraphDatabase.driver``` ?

**Comment by technige** [comment]
@DachuanZhao The 4.0 Python driver is currently in development, as mentioned on https://neo4j.com/docs/driver-manual/current/get-started/. This will expose support for multi-database, and will be selectable per session.

**Comment by technige** [comment]
Note though that Neo4j Community does not support multiple databases.
