### ISSUE TITLE
asyncio support update

### ISSUE THREAD

**Issue by dconathan** [neo4j/neo4j-python-driver#361]
Can we get an update on the plan/roadmap for asyncio support?  I see a bunch of asyncio code has been removed in a [recent commit](https://github.com/neo4j/neo4j-python-driver/commit/c15eef67d36d7bd4ad3bce60794c6e93afd98aab).

Has it been removed from the roadmap?

Thanks

**Comment by martin-neotech** [comment]
Hi @dconathan 

The asyncio is a work in progress. The asyncio code have been moved into https://github.com/neo4j/neo4j-python-driver/tree/4.0-asyncio for now.

There will first be releases to support `Neo4j 4.0` and after that there is on the roadmap to release support for python `asyncio`.

Cheers, Martin
