### ISSUE TITLE
BrokenPipeError - max_connection_lifetime using processor time in Python 2

### ISSUE THREAD

**Issue by cadryden** [neo4j/neo4j-python-driver#373]
Using Google AppEngine I've been getting repeatable `BrokenPipeError`s after leaving a server instance alone for a while (~1 hour).  When the server instance is first spun up a new neo4j driver instance is created and running a query works as expected, then after being left idle any query raises a `BrokenPipeError`.

**Driver version**: Python driver 1.7.6
**Operating System:** Google AppEngine Python 2, also MacOS

### Expected behavior
After setting `max_connection_lifetime` very low (5 seconds), connections should not be reused after long periods of time, causing `BrokenPipeError`s.

### Investigation
Based on the suggestions and explanations in https://github.com/neo4j/neo4j-python-driver/issues/131 and https://github.com/neo4j/neo4j-python-driver/issues/316 I've tried adjusting `max_connection_lifetime`, but the problem persists even setting it down to 5 seconds (Google AppEngine docs say sockets can be reclaimed after 2 minutes, so I'd expect 5 seconds to very safely under that).

Looking through the code to see how `max_connection_lifetime` is used, I see that it's used by [`neobolt.direct.Connection.timedout()`](https://github.com/neo4j-drivers/neobolt/blob/1.7/neobolt/direct.py#L515), and it's using `perf_counter()` to determine how long the `Connection` object has existed.

`perf_counter()` is defined twice by `neobolt.compat` for Python 2 though.  First as [`time.time()`](https://github.com/neo4j-drivers/neobolt/blob/1.7/neobolt/compat/__init__.py#L116) then again as [`time.clock()`](https://github.com/neo4j-drivers/neobolt/blob/1.7/neobolt/compat/__init__.py#L134), but `time.clock()` does not necessarily include sleep or idle time, which would be necessary for tracking how long a `Connection` has been alive.

In my case, after leaving a `Connection` idle for an hour `Connection.timedout()` thinks it's been a live for only a fraction of a second, but if it had been using `time.time()` instead of `time.clock()` it'd correctly know the `Connection` is too old to be reused.

**Comment by martin-neotech** [comment]
@cadryden Hi, sorry for a late reply. This https://github.com/neo4j-drivers/neobolt/commit/9fadc295a00502e980af99223344838c31bb1857 should solve this issue.

Cheers Martin

**Comment by cadryden** [comment]
Thanks @martin-neotech !

**Comment by martin-neotech** [comment]
@cadryden a new version of neobolt have been released also today with this fix.
