### ISSUE TITLE
Nginx - Neoj4 4.0 bolt looks like HTTP

### ISSUE THREAD

**Issue by peterpribeli** [neo4j/neo4j-python-driver#380]
Hi,

I've got an nginx server that terminates SSL (let's encrypt certificate) and redirects neo4j.domain.com and bolt.domain.com:7687 to the neo4j DB.  This is the only configuration in which the neo4j browser actually works. 
But the python driver throws an exception
> neo4j.exceptions.ServiceUnavailable: Cannot to connect to Bolt service on IPv4Address(('bolt.domain.com', 7687)) (looks like HTTP)

This is because it receives a bad request (400) response which begins with 'HTTP1.1...'
The bad request from nginx logs:

> "``\xB0\x17\x00\x00\x00\x03\x00\x00\x00\x02\x00\x00\x00\x01\x00\x00\x00\x00"

Now if I transfer the SSL termination of the bolt protocol to the neo4j DB and bypass nginx (which I would not like to do) the python driver works but the browser does not.

A very similar scenario plays out if I try self-signed certificates on the local network.

I realize that this might be slightly unrelated but there's [very little](https://github.com/neo4j/neo4j-browser/issues/788) available resources on this.
How can I connect to bolt that is behind an nginx reverse proxy ? 

Thank you!

**Neo4j Version:** 4.0.2 Community  
**Neo4j Mode**: Single instance  
**Driver version**: Python driver 1.7.1  and 4.0.0.a1
**Operating System:** macOS Catalina client, debian server
**Nginx config:**

>http{ 
upstream neo4j {
  server 192.168.0.2:7474;
}
upstream bolt {
  server 192.168.0.2:7687;
}
server {
    listen       443 ssl;
    server_name  neo4j.domain.com;
    ssl_certificate /etc/nginx/certificates/https/public.crt;
    ssl_certificate_key /etc/nginx/certificates/https/private.key;
    location / {
        proxy_pass http://neo4j;
    }
}
server {
    listen       7687 ssl;
    server_name  bolt.domain.com;
    ssl_certificate /etc/nginx/certificates/bolt/public.crt;
    ssl_certificate_key /etc/nginx/certificates/bolt/private.key;
    location / {
        proxy_pass http://bolt;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
### Steps to reproduce
1. Start Neo4j with neo4j(7474) and bolt(7687) both unencrypted
2. Start an nginx reverse proxy: neo4.domain.com -> neo4j(7474),  bolt.domain.com:7687 -> neo4j(7687)
3. Try to connect from GraphDatabase.driver() to bolt://bolt.domain.com:7687
### Expected behavior
Both neo4j and bolt should have SSL and be reverse proxied by nginx and both the web browser and python connections should work.
### Actual behavior
With nginx the browser works but python does not and without nginx vice versa.

**Comment by martin-neotech** [comment]
Hi @peterpribeli,

please add the nginx config

**Comment by zhenlineo** [comment]
Hi @peterpribeli,
The python driver runs bolt on TCP socket. The browser might run bolt on websocket. You would need to config your NGINX to be able to redirect both TCP and websocket for bolt port to let python driver and browser works as expected.

**Comment by peterpribeli** [comment]
Hi thanks a lot for the replies! 
@martin-neotech I edited the post.
@zhenlineo Thank you. I'll try the [nginx tcp stream](https://nginx.org/en/docs/stream/ngx_stream_core_module.html) then.

**Comment by peterpribeli** [comment]
I've found a somewhat workable solution. I posted the configs and some explanation [here](https://github.com/neo4j/neo4j-browser/issues/788#issuecomment-604142636). 
Thank you!
Should I close the issue?

**Comment by martin-neotech** [comment]
@peterpribeli thanks for sharing the solution.
