### ISSUE TITLE
Config Attribute "database" does not have an effect.

### ISSUE THREAD

**Issue by Buchhold** [neo4j/neo4j-python-driver#383]
## Env
python 3.8
neo4j-driver              4.0.0a2
Neo4j Server version: 4.0.2 (enterprise)  -- using the 30 day trial, atm

I have create several "databases" through the browser and can successfully switch in the Neo Browser via `:use`. Both, `CREATE`  and `MATCH` statements work as I'd expect.
However, I cannot switch through the driver.

## Steps to reproduce
```
driver = neo4j.GraphDatabase.driver( "bolt://host:7687", auth=(usr, pw), encrypted=False)
s1 = driver.session()
s2 = driver.session(database='mytest')
```
s1._config:
```
<SessionConfig consume_chain=<function Config.consume_chain at 0x7fa86682f670> consume=<bound method Config.consume of <class 'neo4j.conf.WorkspaceConfig'>> connection_acquisition_timeout=60.0 max_retry_time=30.0 initial_retry_delay=1.0 retry_delay_multiplier=2.0 retry_delay_jitter_factor=0.2 database=None fetch_size=1000 bookmarks=() default_access_mode='WRITE'>
```

s2._config:
```
<SessionConfig consume_chain=<function Config.consume_chain at 0x7fa86682f670> consume=<bound method Config.consume of <class 'neo4j.conf.WorkspaceConfig'>> connection_acquisition_timeout=60.0 max_retry_time=30.0 initial_retry_delay=1.0 retry_delay_multiplier=2.0 retry_delay_jitter_factor=0.2 database='mytest' fetch_size=1000 bookmarks=() default_access_mode='WRITE'>
```

```
r = s2.run("match () return count(*)")
print(r.data())
```

## Expected behavior
print the number of nodes in `mytest`

## Actual behavior
prints the number of nodes in the default database

`CREATE` statements made with the session object target the default DB, too.

**Comment by martin-neotech** [comment]
@Buchhold you are correct, multidatabase support is not implemented yet, I'm working on it right now. It is estimated to be an alpha release 4.0.0a3 that includes the multidatabase support next week. Please be patient and dont hesitate to give feedback.

Cheers Martin

**Comment by technige** [comment]
@Buchhold The third alpha was released last week, so you should now be able to trial the multidb functionality.

**Comment by martin-neotech** [comment]
This is available in the alpha release now.

`driver.session(database="my_other_database")`
