### ISSUE TITLE
SSL handshake error

### ISSUE THREAD

**Issue by joostboon** [neo4j/neo4j-python-driver#391]
- Neo4j version: Community 4.0.4
- Neo4j Mode: Single instance
- Driver version: Python neo4j v.1.7.6
- Operating system: MacOS Catelina (10.15.4)

**Steps to reproduce**
- Expected behavior

Following the guidelines trying to set up a connection from a python script to my neo4j instance running on localhost:

1. Running neo4j - no issues. 

2. Trying to connect with python:
`pip install neo4j`

```
from neo4j import GraphDatabase

driver = GraphDatabase.driver("bolt://localhost:7687", auth=("neo4j", "password"))
```
- Actual behavior

Trying this resolves in a ssl handshake error (see output.txt). I've tried multiple versions of openssl that are still compatible with neo4j but all with the same error result. Also tried downgrading to python3.7, didn't work either. 

Please see output.txt and env.txt for the set up. This was all run inside a miniconda env.

[env.txt](https://github.com/neo4j/neo4j-python-driver/files/4649772/env.txt)
[output.txt](https://github.com/neo4j/neo4j-python-driver/files/4649773/output.txt)
[neo4j.conf.txt](https://github.com/neo4j/neo4j-python-driver/files/4649802/neo4j.conf.txt) (sorry had to convert to .txt to be able to upload here)

Please let me know if you need any additional info! Hope you can help!

**Comment by KevinvOosterhout** [comment]
See issue #368. This is due to Neo4j V4 not having a certificate. So set encrypted to false or generate a certificate and put it in the neo4j.conf
