### ISSUE TITLE
[Feature Request] Are there any plans to add support to datadog ddtrace

### ISSUE THREAD

**Issue by aonamrata** [neo4j/neo4j-python-driver#396]
- Neo4j version: Enterprise X.Y.Z
- Driver version: neo4j==1.7.6
- Operating system: centos7 on AWS

Hi,
We are using neo4j driver with flask and datadog for reporting. Datadog APM gives a nice breakdown of services
![image](https://user-images.githubusercontent.com/1792005/82994631-1a5e3280-a020-11ea-89be-3335a8b153f4.png)

It does not have neo4j support http://pypi.datadoghq.com/trace/docs/#supported-libraries . Are there any plans to add that support?

Thanks.

**Comment by martin-neotech** [comment]
Hi @aonamrata

Thanks for your feature request, at the moment we are not planning on adding the support for Datadog APM. Our main focus now is the Python Driver 4.0 version. We will consider the feature request for future work.

Cheers Martin
