### ISSUE TITLE
Neo4j Api not clear in case of how to consume result object, need more examples, and update required to existing examples.

### ISSUE THREAD

**Issue by gaurav1999** [neo4j/neo4j-python-driver#402]
```
from neo4j import GraphDatabase

uri = "bolt://localhost:7687"
driver = GraphDatabase.driver(uri, auth=("neo4j", "password"))

def print_friends_of(tx, name):
    for record in tx.run("MATCH (a:Person)-[:KNOWS]->(f) "
                         "WHERE a.name = {name} "
                         "RETURN f.name", name=name):
        print(record["f.name"])

with driver.session() as session:
    session.read_transaction(print_friends_of, "Alice")

driver.close()
```
In the given example at date June -02-2020 on https://neo4j.com/docs/api/python-driver/current/index.html 

The example is outdated, now driver expects "$name" instead of "{name}".

Also, I would like to ask an example, which explains how to parse a complete Neo4j Record object.
In case if we returned the node "f" then how to access it's label, it's node id and it's properties through python ```print(record["f.name"])``` like in this example.

Thanks.

**Comment by martin-neotech** [comment]
Hi @gaurav1999, thanks for the feedback.

That version of the API Documentation was just an early version. With the release of 4.0.0b2 there is some improvements on the API Documentation and I will try to add some more examples of how to consume the Result object and how to extract data from the Record objects.

please have a look at the updated documentation:

https://neo4j.com/docs/api/python-driver/4.0/api.html#result

https://neo4j.com/docs/api/python-driver/4.0/api.html#record


Cheers, Martin

**Comment by gaurav1999** [comment]
Hi Martin,
Thanks for the response. I will take a look.
Not sure if this is in your area, I would like to ask that if possible can Neo4j team add good examples on the Go Driver as well, in their github they don't even have the link to driver's api docs on their Readme.md it's quite hard to understand without docs and examples around. 

Regards,Gaurav

**Comment by martin-neotech** [comment]
Depending on how you write the cypher query, the Record objects will contain a set of keys.

Example 1:

```
from neo4j import GraphDatabase

uri = "bolt://localhost:7687"
driver = GraphDatabase.driver(uri, auth=("neo4j", "password"))

def print_friends_of(tx, name):
    for record in tx.run("MATCH (a:Person)-[:KNOWS]->(f) "
                         "WHERE a.name = $name"
                         "RETURN f.name", name=name):
        print(record["f.name"])

with driver.session() as session:
    session.read_transaction(print_friends_of, "Alice")

driver.close()
```

Example 2:
```
from neo4j import GraphDatabase

uri = "bolt://localhost:7687"
driver = GraphDatabase.driver(uri, auth=("neo4j", "password"))

def print_friends_of(tx, name):
    for record in tx.run("MATCH (a:Person)-[:KNOWS]->(f) "
                         "WHERE a.name = $name"
                         "RETURN f.name AS x", name=name):
        print(record["x"])

with driver.session() as session:
    session.read_transaction(print_friends_of, "Alice")

driver.close()
```

Example 3:
```
from neo4j import GraphDatabase

uri = "bolt://localhost:7687"
driver = GraphDatabase.driver(uri, auth=("neo4j", "password"))

def print_friends_of(tx, name):
    result = tx.run("MATCH (a:Person)-[:KNOWS]->(f) "
                         "WHERE a.name = $name"
                         "RETURN f.name AS x", name=name):
    
    for record in result:
        print(record.keys())
    
     return 1

with driver.session() as session:
    value = session.read_transaction(print_friends_of, "Alice")

driver.close()
```

**Comment by martin-neotech** [comment]
> Hi Martin,
> Thanks for the response. I will take a look.
> Not sure if this is in your area, I would like to ask that if possible can Neo4j team add good examples on the Go Driver as well, in their github they don't even have the link to driver's api docs on their Readme.md it's quite hard to understand without docs and examples around.
> 
> Regards,Gaurav

@gaurav1999 The Go Driver is being updated right now and there will soon be a pure Go Driver 1.8 released, please add an issue on the https://github.com/neo4j/neo4j-go-driver if there is the need for more examples.
