### ISSUE TITLE
Transaction.sync removed from code but not documented.

### ISSUE THREAD

**Issue by subssn21** [neo4j/neo4j-python-driver#406]
- Neo4j version: Aura
- Driver version: 4.0.0b2
- Operating system: MacOSx Catalina / AWS Ubuntu 18.04
- When upgrading code from 1.7.6 driver to 4.0.0b2 driver calls to Transaction.sync fail with AttributeError, looking at the code there is no longer a sync.method. This is not documented in breaking changes and is still referenced in the API Documentation.
- Expected behavior
.sync() calls and runs any pending tx.run() <Perhaps not necessary anymore, if so not propely documented>
- Actual behavior
AttributeError

**Comment by martin-neotech** [comment]
@subssn21 Thanks for the feedback, yes it was missing to be documented that Transaction.sync() was removed. New API documentation will fix this https://github.com/neo4j/neo4j-python-driver/pull/409
