### ISSUE TITLE
Result.data() Attribute Error

### ISSUE THREAD

**Issue by subssn21** [neo4j/neo4j-python-driver#407]
Neo4j version: Aura
Driver version: 4.0.0b2
Operating system: MacOSx Catalina / AWS Ubuntu 18.04
When upgrading code from 1.7.6 driver to 4.0.0b2 driver calls to reults.data() fails with AttributeError, looking at the code there is no longer a Result.data() method. This is not documented in breaking changes. It is not in the documentation anymore, so it's probably just not documented as a breaking change.
.data() calls and returns the results (as if you had done [rec for rec in results] list comprehensions on the result object)
Actual behavior
AttributeError

**Comment by martin-neotech** [comment]
@subssn21 the PR https://github.com/neo4j/neo4j-python-driver/pull/410 document this.

Use

```
data = []

for record in result:
    data.append(record.data())
```

or

`data = [record.data() for record in result]`

**Comment by martin-neotech** [comment]
@subssn21 The helper function `Result.data(*keys)` have been introduced back with the 4.0.1 release. Note that the argument have changed from `*items` to `*keys` for alignment of the `Record.data(*keys)` function.
