### ISSUE TITLE
labels missing Nodes

### ISSUE THREAD

**Issue by subssn21** [neo4j/neo4j-python-driver#408]
- Neo4j version: Aura
- Driver version: 4.0.0b2
- Operating system: Mac OSX Catalina / AWS Ubuntu 18.04
- 
When executing A query and calling `Result.graph` not all nodes will have their labels in the `Node.labels` set. This worked fine with the 1.7.6 driver on Neo4j 4.0 using the desktop app, The 1.7.6 driver does not work right with Aura.
- Expected behavior

When calling `Result.graph`, the nodes that are returned should all have their labels in the labels set of each of their nodes. 

- Actual behavior

For some reason only some of the Nodes have their labels in the set

I don't have a simple set of reproduction steps, it happens calling many different queries.

This Query:

```
MATCH (f:File{uid: $uid})
        OPTIONAL MATCH (f)-[rel]->(n) 
        RETURN f, rel, n
```

returns the label for f in the results, but not for the nodes in n, This used to work in the 1.7.6 driver.

**Comment by martin-neotech** [comment]
@subssn21 thanks for finding this bug, the PR https://github.com/neo4j/neo4j-python-driver/pull/411 will solve this issue.

**Comment by subssn21** [comment]
I have tested the PR against my code and it fixes the problem.

**Comment by martin-neotech** [comment]
PR merged.
