### ISSUE TITLE
Tolerant depreciation of neo4j.result.value() and .values() in version 1.7.1 not in accordance with Azure Functions

### ISSUE THREAD

**Issue by Alsaxian** [neo4j/neo4j-python-driver#434]
In reading your [Python 4.0 driver ducumentation](https://neo4j.com/docs/api/python-driver/4.0/api.html#neo4j.Result) one can realize that you are depreciating `neo4j.result.value()` and `.values()` from now on, which were however two of the main ways to consume Neo4j results before, which is OK in theory, because it's only an issue of adding a for-loop to your code, but imagine when in your old projects `value()` and `values()` are everywhere..

Keeping the old version 1.7 of the Python driver combining with Neo4j 4.0 should have been a good workaround to avoid making these changes here and there. However, this seems not to be true in Azure Functions.

Environment: Python: 3.8.3, neo4j-python-driver: 1.7.1, neobolt: 1.7.17, OS: Windows 10, IDE: VS Code.
In my local debugging the result consumption with `result.value()` and `result.values()` worked just great.
Now when I tried to deploy everything onto Azure Functions, nightmare comes. With exactly the same environment with Azure Function 3.0.2630, even when I just run everything in local, Errors prompt out.
No matter if I only include neo4j or neobolt as well in requirements.txt, debugger says
```
Exception: AttributeError: 'Result' object has no attribute 'value'
```
Then if I change `value()` to a self-made iter-to-list piece of code, everything works. 

It seems to me that on one side, Azure Functions installs and manages Python packages on its own so that for example you can't really define the exact version you need for the packages you use. On the other, you guys did some not 100% worry-free tricks in the back so that "higher" versions of neo4j-python-driver in 1.7 could still run the methods `values()` and `values()` on a result, though both being already depreciated with tolerance in these 1.7 versions, with the thought to drop them out definitely in the future versions of 4.0. But the tricks somehow don't get along with Azure Functions. 

Given that changing and testing every place where these methods come up in the old code would be extremely cumbersome, look forward to some meaningful solution or advice from the team. Thank you.

**Comment by Alsaxian** [comment]
My bad, adding `neo4j==1.7.1` to requirements.txt did the work.

The problem is Azure Functions never wrote a clear documentation or a quick start example on how you can define versions in requirements.txt and somehow, you have the feeling that when running locally, it is actually supposed, but doesn't really use the packages you installed for it in the Python environment you point it to, instead it'll download and run packages on its own. Though you are not sure, you have to guess. And yes without pointing out the version it has probably used the neo4j python driver 4.0 even when I've never downloaded it. 

Philosophically this is strange though for Azure Functions, if you don't want to use my environment I gave you and download everything you need by yourself, then why do you ask me to point out a Python interpreter, find it on your own on the internet too...

And somehow, you are nearly sure that Azure Functions should use local packages rather than look for something online because you designated neo4j to it in an import-like way in requirements.txt and not using the whole name neo4j-python-driver of the package, so how has it been able to find neo4j-python-driver online using the shortcut. But you are wrong. So many things unpredictable when lack of documentation.

**Comment by martin-neotech** [comment]
@Alsaxian thanks for your feedback. Please reach out if there is any other issues on your mind.

**Comment by martin-neotech** [comment]
@Alsaxian With release of 4.0.1 the helper functions:

```
.value(key=0, default=None)
.values(*keys)
.data(*keys)
```

for a Result object was re-introduced. Bare in mind that the key parameter have changed named from `item` to `key` and `items` to `keys` for alignment of the Record functions.
