### ISSUE TITLE
Different behaviours in the 4.0 driver when returning a result iterator before consuming it 

### ISSUE THREAD

**Issue by Alsaxian** [neo4j/neo4j-python-driver#449]
Hey,

I have always thought that I should rather carry the iterator with me when I pass a result from one function to another wherever it is possible, and only consume it (convert it to a list or a dict) at the last step where I really need to, since iterators are much less cumbersome than lists or dicts in Python, which goes in line with Python's best practice. This idea has been working well with the 1.7.1 driver but I just ran into a problem with the 4.0 driver. Let's consider the following code

```python
from neo4j import GraphDatabase
driver = GraphDatabase.driver("bolt://localhost:7687", auth=("neo4j", "my_password"), encrypted = False)

def gimme_some_names(tx):
    names = tx.run("MATCH (pl:Person) RETURN pl.name AS names")

with driver.session() as session1:
    result_non_transactional = session1.run("MATCH (pl:Person) RETURN pl.name AS names")
    result_transactional = session1.read_transaction(gimme_some_names)

driver.close()

print("Result when I don't use transactions:", result_non_transactional.values())
print("Result when I use transactions:", result_transactional.values())
```

The idea is that I let Neo4j run as little time as possible, I try not to treat any result during an open Neo4j session so that Neo4j should only concentrate on its queries. I use transactions once and not, the other time. However:

With Python 3.8.3 + Neo4j 4.0 + neo4j-python-driver 1.7.1, both works well. 
With Python 3.8.3 + Neo4j 4.0 + neo4j-python-driver 4.0, the non-transactional one works well but the transactional one doesn't work, which only returns an empty list. But if I directly convert the result to a list or a dict inside the Neo4j session, both works well again. 

Is this what supposed to be with the 4.0 driver? If yes, any explanation why the 4.0 driver doesn't encourage users to transport result iterators anymore instead of lists when they use transactions, but still keep the possibility when they don't? 

Thank you.

**Comment by martin-neotech** [comment]
@Alsaxian Hi, a transaction function should be isolated. Consume the result in the transaction function and then return.


```
from neo4j import GraphDatabase
driver = GraphDatabase.driver("bolt://localhost:7687", auth=("neo4j", "my_password"), encrypted = False)

def gimme_some_names(tx):
    # Always consume the Result object in a transaction function.
    # This is because the transaction function will do a commit or a reset.
    # The 4.0 introduced fetch_size of records to get records in batches, if there is unconsumed records they will not be fetched.
    result = tx.run("MATCH (pl:Person) RETURN pl.name AS name")  # The result is an iterator object
    return [record["name"] for record in result]

with driver.session() as session:
    result = session.run("MATCH (pl:Person) RETURN pl.name AS name")
    names = [record["name"] for record in result]

with driver.session() as session:
    names = session.read_transaction(gimme_some_names)

driver.close()
```

**transaction**

A transaction comprises a unit of work performed against a database. It is treated in a coherent and reliable way, independent of other transactions. A transaction, by definition, **must be atomic, consistent, isolated, and durable**.

**transaction function**

The method of grouping a number of queries together which, when run in a session, are retried on failure.

**transaction manager**

The component/code responsible for deciding what to do if a transaction fails, i.e to retry, give up or do something else.

Transaction Functions:

https://neo4j.com/docs/driver-manual/4.0/session-api/simple/#driver-simple-transaction-fn
