### ISSUE TITLE
SSL import issue in Python 2.7 earlier than 2.7.9

### ISSUE THREAD

**Issue by technige** [neo4j/neo4j-python-driver#46]
For details, see https://github.com/nigelsmall/py2neo/issues/487

**Comment by technige** [comment]
Likely fix is to handle `ImportError` gracefully and disable SSL support in 2.7 if below 2.7.9.

**Comment by Alan-R** [comment]
I can live with this. Is this where I should have opened the issue?

**Comment by technige** [comment]
No, that's fine. You use py2neo and used the library indirectly from there so you raised it in the right place.

**Comment by technige** [comment]
This was addressed in 92e47d416481a9ef2165d547c01cdf3496ac99e1
