### ISSUE TITLE
how to query path

### ISSUE THREAD

**Issue by drunkenlion** [neo4j/neo4j-python-driver#462]
when I run

```
match p=(n:card{card_id:27})-[r*..3]->(m:card{card_id:106}) where n.card_id<>m.card_id return p limit 5
```

I can't get path object ,

API Doc says:
Cypher Type | Python Type
-- | --
Node | neo4j.graph.Node
Relationship | neo4j.graph.Relationship
Path | neo4j.graph.Path

but I can't .

how does it work???

**Comment by martin-neotech** [comment]
@drunkenlion please provide the

Neo4j version:
Python Driver version:

and what does your result contain ?

**Comment by martin-neotech** [comment]
This test show you how a Path object is returned

https://github.com/neo4j/neo4j-python-driver/blob/4.1/tests/integration/test_graph_types.py#L47
