### ISSUE TITLE
Have a way to retrieve the original error on defunct connection ?

### ISSUE THREAD

**Issue by prevostc** [neo4j/neo4j-python-driver#463]
# Suggestion

I noticed the _set_defunct method of the bolt protocol files completely hides the underlying error message: 

 - https://github.com/neo4j/neo4j-python-driver/blob/2d55eae5a95c3fcbe6080b7ac7e444d971ad50e0/neo4j/io/_bolt4x0.py#L367

In my case I get a OSError from IncomingMessage:

- Method passed here: https://github.com/neo4j/neo4j-python-driver/blob/2d55eae5a95c3fcbe6080b7ac7e444d971ad50e0/neo4j/io/_bolt4x0.py#L85
- Error triggered here: https://github.com/neo4j/neo4j-python-driver/blob/2d55eae5a95c3fcbe6080b7ac7e444d971ad50e0/neo4j/io/_courier.py#L63

When I get this "Failed to read from defunct connection" error, I don't really know what to do and have absolutely no way to retrieve the original error for hints.

**Comment by martin-neotech** [comment]
@prevostc Thanks for the suggestion, I will have a look at this, to improve error propagation for this case.

**Comment by martin-neotech** [comment]
https://github.com/neo4j/neo4j-python-driver/pull/466

**Comment by martin-neotech** [comment]
@prevostc does the PR solve your issue with the error propagation info? I will do a patch release on Thursday where this is included.

**Comment by prevostc** [comment]
@martin-neotech thank you for your quick work and great communication. I'll try the branch with the fix and will let you know today.

**Comment by prevostc** [comment]
Sorry for the delay, I can confirm this fix for my particular issue

**Comment by martin-neotech** [comment]
great news, thanks for the feedback.

Cheers, Martin
