### ISSUE TITLE
intermittent connectivity issues w/ Sandbox

### ISSUE THREAD

**Issue by whatSocks** [neo4j/neo4j-python-driver#470]
## Guidelines

- Neo4j version: Sandbox Recommendations - 3.5.117, Enterprise
- Neo4j Mode:  Sandbox Recommendations
- Driver version: 4.0.0

- Operating system: Mac OS Catalina
- **Steps to reproduce**
- Expected behavior

* Connect to the Recommendations (movies, genres, actors etc) sandbox using the driver
* make about 5 queries for movies and movies by genre (loading a page with movies by genre)
* receive results

- Actual behavior

* Connect to the Recommendations (movies, genres, actors etc) sandbox using the driver
* make about 5 queries for movies and genres
* receive some results, other times receive 
```
neo4j.exceptions.ServiceUnavailable: Failed to read from defunct connection IPv4Address(('34.227.92.130', 34260)) (IPv4Address(('34.227.92.130', 34260)))
```

**Comment by martin-neotech** [comment]
@whatSocks Hi could you please add a code snippet.

It is normal in network applications that a connection could die and then you have to catch the error and do another query.

Please read this article. https://medium.com/neo4j/try-and-then-retry-there-can-be-failure-30bf336383da
