### ISSUE TITLE
Disable caching using the python driver.

### ISSUE THREAD

**Issue by Wathsara** [neo4j/neo4j-python-driver#471]
I am using the community version of Neo4j and I am trying to do a benchmark for the performance of the quries. Is there a way to disable the caching when executing the queries using the python driver without changing the configuration files?

**Comment by technige** [comment]
If you are talking about server-side query caching, then no. This behaviour is controlled entirely by the server.

**Comment by Wathsara** [comment]
Is there a way to disable caching?

**Comment by technige** [comment]
Not as far as I know. You'll need to check the Neo4j operations manual.

Alternatively, try adding some kind of random "salt" to your query, such as a variable name. If the text changes, it won't get cached and reused.

I'd also advise thinking about what you're actually trying to benchmark here. Disabling caching won't give you any realistic kind of measure.
