### ISSUE TITLE
Transaction in Neo4j

### ISSUE THREAD

**Issue by hasaiki123** [neo4j/neo4j-python-driver#473]
How can I roll back the transaction?

**Comment by fbiville** [comment]
Hi, if you explicitly define a transaction with `with session.begin_transaction() as tx`, then you can explicitly roll it back as well with a [`tx.rollback()`](session.begin_transaction()) call on the `Transaction` object.

**Comment by technige** [comment]
Also, if you are using a transaction function, you will need to raise an exception to automatically roll back the transaction.
