### ISSUE TITLE
Specifying *current_db* on a session call.

### ISSUE THREAD

**Issue by rtviii** [neo4j/neo4j-python-driver#481]
Hi, not sure where that went -- but since the 4.2.0 bump i cannot specify 
...driver.session(current_db="one_of_my_dbs_name") 
to choose one of the databases. Can we bring that back or am i missing something? Couldn't find in current docs on a cursory search.
 
Thank you!

**Comment by fbiville** [comment]
I'm not a Pythonista so I may be wrong, but I think [the setting](https://github.com/neo4j/neo4j-python-driver/blob/3c11e2bc4448231b1411bdc5d1a0d9f1e3f6e211/neo4j/conf.py#L295) is now just called `database`?

**Comment by rtviii** [comment]
Right on, good to know the source.
Thanks for the swift response.
