### ISSUE TITLE
Prevent Deprecation Warning to users 

### ISSUE THREAD

**Issue by pjljvandelaar** [neo4j/neo4j-python-driver#492]
## User get DeprecationWarnings

- Operating system: Windows 10

Run install and run [nox](https://nox.thea.codes/en/stable/) on attached archive
[example_python.zip](https://github.com/neo4j/neo4j-python-driver/files/5842343/example_python.zip)

- Expected behavior
pylint should analyze the code and report user erros

- Actual behavior
pylint reports issue in neo4j driver as well!

```
================================================= warnings summary =================================================
<unknown>:339
  <unknown>:339: DeprecationWarning: invalid escape sequence \*

<unknown>:381
  <unknown>:381: DeprecationWarning: invalid escape sequence \*

-- Docs: https://docs.pytest.org/en/stable/warnings.html
============================================= short test summary info ==============================================
FAILED example.py::PYLINT
```

**Comment by robsdedude** [comment]
I located the problematic lines in the driver code and I'll fix them for the next release. However, I find it quite strange behavior of pylint to check the dependencies' code. A quick search didn't yield a way to change pylint's behavior there. It also seemed that the warning would only show up the first time pylint is ran, not on consecutive runs, unless deleting `src/.pytest_cache`. Not sure if intended or a bug in pylint.
