### ISSUE TITLE
'The client is unauthorized due to authentication failure.

### ISSUE THREAD

**Issue by sitashmarajbhandari7879** [neo4j/neo4j-python-driver#495]
Hello while trying to use python to build a graph in neo4j i always get an authentication error.  
```
(CKG_ENV) C:\Users\sitas\CKG\src\graphdb_builder\builder>python builder.py -b minimal -u neo4j
```
error:
```python
  File "C:\Users\sitas\CKG\src\graphdb_connector\connector.py", line 45, in connectToDB
    raise Exception("Unexpected error:{}.\n{}".format(err, sys_error))
Exception: Unexpected error:{code: None} {message: None}.
(<class 'neo4j.exceptions.AuthError'>, AuthError('The client is unauthorized due to authentication failure.'), <traceback object at 0x000001EAB1FED680>), file: connector.py,line: 40
```

How can I solve this? I am new to neo4j

**Comment by fbiville** [comment]
Welcome! 
You need to specify a password in order to connect to Neo4j and I do not see any passed to `python builder.py`.

(Note: this kind of question is better suited for https://community.neo4j.com/. The repository issues are for reporting technical issues with the driver.)

**Comment by sitashmarajbhandari7879** [comment]
Thank you for response, can you please elaborate where the password must be added?

I will also be posting this problem in the site you have suggested.

I am very grateful for the suggestions

**Comment by fbiville** [comment]
You can find an example of how to use the Python in the [README](https://github.com/neo4j/neo4j-python-driver#quick-example), in particular see the `auth` parameter:

```python
driver = GraphDatabase.driver("neo4j://localhost:7687", auth=("neo4j", "password"))
```

It seems that your `builder.py` requires a Neo4j username (I assume that `-u neo4j` stands for the Neo4j username), but I don't see any flag for the password (like `-p password`).

**Comment by sitashmarajbhandari7879** [comment]
I understood well now. Thank you so much for clarifying my problem.
with regards
Sitashma Rajbhandari
