### ISSUE TITLE
Crash when using spatial type as parameters

### ISSUE THREAD

**Issue by stellasia** [neo4j/neo4j-python-driver#496]
Hi folks!

I can't seem to get the spatial type working, just getting a crash (stack trace attached).

- Neo4j version: Enterprise 4.2.1
- Neo4j Mode: Single instance
- Python 3.9
- Driver version:  driver 4.2.1
- Operating system: Ubuntu 20.04

- **Steps to reproduce**: run the following piece of code:

```
import neo4j
print(neo4j.__version__)

from neo4j.spatial import WGS84Point
from neo4j import GraphDatabase, basic_auth
driver = GraphDatabase.driver("bolt://localhost:7687", auth=basic_auth("neo4j", ""), encrypted=False)
point = WGS84Point(dict(x=2, y=48))
cypher = "WITH $point as point RETURN [point.x, point.y]"
params = {"point": point}
with driver.session() as session:
    session.run(cypher, params)
```

- Expected behavior : query returns [2, 48] (or a meaningful error message in case of misuse)
- Actual behavior: `neo4j.exceptions.ServiceUnavailable: Failed to read from defunct connection IPv4Address(('localhost', 7687)) (IPv4Address(('127.0.0.1', 7687)))`

Full stack trace is attached.
[neo_spatial.log](https://github.com/neo4j/neo4j-python-driver/files/5968103/neo_spatial.log)

Also, only error in server logs is:

```
2021-02-11 18:00:06.353+0000 ERROR Client triggered an unexpected error [Neo.DatabaseError.General.UnknownError]: Unknown statement ID: -1. Existing IDs: [], reference 1c40d17c-1c03-4b40-b422-ceeef7fc49ec.
```

- Additional information:
    -  Same error with CartesianPoint  
    - Doing similar things with DateTime works well (and basically, anything else is working just fine :) )
    - I havn't found an example using spatial types in the doc, but the example is taken from https://github.com/neo4j/neo4j-python-driver/blob/4.3/tests/integration/test_spatial_types.py (I think)
    - Replacing the query with a `MATCH (n:Node) RETURN n.point` returns a `neo4j.spatial.WGS84Point` as expected
    - Same error as https://github.com/neo4j/neo4j-python-driver/issues/484 but, not sure the root cause is the same though.

**Comment by robsdedude** [comment]
The constructor of `WGS84Point` takes a tuple or list of floats. Your example works if you replace 

    point = WGS84Point(dict(x=2, y=48))

with 

    point = WGS84Point((2.0, 48.0))

a type check on the driver side would make for a more helpful error message.

You can find more details in the driver's [API docs](https://neo4j.com/docs/api/python-driver/4.2/api.html?highlight=point#point).

**Comment by stellasia** [comment]
Arf, my bad, thanks for this!

Also, apparently, the elements in the tuple need to be floats, it fails with the same error if I use int (ok no one wants to use int for latitude and longitude... except me when testing :) ).

**Comment by technige** [comment]
@stellasia Not really your bad. The usage isn't obvious. We should probably coerce these into floats internally.
