### ISSUE TITLE
So no need for Py2neo anymore?

### ISSUE THREAD

**Issue by thmohds** [neo4j/neo4j-python-driver#56]
So no need for Py2neo to run cypher queries anymore?

**Comment by stevenpollack** [comment]
~~I'm not sure; it may seem that basic connectivity with this driver is buggy -- see my issue (#58)~~ (my issue is fixed with #59)... I'm now wondering the same thing as @thmohds...

**Comment by thmohd** [comment]
@stevenpollack I did get that issue and I solved it same way. I am getting another issue with caching but not sure if it is relevant to the Driver.

**Comment by mjmare** [comment]
I'd be interested in learning the plans for py2neo. Roadmap?

**Comment by technige** [comment]
This is not the right place to discuss py2neo but I'll answer briefly anyway. Both libraries will continue to exist side by side for the foreseeable future. The official driver is for Neo4j 3.0+ only and is both supported and presents a uniform API across all Neo drivers. Py2neo supports 2.0+, is not supported by Neo Tech and has a different (and larger) API. The choice of which to use will depend on your circumstances and use case.

**Comment by mjmare** [comment]
Thanks Nigel

**Comment by mjmare** [comment]
Hi Nigel, since you are revising the docs for the 1.1 drivers, please provide a clear comparison between the official driver and the py2neo package, with respect to scope, support, roadmap.
