### ISSUE TITLE
[Feature Request] Make DEBUG logging parameters along with query optional

### ISSUE THREAD

**Issue by havardthom** [neo4j/neo4j-python-driver#577]
Parameters may contain sensitive data which are not fit for logs, it would be great to have an option that disables the logging of parameters.

**Comment by robsdedude** [comment]
Thanks for the feedback.

I'd personally argue that DEBUG logging isn't suitable for a production system anyway. So one shouldn't end up with sensitive data in a DEBUG log.

Either way, I'll see how other official drivers handle this and come back to it.

**Comment by havardthom** [comment]
I agree that DEBUG level logging is not suitable in a production environment, there are however other scenarios such as debugging in a cloned/backup production environment. 
This is not a huge issue for us as we can just disable logging from the neo4j driver, but we would rather not be forced to disable it. Thanks for looking into it.

**Comment by robsdedude** [comment]
Thanks again for the input. We've put the idea up on our internal Trello wall for future work https://trello.com/c/PWjcnanw. We'll come back to this issue as soon as we've made a decision of either rejecting it or putting it on the road-map for a future release.
