### ISSUE TITLE
neo4j-driver 1.0.0

### ISSUE THREAD

**Issue by papachoco** [neo4j/neo4j-python-driver#60]
Hello,

Could we make available on PyPI a sdist (source/ legacy) for neo4j-driver. This is for easy-install / zc.buildout installations.

Thanks

Carlos

**Comment by technige** [comment]
Yes, that was intended for 1.0.0 but due to build server issues, a broken tarball was released and had to be removed. Due to PyPI limitations, a file name can never be reused once taken so we have no way to fix that now. From 1.0.1, this should be available.
