### ISSUE TITLE
Throw more specific exceptions / document attributes

### ISSUE THREAD

**Issue by thisjustin** [neo4j/neo4j-python-driver#61]
Currently if you were to run code like:

```
# Example from developer manual
# but how do we know this was specifically the `Neo.ClientError.Statement.InvalidSyntax` status code?
try:
    session.run("This will cause a syntax error").consume()
except CypherError:
    raise RuntimeError("Something really bad has happened!")
finally:
    session.close()
```

You would get a `CypherError` which is a catch all for a lot of different errors. Currently you would need to inspect the `code` attribute of the exception to match it up with http://neo4j.com/docs/stable/status-codes.html

Would it make more sense for this driver to check for the various codes and throw a specific error? (in this case maybe `CypherSyntaxError`)

Also, it would be helpful for the docs (or comments in the code itself) to include a mention of `code` and all the attributes we can expect to be set on an exception.

**Comment by technige** [comment]
There are pros and cons with modelling every possible status code within a client-side error. We considered this in depth during the earlier parts of the project but feel that the extra code required is less of a burden that the maintenance overhead it would introduce, given the large number of codes.

The recommended pattern (still very readable IMHO) would be:

```
try:
    session.run("This will cause a syntax error").consume()
except CypherError as error:
    if error.code == "Neo.ClientError.Statement.SyntaxError":
        raise RuntimeError("Something really bad has happened!")
    else:
        raise
finally:
    session.close()
```

A full list of status codes and their descriptions can be found here:
http://neo4j.com/docs/developer-manual/current/#status-codes
