### ISSUE TITLE
Add changelog

### ISSUE THREAD

**Issue by thisjustin** [neo4j/neo4j-python-driver#62]
It would be very helpful if a changelog was added to the repo to help us identify new features, fixes and also breaking changes with each release.

See [http://keepachangelog.com/](http://keepachangelog.com/)

**Comment by zhenlineo** [comment]
Do you mean this one? https://github.com/neo4j/neo4j-python-driver/wiki/1.0-changelog

Or do you want the changelog comes with the repo's source code directly?

**Comment by thisjustin** [comment]
@zhenlineo ah, I had no idea it was there. I always check for `changelog.md` in the root of repos. Just a link from the readme would suffice if you've already been keeping one in the wiki.
