### ISSUE TITLE
ERROR  Failed to establish connection to ResolvedIPv4Address(('127.0.0.1', 7687))  and ERROR Failed to establish connection to ResolvedIPv6Address(('::1', 7687, 0, 0))

### ISSUE THREAD

**Issue by Naama-Lazar** [neo4j/neo4j-python-driver#634]
![image](https://user-images.githubusercontent.com/73069175/147698340-509bb101-6bda-4abd-96a3-e6ea448a9584.png)
![image](https://user-images.githubusercontent.com/73069175/147698287-3644aca1-47de-4c0f-876b-3764219cefcd.png)
In the first image, I changed the line in the conf of neo4j to allow a server connection.
And in the second picture, there are still errors
Would appreciate help
Thanks

**Comment by fbiville** [comment]
Please note this kind of question is better posted in https://community.neo4j.com/.

That being said, am I missing something here or is the highlighted `dbms.connector.bolt.listen_address` line still commented?
In any case, if you are using a local Neo4j server and a locally-running application, you should not need make any changes to your server configuration.

**Comment by robsdedude** [comment]
Please refrain from double-posting your issue. I've already replied [here](https://github.com/neo4j/neo4j-python-driver/issues/509#issuecomment-1004039026).

Also, I'll close this issue as it is most likely not bug in the driver. Still, feel free to comment on it.
