### ISSUE TITLE
ProtocolError (2)

### ISSUE THREAD

**Issue by Elektra58** [neo4j/neo4j-python-driver#64]
In your example it might be helpful to address the following issue (I see, it was raised before, now in the closed issues): clear content of the known_hosts file.

``` python
D:\Anaconda3\envs\py35\python.exe D:/IdeaProjects/Test/direct.py
Traceback (most recent call last):
  File "D:\Anaconda3\envs\py35\lib\site-packages\neo4j\v1\session.py", line 146, in session
    session = self.session_pool.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/IdeaProjects/Test/direct.py", line 3, in <module>
    session = driver.session()
  File "D:\Anaconda3\envs\py35\lib\site-packages\neo4j\v1\session.py", line 148, in session
    session = Session(self)
  File "D:\Anaconda3\envs\py35\lib\site-packages\neo4j\v1\session.py", line 461, in __init__
    self.connection = connect(driver.host, driver.port, driver.ssl_context, **driver.config)
  File "D:\Anaconda3\envs\py35\lib\site-packages\neo4j\v1\connection.py", line 410, in connect
    "details in file %r" % (host, KNOWN_HOSTS))
neo4j.v1.exceptions.ProtocolError: Server certificate does not match known certificate for 'localhost'; check details in file 'C:\\Users\\########\\.neo4j\\known_hosts'

Process finished with exit code 1

```

**Comment by zhenlineo** [comment]
Quick answer:
Delete the file `C:\\Users\\########\\.neo4j\\known_hosts`

Long answer:
You are using `Trust on first use` encryption with this driver, it will create known_hosts file and then attach server's cert signature with host address and port there. So if your server changes/server cert changes, then you will be caught by this error.
You could find more info in the Encryption part in the manual.

**Comment by technige** [comment]
This behaviour is correct, as @zhenlineo mentions. For testing, we recommend disabling encryption so as to avoid this mismatch scenario.

**Comment by fab679** [comment]
This really helped thank you guys
