### ISSUE TITLE
Neo4j session.run summary is 'None'

### ISSUE THREAD

**Issue by naisanzaa** [neo4j/neo4j-python-driver#657]
This used to return the summary in an earlier version of this library, but I noticed it no longer returns the summary now.

- Neo4j version: `AuraDB`
- Neo4j Mode: `AuraDB single instance`
- Driver version: `python neo4j-driver 4.4.1 `
- Operating system: `Mac 12.3`
- **Steps to reproduce**
```
1. create cypher
2. run cypher
```
- Expected behavior
```
show summary from run response
```
- Actual behavior
```
response `_summary` property shows `None`
```

Cypher query:
```
MATCH (A  { `SSID`: "SouthPark_Guest" }) 
MATCH (B  { `SSID`: "SouthPark_Guest" }) 
WHERE A.BSSID <> B.BSSID 
MERGE (A) - [r :`EXTENDS`] -> (B) 
RETURN *
```

neo4j.work.result.Result:

<img width="615" alt="image" src="https://user-images.githubusercontent.com/58240560/153377195-18d91ac3-033a-4b1d-96be-9414dc467925.png">

**Comment by robsdedude** [comment]
Hi. For debugging it's fine to look into attributes and methods that start with `_`. But please refrain from using them for anything else. In Python, it's common agreement to treat them like `private` attributes in other languages. If you want to access the summary of a query, you have to `consume()` the result ([API docs](https://neo4j.com/docs/api/python-driver/4.4/api.html#neo4j.Result.consume)). This will not only return the summary but make sure the driver does what's necessary to obtain it.

I hope this helps. I'll be closing this issue as it does not seem to be a bug in the driver. However, you are welcome to keep commenting should you need more support or think there is a bug.
