### ISSUE TITLE
Session.close() fails when using transactions in some cases

### ISSUE THREAD

**Issue by mjmare** [neo4j/neo4j-python-driver#67]
I have this test code. Since the docs stress that the session should be closed whatever happens, I have an session.close() in the try/except/finally construct. 

There seems to be a difference between an exception in cypher (error case 1) and a regular exception (see error case 2).  In the first case I get an error in the line session.close(): "neo4j.v1.exceptions.CypherError: rollback cannot be done when there is no open transaction in the session.” In the second case (of course commenting out case 1): no error and the tx is rolled back correctly.

```
from neo4j.v1 import GraphDatabase, basic_auth, TRUST_ON_FIRST_USE

driver = GraphDatabase.driver("bolt://localhost:7000",
                              auth=basic_auth("neo4j", "test"),
                              encrypted=False,
                              trust=TRUST_ON_FIRST_USE)

session = driver.session()
tx = session.begin_transaction()

try:
    result = tx.run("CREATE (n:Person{lastname:'test', firstname:'T'})")
    # Error case 1: with the following 2 lines uncommentend one gets the problem
    result = tx.run("XXMATCH (n:Person)-[r]->(m) RETURN n, r, m")
    result = list(result)
    # Error case 2: with the following line uncommented instead of the previous two one does not get the problem
    # raise Exception('Testing exception')

    tx.commit()
except Exception as e:
    print('*** ',e)
    tx.rollback()
finally:
    session.close()
```

**Comment by technige** [comment]
When a Cypher error occurs, the transaction is rolled back by the server and therefore the client will be unable to subsequently roll back that transaction itself. Conversely, a client-side exception is unseen by the server and the client will need to explicitly perform a rollback.

You probably want to consider catching `CypherError` instead of just general exceptions so that you can distinguish between the two.

**Comment by mjmare** [comment]
That makes sense. Creates an extra burden for the user. You might consider adding an explanation to the docs. 

So if I understand correctly, this should be the correct way to handle this situation:

```
from neo4j.v1 import GraphDatabase, basic_auth, TRUST_ON_FIRST_USE, CypherError

driver = GraphDatabase.driver("bolt://localhost:7000",
                              auth=basic_auth("neo4j", "test"),
                              encrypted=False,
                              trust=TRUST_ON_FIRST_USE)

session = driver.session()
tx = session.begin_transaction()

try:
    result = tx.run("CREATE (n:Person{lastname:'test', firstname:'T'})")
    result = tx.run("XXMATCH (n:Person)-[r]->(m) RETURN n, r, m")
    result = list(result)

    tx.commit()
    print('after commit')

except Exception as e:
    print('*** Got exception',e)
    if not isinstance(e, CypherError):
        print('*** Rolling back')
        tx.rollback()
    else:
        print('*** Not rolling back')
finally:
    session.close()
```

Seems to work. However when I delete the line "result = list(result)" no exception is thrown. The line "after commit" is printed! Only the line "session.close()" will yield the CypherException!

**Comment by technige** [comment]
We'll add more clarity on this to the docs.
