### ISSUE TITLE
How to get Neo4j Transaction Summary?

### ISSUE THREAD

**Issue by laxmimerit** [neo4j/neo4j-python-driver#677]
Hi,
I am trying to get a transaction summary after a read or write transaction. I have written some code to get this but these aren't working.

**Code**
```
def write_data(tx, query):
    result = tx.run(query)
    record = result.single()
    value = record.value()
    info = result.consume()
    return value, info

def commit_data(query):
    with driver.session(database="neo4j") as session:
        node_id, info = session.write_transaction(write_data,query)
        print(node_id, info, type(node_id), info.database, info.plan, info.profile)
```
```
output
--------
1 <neo4j.work.summary.ResultSummary object at 0x000001DB94F1D0D0> <class 'int'> neo4j None None
```
I get the type of result as `ResultSummary ` but this object doesn't have any useful info here. This summary clearly says result plan and profile both are `None` but actually result should be having information like this as per neo4j desktop browser. Kindly help me to get the result summary.
```
[
  {
    "batches": 1,
    "total": 8077,
    "timeTaken": 0,
    "committedOperations": 8077,
    "failedOperations": 0,
    "failedBatches": 0,
    "retries": 0,
    "errorMessages": {

    },
    "batch": {
"total": 1,
"committed": 1,
"failed": 0,
"errors": {

      }
    },
    "operations": {
"total": 8077,
"committed": 8077,
"failed": 0,
"errors": {

      }
    },
    "wasTerminated": false,
    "failedParams": {

    },
    "updateStatistics": {
"nodesDeleted": 8077,
"labelsAdded": 0,
"relationshipsCreated": 0,
"nodesCreated": 0,
"propertiesSet": 0,
"relationshipsDeleted": 14528,
"labelsRemoved": 0
    }
  }
]
```

**Comment by robsdedude** [comment]
Hi and thanks for reaching out to us. You are on the right track. The summary object is what you're after. That `plan` and `profile` are empty (`None`) is to be expected unless you explicitly run an [`EXPLAIN` or `PROFILE` query](https://neo4j.com/docs/cypher-manual/current/query-tuning/how-do-i-profile-a-query/#how-do-i-profile-a-query). Have a look around the [other properties of the summary object](https://neo4j.com/docs/api/python-driver/4.4/api.html#neo4j.ResultSummary) (like `.counters`, `.notifications` (could also be empty), `.result_available_after`, ...).
Some of the statistics your example shows (like `batches`) seem to be neo4j browser specific hand don't come from the database but from how neo4j browser handles queries for you.

I'll close this issue as it does not seem to be a bug in the driver. Please feel free to comment nonetheless, should you have more questions.

**Comment by laxmimerit** [comment]
Hi,
Just wanted to post the answer to this question in case anyone else lands here.
```
def commit_data(query):
    with driver.session(database="neo4j") as session:
        tx = session.begin_transaction()
        result = tx.run(query)
        result = [dict(i) for i in result]
        
       # uncomment below line to see the complete txn summary.
        # print(result) 

        if result[0]['failedOperations']>0:
            print(query)
            print(result)
            raise 'Error! Please recheck your query.'
        
        tx.commit()
```
