### ISSUE TITLE
spelling error in exception text

### ISSUE THREAD

**Issue by djhenderson** [neo4j/neo4j-python-driver#70]
After `pip install neo4j-driver==1.0.0` and installing `neo4j-community_windows-x64_3_0_1.exe`, after a deliberate error, in this (abbreviated) trace back:

```
Traceback (most recent call last):
  ...
  File "…\site-packages\neo4j\v1\connection.py", line 227, in on_failure
    raise ProtocolError(metadata.get("message", "Inititalisation failed"))
neo4j.v1.exceptions.ProtocolError: Authentication token must contain: 'scheme : basic' (ID:33C2200B5DCC917A46392A99DB54B
53104BAFC2D0F4ECEF2E73D554A0A149C02)
```

you can see that Initialization is misspelled as "Inititalisation". My spelling corrector used en_CA, you may prefer the en_US spelling of Initialisation.

**Comment by technige** [comment]
This has now been fixed.

https://github.com/neo4j/neo4j-python-driver/blob/1.0/neo4j/v1/connection.py#L229
