### ISSUE TITLE
'Too many files open' or 'StopAsyncIteration' Exception when working with async

### ISSUE THREAD

**Issue by ghost** [neo4j/neo4j-python-driver#729]
Hi,

I'm using async support to run queries concurrently. My code is below. If I create driver for each thread (VERSION 1 below) and than use those drivers in only one thread at a specific time, it throws **StopAsyncIteration** on the second iteration(I inspected the code and it's unable to receive message from neo4j, I can give details if you want).  So I decided to create the driver inside the thread instead (VERSION 2). In this method, No StopAsyncIteration is raised because each query is the first query for that driver. And therefore I have a code loading data concurrently to Neo4j successfully ( Although I'm not sure if creating a new driver is a nice solution in each iteration - Of course I close drivers after all threads completed running).

The issue with this solution is that after a while, python raises '**Too many files open'** exception because even if I close drivers, sockets these drivers using are not closed. So I **edited** the driver code to close socket when closing the driver. I hope this solves this problem.

I'm wondering if my VERSION 2 solution is good or is there any other way without creating new drivers in  each iteration and not having StopAsyncIteration Exception?

Thanks.

```
def main():
    # Create async drivers for VERSION 1
    asyncio.run(self.run_asyncio(process_params))

async def run_asyncio(self, process_params):
    tasks = []
    for p in process_params:
        tasks.append(asyncio.create_task(self.run_cql(p['session_index'], p['cql'], p['rows_dict'])))

    await asyncio.gather(*tasks)

```
VERSION 1 (raises StopAsyncIteration)

 ```
async def run_cql(self, session_index, cql, dict):
        print('Running session %d' % session_index)

        session = self._async_drivers[session_index].session(**self.db_config)

        # session.run() throws an Exception, having trouble communicating with neo4j on the 2nd run
        # couldn't figure out why, this solution works well
        tx = await session.begin_transaction()
        await tx.run(cql, dict=dict)
        await tx.commit()

        await session.close()

        print('Completed session %d' % session_index)
```

VERSION 2 (works but after a while raises 'Too many open files' exception)

   ```
 async def run_cql(self, session_index, cql, dict):
        print('Running session %d' % session_index)
        driver = async_db.driver(config['server_uri'],
                                 auth=(config['admin_user'],
                                       config['admin_pass']))
        self._async_drivers.append(driver)

        session = driver.session(**self.db_config)

        # session.run() throws an Exception, having trouble communicating with neo4j on the 2nd run
        # couldn't figure out why, this solution works well
        tx = await session.begin_transaction()
        await tx.run(cql, dict=dict)
        await tx.commit()

        await session.close()
        await driver.close()

        print('Completed session %d' % session_index)
```

**Comment by robsdedude** [comment]
Hi, thanks for contacting us. There are several question in this issue. I'll have a closer look at the details tomorrow.

For now, I want to highlight that it is not recommended to open multiple drivers. Have one global driver instance from which you create one or multiple sessions in each coroutine (or thread when using threading). A driver maintains a connection pool. By opening as many drivers as you have jobs, you create at least as many connections. This might easily overload the server resulting in `neo4j.exceptions.TransientError: {code: Neo.TransientError.Request.NoThreadsAvailable} {message: There are no available threads to serve this request at the moment. You can retry at a later time or consider increasing max thread pool size for bolt connector(s).}`

Secondly, I'd really appreciate if you could post the stacktrace of the mentioned `StopAsyncIteration`.

**Comment by ghost** [comment]
I initally of course went with one driver approach but I had problems with it. I'll post the details tomorrow.

**Comment by robsdedude** [comment]
Closing the issue as the user deleted their account. I don't expect more details.
