### ISSUE TITLE
What is the tx parameter?

### ISSUE THREAD

**Issue by steve-solun** [neo4j/neo4j-python-driver#775]
I am trying to understand what is tx in the following code. I don't see any declaration of `tx` and will be happy to understand what is it.

```
from neo4j import GraphDatabase

driver = GraphDatabase.driver("neo4j://localhost:7687", auth=("neo4j", "password"))

def add_friend(tx, name, friend_name):
    tx.run("MERGE (a:Person {name: $name}) "
           "MERGE (a)-[:KNOWS]->(friend:Person {name: $friend_name})",
           name=name, friend_name=friend_name)

def print_friends(tx, name):
    for record in tx.run("MATCH (a:Person)-[:KNOWS]->(friend) WHERE a.name = $name "
                         "RETURN friend.name ORDER BY friend.name", name=name):
        print(record["friend.name"])

with driver.session() as session:
    session.write_transaction(add_friend, "Arthur", "Guinevere")
    session.write_transaction(add_friend, "Arthur", "Lancelot")
    session.write_transaction(add_friend, "Arthur", "Merlin")
    session.read_transaction(print_friends, "Arthur")

driver.close()
```

**Comment by steve-solun** [comment]
@srbaker @mneedham @boggle @akollegger @robsdedude

**Comment by steve-solun** [comment]
https://github.com/neo4j/neo4j-python-driver/blob/5.0/neo4j/_sync/work/session.py

**Comment by robsdedude** [comment]
Thanks for contacting us. The docs are indeed not very explicit about this. This has already been improved upon in 5.0 https://github.com/neo4j/neo4j-python-driver/blob/799720d58a167423c35bafc1aa708b2b84a368a0/docs/source/api.rst?plain=1#L826

**Comment by steve-solun** [comment]
Thanks a lot dear @robsdedude

**Comment by fbiville** [comment]
In the future, please note that https://community.neo4j.com/ is a better fit for this kind of questions.
