### ISSUE TITLE
Inconsistent relationship content when using map projections

### ISSUE THREAD

**Issue by livni** [neo4j/neo4j-python-driver#811]
Relationship returns different content than in the browser, when map projections are used

- Neo4j version: 4.3.9
- Neo4j Mode: Single instance
- Driver version: 5.0.1
- Python: 3.8.13
- Operating system: MacOS

### Steps to reproduce
Create the following scenario:

> CREATE (a:Test {alpha:1, beta:2})-[:RTEST]->(b:Test {alpha:3, beta:4})

Fetch the data once in the browser with:

> MATCH (a:Test)-[r:RTEST]->(b:Test)
> RETURN a, b, r

Fetch the data a second time in the browser with:

> MATCH (a:Test)-[r:RTEST]->(b:Test)
> RETURN a{.alpha}, b{.alpha}, r

Notice that in the browser, even though we used map projections for `a` and `b`, the relationship `r` is returned with full information.

Now let's try that again in python...
Try once with

> response = dbService.run_query("""MATCH (a:Test)-[r:RTEST]->(b:Test) RETURN a, b, r""",{}).data()

and once with

> response = dbService.run_query("""MATCH (a:Test)-[r:RTEST]->(b:Test) RETURN a{.alpha}, b{.alpha}, r""",{}).data()

You will notice that response['r'] is different between the two. When we used map projections `r` completely lost it's data - a very different behavior than in the browser, where at least it retained the IDs of the objects

**Comment by robsdedude** [comment]
I think this boils down to the fact that `.data()` never contains ids. Not with the first and not in the second query. And as you noticed (or at least alluded to) yourself: if you don't return the nodes but only the relationship (and optionally some other attributes, but not nodes), there is not way for the driver to populate the nodes in the relationship. All it will know is the id of the nodes. And when using `Result.data()` you just throw away that information.

Try this example insted

```python
import neo4j


def work(tx, query, **params):
    res = tx.run(query, **params)
    return list(res), res.consume()


def main():
    uri = "neo4j://localhost:7687"
    auth = ("neo4j", "pass")
    with neo4j.GraphDatabase.driver(uri, auth=auth) as driver:
        with driver.session(database="neo4j") as session:
            session.execute_write(
                work,
                "MERGE (a:Test {alpha:1, beta:2})"
                "-[:RTEST]->(b:Test {alpha:3, beta:4})"
            )
            records, _ = session.execute_read(
                work,
                "MATCH (a:Test)-[r:RTEST]->(b:Test) RETURN a, b, r"
            )
            assert len(records) == 1
            print(records[0].values("a", "b", "r"))
            records, _ = session.execute_read(
                work,
                "MATCH (a:Test)-[r:RTEST]->(b:Test) "
                "RETURN a{.alpha}, b{.alpha}, r"
            )
            assert len(records) == 1
            print(records[0].values("a", "b", "r"))


if __name__ == '__main__':
    main()
```

And you will see that the id (called `element_id` starting with 5.0) is present with both queries.

Output:
```
[<Node element_id='0' labels=frozenset({'Test'}) properties={'alpha': 1, 'beta': 2}>, <Node element_id='1' labels=frozenset({'Test'}) properties={'alpha': 3, 'beta': 4}>, <Relationship element_id='0' nodes=(<Node element_id='0' labels=frozenset({'Test'}) properties={'alpha': 1, 'beta': 2}>, <Node element_id='1' labels=frozenset({'Test'}) properties={'alpha': 3, 'beta': 4}>) type='RTEST' properties={}>]
[{'alpha': 1}, {'alpha': 3}, <Relationship element_id='0' nodes=(<Node element_id='0' labels=frozenset() properties={}>, <Node element_id='1' labels=frozenset() properties={}>) type='RTEST' properties={}>]
```

I hope I could answer your question. As I don't see a bug in the driver here, I will close this issue. But please feel free to keep commenting if you have further questions or have a look at our [community forums](https://community.neo4j.com/) or [stackoverlfow](https://stackoverflow.com/questions/tagged/neo4j).

A final note: `Result.data()` is more tailored to rapid prototyping than a reliable application. It has it's limitations and certainly doesn't give you full control over the result object.
