### ISSUE TITLE
Multiple statements per query

### ISSUE THREAD

**Issue by Travis-Barton** [neo4j/neo4j-python-driver#826]
How do I exicute multiple statements in one query. Ex:

```
app = App(uri, username, password)
query = """
        MATCH
          (a:GENE),
          (b:GENE)
        WHERE a.name = 'name1' AND b.name = 'name2'
        CREATE (a)-[:PPrel]->(b);
        
        MATCH
          (a:GENE),
          (b:GENE)
        WHERE a.name = 'name3' AND b.name = 'name4'
        CREATE (a)-[:PPrel]->(b);
"""
app.run(query)
```

returns

```
neo4j.exceptions.CypherSyntaxError: Expected exactly one statement per query but got: 2 (line 1, column 0 (offset: 9))
```

I'm really trying to add 59,000 relationships and batching those queries would be a lot faster than doing them 1 by 1. How do I submit more than one statement per query?

**Comment by robsdedude** [comment]
Hi and thanks for reaching out to us.

The GitHub issues are more for potential bugs and mistakes in the driver. Questions about usage (and especially the cypher query language) are better suited to [stackoverflow](https://stackoverflow.com/questions/tagged/neo4j), the [community forums](https://community.neo4j.com/). If you are a enterprise customer, you can also contact your support agent.

To sill give you at least some pointers:  
You could use the [`UNWIND` clause](https://neo4j.com/docs/cypher-manual/current/clauses/unwind/) and pass the list of name pairs as parameter through the driver.

Something like (untested):
```python
import neo4j


def work(tx, query, **params):
    res = tx.run(query, **params)
    return list(res), res.consume()


def main():
    uri = "neo4j://localhost:7687"
    auth = ("neo4j", "pass")
    with neo4j.GraphDatabase.driver(uri, auth=auth) as driver:
        with driver.session(database="neo4j") as session:
            query = (
                "UNWIND $pairs AS pair "
                "MATCH "
                "  (a:GENE {name: pair[0]}), "
                "  (b:GENE {name: pair[1]}) "
                "CREATE (a)-[:PPrel]->(b)"
            )
            pairs = [["name1", "name2"], ["name3", "name4"]]
            session.execute_write(query, pairs=pairs)


if __name__ == '__main__':
    main()
```
