### ISSUE TITLE
Project dependencies may have API risk issues

### ISSUE THREAD

**Issue by PyDR-Tool** [neo4j/neo4j-python-driver#841]
Hi, In **neo4j-python-driver**, inappropriate dependency versioning constraints can cause risks.

Below are the dependencies and version constraints that the project is using

```
pytz
```

The version constraint **==** will introduce the risk of dependency conflicts because the scope of dependencies is too strict.
The version constraint **No Upper Bound** and **\*** will introduce the risk of the missing API Error because the latest version of the dependencies may remove some APIs.

After further analysis, in this project,
The version constraint of dependency **pytz** can be changed to *>=2011d,<=2013d*.
The version constraint of dependency **pytz** can be changed to *>=2011b,<=2022.1*.

The above modification suggestions can reduce the dependency conflicts as much as possible, 
and introduce the latest version as much as possible without calling Error in the projects.

The invocation of the current project includes all the following methods.

<details><summary>The calling methods from the pytz</summary>
 <pre>pytz.FixedOffset
pytz.UTC.localize
pytz.timezone
</pre>
</details>
<details><summary>The calling methods from the all methods</summary>
 <pre>self.server_info.update
time.Duration
_driver_logger.buffer_handler.stream.getvalue.endswith
tuple.append
mcs.ConfigType.super.__new__
os.strerror
self._writer.drain
self.defunct
self.days_in_month
tx.run.peek
neo4j.time.DateTime.from_clock_time
i.prefix.v.self._transform.items
time.DateTime.combine
_async_compat.concurrency.AsyncRLock
val.eval.eval
self._check_state
self.__iter__
deprecated_aliases.keys
mock.Mock
self.opener
datetime.datetime.fromtimestamp
tz.localize.utcoffset
code.split
value.type.hydration_hooks
setattr
self.__enter__
cls.keys
_Routing.__init__
metadata.pop
self._update_routing_table_from
self.fetch_routing_info.get
self_norm.replace.time
connection.socket.get_deadline
add_months
self._writer.close
self._run
self._unpack_map
cls.__subclasses__
connection_.defunct
self._properties.get
async_main
cls.__calc_ordinal
connection_.reset
self.__mod__
self._wr.drain
template.format
k.startswith
_warning_check.warning_check
self._transform
self_norm.replace.replace
TypeError
self._pool.close
dt.astimezone.to_clock_time
HydrationScope
time.DateTime.from_native
random.choice
IndexError
self.callbacks.pop
selector.register
asyncio.get_event_loop.sock_connect
experimental_warn
asyncio.current_task
self.hydration_handler.new_hydration_scope
neo4j.TrustAll
BoltSocket._secure.getpeercert
list
__file__.Path.absolute.resolve
self.next_key
self._subclass_by_family
int
DeprecatedAlternative
self._elements.keys
self.close_socket
dt_columns.df.apply
_routing.RoutingTable.parse_routing_info
_meta.unclosed_resource_warn
logging.getLogger.isEnabledFor
self.__copy__
nanoseconds.str.rjust.rstrip
datetime.datetime
self.cond.notify_all
session.begin_transaction.run
self._acquire.close
add_days
addressing.Address
cls.version_list
AsyncBoltDriver.open
self.__time.replace
tz.timezone.utc.DateTime.utc_now.replace.astimezone.timetz
neo4j.GraphDatabase.driver.session
_spatial.point_type
self.Watcher.super.__init__
neo4j.AsyncGraphDatabase.driver.get_server_info
self._auto_result._buffer_all
get_date_unix_epoch
zip.append
functools.partial
neo4j.GraphDatabase.driver.supports_multi_db
super.acquire
server.AsyncServer.stop
dict
self.combine
result.Result
base._deprecated_options
self.pack_string_header
cls.consume_chain
sorted
_bookmarks_to_set
socket_.close
number
ClockTime
other_norm.replace.replace
self.__time.dst
self._writer.transport.get_extra_info
totestkit.field
repr
self._lock.acquire
exceptions.BrokenRecordError
functools.reduce
self.__add__
other_norm.replace.time
neo4j.GraphDatabase.driver.verify_connectivity
AsyncNeo4jDriver.open
self._commit
fake_connection_generator
cls.neo4j_driver
KeyError
Driver.__init__
self.AsyncNeo4jPool.super.deactivate
struct.pack
deprecated_alternatives.update
neo4j.GraphDatabase.driver.close
iter_items
exceptions.MarkdAsDriverException
asyncio.get_event_loop
neo4j.spatial.CartesianPoint
data.keys
neo4j._async_compat.util.AsyncUtil.next
self.readers.replace
subtest_args.mark_all_as_read
logging.StreamHandler.setFormatter
neo4j._deadline.Deadline.from_timeout_or_deadline
record.data
exceptions.ReadServiceUnavailable
api.ServerInfo
properties.items
self._requestHandlers.get
matcher.match
exceptions.SessionExpired
s.getsockname
Version
ctypes.byref
inspect.getmembers
self.__on_error
neo4j._async_compat.util.Util.list
session._get_server_info
self._properties.items
_cancel_and_wait
super.release
self.locked
deprecation_warn
to_param
neo4j.basic_auth
traceback.extract_tb
work.ResultSummary
self.getsockname
self._set_cached_database
Date.to_ordinal
self.handlers.get
point_type
to_cypher_and_params
self._pool.acquire
self.struct_hydration_functions.update
self.tzinfo.dst.total_seconds
deprecated_alternatives.keys
asyncio.iscoroutinefunction
data.split
_common.HydrationScope
f
self._update_bookmarks
exceptions.ResultNotSingleError
tuple.__new__
self._send_all
datetime.time
self.__calc_ordinal
get_date_unix_epoch_ordinal
datetime.date
result.AsyncResult._tx_ready_run
kwargs.mark_all_as_read
next
_data.RecordTableRowExporter
error.is_retryable
cls
cls.protocol_handlers
bolt_cls.hello
self.socket.sendall
other_norm.replace.date
to_raise
self.pack_bytes_header
_Module
health_check
self._unpacker.reset
platform.uname
Entity.__init__
session.run.single.value
d.append
bolt_cls.kill
_async.backend.AsyncBackend.close
_meta.get_user_agent
self.closed
Time.from_iso_format
self._struct_hydration_functions.get
self._elements.clear
epoch.time
dt.astimezone.astimezone
logger.setLevel
self._handlers.pop
self.Neo4jPool.super.deactivate
mocker.AsyncMock
api.Version
self._error_handling_connection.send_all
time.struct_time
functools.wraps
bytes
self.__new__
Clock.local_time
self.driver.close
graph.Graph
_meta.deprecated
iso_week_1.to_ordinal
cls._deprecated_keys
Date.from_iso_format
time.mktime
type.cast
self.hydrate_node
collections.deque
asyncio.Lock
self.deactivate
BoltSocket._secure.gettimeout
self.outbox.append_message
min
self.timetz.iso_format
neo4j.kerberos_auth
asyncio.get_event_loop.create_connection
BoltSocket._handshake
io.ConnectionErrorHandler
_exceptions.BoltHandshakeError
cls._connect_secure
self.responses.append
self._unpacker.unpack_structure_header
TrustAll
epoch.to_ordinal
inst._properties.update
self._deadline.to_timeout
initial_bookmarks.items
self.recv
pytz.UTC.localize
curr_bms.update
_codec.hydration.v1.spatial.hydrate_point
self._deprecated_alternatives
self._bookmarks.pop
values.append
predicate
asyncio.ensure_future.done
readers.extend
self.ensure_routing_table_is_fresh
value.tzinfo.utcoffset
AsyncNetworkUtil.get_address_info
self.transform
bookmark_manager.Neo4jBookmarkManager
v.tzinfo.utcoffset
_common.AsyncOutbox
timestamp.cls.utc_from_timestamp.replace
resolution_func
self._results.append
issubclass
self._socket.close
selectors.DefaultSelector
backend.bookmarks_supplies.pop
loop.call_later.cancel
_deadline.Deadline.from_timeout_or_deadline
database.self.routing_tables.routers.discard
_bolt3.ServerStateManager
collections.deque.append
EntitySetView
NetworkUtil.get_address_info
self._set_defunct
self.hydrate_unbound_relationship
neo4j.custom_auth
tx._commit
asyncio.start_server
tx.run.single
self.outbox.flush
super.__str__
self._record_buffer.clear
self.cond.wait
self.read_u8
e.is_fatal_during_discovery
tx_cls
self.get_base_headers
name.startswith
self.tzinfo.utcoffset
json.loads.get
json.load.items
time_.date_.self.combine.replace
set
tz.timezone.utc.DateTime.utc_now.replace.astimezone.date
DateTime
self.writers.replace
nanoseconds.str.rjust
inspect.isawaitable
data.get
self._select_address
BoltSocket._secure.sendall
io.AsyncNeo4jPool.open.get_default_database_initial_router_addresses
example.driver.session
re.compile.match
self._lock._acquire
value.tz.utcoffset.total_seconds
value.encode
asyncio.sleep
func.startswith
self.pack
self._record_buffer.popleft
self.__date.to_ordinal
work.AsyncSession
cls.close_socket
self.socket.getsockname
self._acquire_non_blocking
subprocess.run
_async_compat.concurrency.Condition
day_of_week
self._hydration_scope.get_graph
address.self.connections.get.remove
parts.append
self._unpack
self._disconnect
BoltSocket._secure.recv
self.connections.pop
config.keys
asyncio.StreamReaderProtocol
self._writer.write
entities.append
api.parse_neo4j_uri
self.__subclasses__
col.map
r
self._properties.keys
cls.parse_target
self.release
self._acquire.stale
request.param
selector.select
self.fetch_message
value.value.tzinfo.utcoffset.total_seconds
random.random
self._buffer
self._rollback
time.Date
asyncio.TimeoutError
BoltSocket._secure
Neo4jDriver.open
Clock
_util.AsyncNetworkUtil.resolve_address
self.pull
math.isnan
time.Date.from_ordinal
neo4j.time.Date
TrustSystemCAs
bool
failed_addresses.append
neo4j.TrustCustomCAs
subprocess.check_call
mocker.Mock
self._connection.pull
self._acquire.set_stale
clock.available
statistics.dict.items
graph.Node
self.session
self.pool.mark_all_stale
deprecated
attrs.append
self.get_default_database_initial_router_addresses
scripted_connection_generator
self._elements.update
neo4j.time.Clock.utc_time
dict_of_closables.items
_arithmetic.symmetric_divmod
ConnectionError
self._connect
session.run
v.items
self.local_offset
exceptions.AuthError
callable
self._discard
neo4j.Auth
_async_compat.network.AsyncNetworkUtil.resolve_address
self._process
warn_log.pop
ctypes.CDLL.clock_gettime
collections.defaultdict
self.connection.reset
data.mark_item_as_read_if_equals
driver.session.begin_transaction
logging.getLogger
k.replace.replace
neo4j.spatial.WGS84Point
re.compile
exceptions.UnsupportedServerProduct
self._server.close
self._auto_result.consume
driver.session.last_bookmarks
int.ljust
BoltDriver.open
self._loop.create_future.set_result
struct.unpack
logging.getLogger.addHandler
NotImplementedError
routers.extend
os.path.dirname
sys.exit
self._loop.create_future.done
super
self.__floordiv__
format
self._handle_cancellation
time.time
fromtestkit.to_tx_kwargs
coords.append
k.replace.replace.prefix.v.self._transform.items
cls.Bolt.get_handshake
routing_table.__getattribute__
backend.process_request
_async_compat.async_sleep
_driver_logger.buffer_handler.stream.getvalue
_deadline.Deadline.from_timeout_or_deadline.expired
curr_bms.difference_update
self.get_routing_table_for_default_database
connections.remove
self._acquire.reset
coroutine_func
BoltSocket._secure.setblocking
os.environ.get
neo4j.TrustSystemCAs
exceptions.ServiceUnavailable
rejected_keys.append
self._get_new
self._run_transaction
_is_leap_year
offset.self.replace
self._writer.transport.get_extra_info.getpeercert
self.gettimeout
self.sendall
tz.utcoffset
self.Request.super.get
_common.Outbox
self.keys
Time.from_ticks
asyncio.get_running_loop.call_later
self.read
self._unpack_structure_header
self._acquire.kill
super.__getattr__
self._wr.write
_async_compat.concurrency.CooperativeRLock
pandas.api.types.infer_dtype
AssertionError
DateTime.utc_now.replace
addresses.append
_deprecated_keys
pytz.timezone.localize
Date
ssl.SSLContext
ClockTime.utcoffset
cls.days_in_month
write
s.partition
asyncio.StreamReader
self._on_cancel
enumerate
_common.check_supported_server_product
super.__repr__
exceptions.ConfigurationError
typing.cast
server.AsyncServer.serve_forever
self.ColourFormatter.super.format
server.AsyncServer.start
async_scripted_connection_generator
time.DateTime.to_clock_time
addressing.log.debug
self.state.self._STATE_TRANSITIONS.get.get
self._clear
self._error_handling_connection.fetch_all
connection_.is_idle_for
_conf.PoolConfig
self.date.iso_format.split
self._buffer.clear
self._get_both_normalized_ticks
self._connection.rollback
BoltSocket._secure._handshake
AsyncDriver.__init__
RecordExporter
neo4j.exceptions.ConfigurationError
super.__getitem__.mark_all_as_read
sock.getsockname
RuntimeError
self.pack_raw
skip_decorator
_common.Structure
asyncio.ensure_future.remove_done_callback
_driver_logger.log.info
_conf.SessionConfig
backend.next_key
self.read.tobytes
transport.get_extra_info
vars
codecs.decode
self._socket.settimeout
result.AsyncResult
PackableBuffer
Date.from_ordinal
self.acquire
self.pack_map_header
packer_cls
memoryview
cls.__normalize_nanosecond
ssl_context.wrap_socket
sys.argv.lower
classmethod
neo4j.time.ClockTime
neo4j.Query
v.v.tzinfo.utcoffset.total_seconds
pytz.FixedOffset
self.dehydration_functions.update
self.close
all
io.Neo4jPool.open.get_default_database_initial_router_addresses
warnings.filterwarnings
deprecated_aliases.get
super.__getitem__
int.from_bytes
self._acquire_from_pool_checked
SummaryCounters
neo4j.time.Duration
self.routers.replace
record.values
slice
tuple.__repr__
socket.socket
self.pool.on_write_failure
_common.Response
experimental_options.update
self._enter
self.responses.popleft.on_success
dict_of_closables.clear
float
_conf.iter_items
self.__aiter__
_async_compat.concurrency.RLock
map
self._bookmarks.keys
self.socket.getpeercert
self.unpackable.read_u8
self.in_use_connection_count
self.socket.close
_data.RecordTableRowExporter.transform.values
dict.items
time.time_ns
load_config
x.iso_format
asyncio.ensure_future.cancel
dt.date
nanoseconds.abs.str.rjust.rstrip
DateTime.from_native
socket.getaddrinfo
self.type_
nodes.append
address.self.in_use_connection_count.addresses_by_usage.setdefault.append
object.__repr__
key_to_attr_name.get
neo4j.AsyncGraphDatabase.driver.verify_connectivity
sys.argv.lower.strip
line.decode.rstrip.decode
run
self._broken_record_error
logging.getLogger.setLevel
converter
k.replace.replace.v.self._transform.items
Time
self.time.to_clock_time
work.Session
_exceptions.BoltSecurityError
threading.Lock
self._connection.begin
self._server.serve_forever
exceptions.TransactionError
self.connections.get
socket.getpeername
self._connection.fetch_all
self.socket.attach_mock
type
e.clear
self._packer.pack_struct
iso_week_1
TIME_ISO_PATTERN.match.group
self.to_ordinal
_conf.Config.consume_chain
self.pack_struct
server.AsyncServer.handle_request
self.func
_driver_logger.log.error
socket_.shutdown
server.AsyncServer
self.callbacks.append
_driver_logger.buffer_handler.stream.seek
_bolt.AsyncBolt.open
sock.getpeername
driver.session.close
self.get_or_create_routing_table.update
sock.recv_into
result.Result._tx_ready_run
Duration
self._update_bookmark
tz.fromutc
self._loop.create_future.cancel
time_remaining
self._exc_msg
session._connect
self._release
tx._close
_arithmetic.round_half_to_even
self.__date.weekday
self.replace
self.__iter__.__next__
print
address.self.connections.append
_exceptions.SocketDeadlineExceeded
srid_map.items
set_attr
connection_.closed
neo4j.AsyncGraphDatabase.bookmark_manager
cls.parse
self._attach
unpacker_cls
driver.session.run
io.Neo4jPool.open
dt.to_native
self.unpackable.read
self._lock._release
_async.backend.AsyncBackend
_GraphHydrator
object.__new__
pandas.Timestamp
self.get_or_create_routing_table.servers
self._unpack_list_items
self.code.split
summary.parameters.items
self.items
shims.wait_for
self._get_all_bookmarks
outer
self._unpacker.unpack
FrontendError
asyncio.ensure_future.result
self.toordinal
Watcher.watch
_meta.experimental
self._connection.discard
transport.get_extra_info.getpeercert
io.AsyncNeo4jPool.open
_arithmetic.nano_divmod
addresses_by_usage.setdefault
receive_into_buffer
os.path.abspath
Clock.utc_time
address.rsplit.rsplit
iter
packer_cls.new_packable_buffer
self.__date.iso_calendar
tx.run.consume
agent.startswith
self.is_owner
_async_compat.concurrency.CooperativeLock
api.parse_routing_context
Date.from_native
neo4j.__version__.split
hydration_handler.new_hydration_scope
self._chunk_data
datetime.timezone.utc.timestamp.cls.utc_from_timestamp.replace.astimezone
neo4j.unit_of_work
neo4j.GraphDatabase.driver.get_server_info
_codec.hydration.v1.spatial.dehydrate_point
_Direct.__init__
deprecated_alternatives.get
str
typing_extensions.ParamSpec
self.socket.settimeout
t.replace.as_timezone
neo4j.time.DateTime
_async_compat.network.AsyncBoltSocket.close_socket
int.lstrip
self.pool.deactivate
unpacker_cls.new_unpackable_buffer
addressing.Address.parse_list
cls._find_subclass._find_subclass
self.send_response
BoltSocket._secure.getsockname
self._pool.kill_and_release
self._pool.update_routing_table
ClockTime.time
time.gmtime
base.keys
driver.session.execute_read
io.AsyncBoltPool.open
exceptions.Neo4jError.hydrate
writers.extend
self.Bolt.get_handshake
x.iso_format.pd.Timestamp.replace
fr.read
ix.encode
cls._find_subclass
asyncio.ensure_future.add_done_callback
self._deprecated_aliases
self._WAITERS_RE.search.group
self._get_bookmarks
self.get_base_headers.update
self.attach_mock
self.from_native
self._buffer.is_tmp_buffering
self._initialize_bookmarks
self_norm.replace.date
fields.append
neo4j.AsyncGraphDatabase.driver.close
self.responses.popleft.on_ignored
transaction_function
io.BoltPool.open
datetime.timezone.utc.DateTime.utc_now.replace.astimezone
setuptools.find_packages
msg.format
connection.new_hydration_scope
self._connection.send_all
self._get_bookmarks.update
open
cls.protocol_handlers.keys
self.unpack
record.items
time.DateTime.from_native.to_clock_time
self.fetch_routing_info
zip
_common.Structure.encode
_deadline.connection_deadline
range
logging.getLogger.debug
writer.close
neo4j.time.Clock
logger.removeHandler
self.notify
self.fetch_all
self.date.iso_format
self._TimeSpec
SessionTracker
self._write
res.update
self._auto_result._run
line.decode.rstrip
loop.create_future.done
cmd.append
_LazyEvalFunc
_exceptions.BoltProtocolError
NetworkUtil._dns_resolver
sync_main
hash
self._closed
_meta.deprecation_warn
database.self.routing_tables.should_be_purged_from_memory
Clock.local_offset
RecordExporter.transform
asyncio.ensure_future
clock.precision
urllib.parse.parse_qs
self.send_all
inst._labels.union
BoltSocket._connect
self.configuration_hints.update
copy.copy.with_traceback
BoltSocket._secure.setsockopt
Structure
self.is_reset_mock
cls.__normalize_minute
self.__time.tzname
neo4j._async_compat.util.AsyncUtil.list
self._wait_for_io
other.time.to_clock_time
exceptions.ResultConsumedError
asyncio.shield
self._experimental_options
self._results._buffer_all
connection_.stale
_days_in_year
asyncio.run
neo4j._async_compat.util.Util.iter
buffer.popleft
cls.parse_targets
self.__new
join
asyncio.StreamWriter
self._WAITERS_RE.search
asyncio.ensure_future.exception
resolved.append
neo4j.api.check_access_mode
it.__anext__
year.Date.to_ordinal
exceptions.IncompleteCommit
self.is_retryable
data.mark_item_as_read
backend.custom_resolutions.pop
self._acquire.closed
self.__class__
async_fake_connection_generator
tracemalloc.get_object_traceback
self._open_transaction
self._acquire_new_later
time.Time
UnpackableBuffer
pandas.DataFrame.apply
_spatial.Point
k.replace
self._buffer.pop_u16
_async_compat.network.AsyncBoltSocket.connect
neo4j.AsyncGraphDatabase.driver.supports_multi_db
self._reader.read
neo4j._async_compat.util.AsyncUtil.iter
cls.close
self._writer.wait_closed
self._socket.gettimeout
OverflowError
exceptions.SessionError
neo4j.AsyncGraphDatabase.driver.session
Exception
logging.StreamHandler.setLevel
len
self._transaction._begin
pandas.DataFrame
e.update
super._connect
datetime.timedelta
self._record_buffer.extend
database.self.routing_tables.readers.discard
_async.backend.AsyncBackend.process_request
asyncio.create_task
os.environ.get.lower
self.responses.popleft
ServerStateManager
io.StringIO
self.__year.Date.toordinal
self._deprecated_keys
self.__date.replace
warnings.catch_warnings
x.items
self.kill
DateTime.utc_now
bookmarks_consumer
super.__new__
pathlib.Path
_async_compat.concurrency.AsyncCooperativeRLock
self._utc_offset
cls.bolt_driver
packstream.Structure
merge_deadlines
ssl_kwargs.update
logging.StreamHandler
self.to_timeout
neo4j.exceptions.ServiceUnavailable
self.watch
neo4j.time.Time
urllib.parse.urlparse
Watcher
keys.append
sys.path.insert
attributes.items
s.startswith
resolver
logging.getLogger.error
build_message_handler
_routing.RoutingTable
self.timetz.utc_offset
value.type.dehydration_hooks
hooks.keys
_sync.backend.Backend
addressing.ResolvedAddress
_get_skip_reason
DateTime.combine
pytest.fixture
self.unpackable.reset
self._transaction._rollback
typing.TypeVar
isinstance
neo4j.GraphDatabase.bookmark_manager
day.month.year.date.toordinal
to
server.Server
self.utcoffset
_deadline.Deadline.from_timeout_or_deadline.to_timeout
offered_versions.version.version.to_bytes.join.ljust
epoch.date.to_ordinal
v1.hydration_handler._GraphHydrator
self._exc_stems_from_driver
summary_metadata.get
t.replace.replace
self._super_getitem_single
metadata.get
DateTime.to_clock_time
result.AsyncResult._tx_end
tracemalloc.get_object_traceback.format
self._buffer.tmp_buffer
self._waiters.append
_normalize_day
neo4j.GraphDatabase.driver
kwargs.get
sum
message.deprecated
outer_async
retry_delay_generator
match.group.ljust
cls.utc_from_timestamp
self.responses.on_records
type.Date.DateTime.x.isinstance.col.map.all
self.goodbye
field
nanoseconds.abs.str.rjust
traceback.format_exc
neo4j._async_compat.util.Util.next
cls.from_clock_time
time.DateTime
self.__aiter__.__anext__
self.utc_time
bolt_cls
result.append
cls.__new
ctypes.CDLL
size.self.read.tobytes
property
neo4j.AsyncGraphDatabase.driver
ClockTime.date
point_class
exceptions.ClientError
connection_creator
inspect.signature
self._append
self._on_change
cls.__normalize_second
self.from_native.replace
_driver_logger.buffer_handler.stream.truncate
self._metadata.get
_driver_logger.buffer_handler.stream.getvalue.encode
bytearray
self._pull
self._seen_keys.add
SKIPPED_TESTS.items
connection.socket.set_deadline
UnixEpoch.Clock.utc_time.cls.from_clock_time.replace
database.self.routing_tables.writers.discard
pytz.utc.localize.toordinal
get_date_unix_epoch.toordinal
self.stop
logger.addHandler
_common.Structure.items
set.update
ValueError
closable.close
_async_compat.util.AsyncUtil.callback
db_context.update
Clock.__subclasses__
_common.InitResponse
neo4j.ServerInfo
transactionFunc
s.rpartition
logging.getLogger.info
self.get_or_create_routing_table.is_fresh
cb
self.code.startswith
mock.AsyncMock
divmod
dt.timetz
Time.from_native
self.to_clock_time
super._disconnect
self.routing_tables.keys
self._close
attributes.setdefault
logging.getLogger.warning
base._deprecated_alternatives
self._acquire
tuple
_async_compat.network.BoltSocket.close_socket
self.__date.iso_weekday
AsyncNetworkUtil._dns_resolver
cls._extract_error_class
self.sessions.items
self._buffer_one_chunk
ls.append
type.TypeVar
pool.acquired_connection_mocks.append
self.to_native
self._waiters.remove
self.__time._utc_offset
offset.self.replace.to_native
self.__keys.index
self._pool.release
hasattr
tx.run.keys
self._get_both_normalized
ord
_LazyEvalEnv
ssl.SSLContext.load_verify_locations
e.type
time.perf_counter
loop.create_future.set_result
self._connection.defunct
val.mark_all_as_read
to_tx_kwargs
_async_compat.sleep
self._metadata.update
self._process_message
neo4j.Bookmarks.from_raw_values
formatter_cls
os.path.join
globals
setuptools.setup
super.__iter__
self._connection.closed
json.loads
self.write_driver_exc
AttributeError
self._transaction._closed
asyncio.current_task.cancel
_common.Inbox
driver.session.execute_write
self.graph.relationship_type
warnings.warn
self.inbox.pop
deprecated_aliases.update
OSError
self.socket.kill
_data.RecordTableRowExporter.transform.keys
self._cancel
_conf.TrustAll
_async_compat.network.NetworkUtil.resolve_address
self._acquire.defunct
value.values
abs
_resolved_addresses_from_info
self.iso_format
pytz.FixedOffset.localize
self.transform.append
driver._pool.update_routing_table
BrokenHydrationObject
self.tzinfo.tzname
self.run
fromtestkit.to_query_and_params
epoch.date
_async_compat.concurrency.AsyncCooperativeLock
pool.buffered_connection_mocks.pop
self.fetch_routing_table
BoltSocket._secure.settimeout
self.settimeout
self._server_state_manager.transition
exceptions.WriteServiceUnavailable
self.utc_offset.total_seconds
warnings.simplefilter
backend.dns_resolutions.pop
totestkit.record
config_class._consume
self.mark_item_as_read
errors.append
self._STATE_TRANSITIONS.get
deprecated_options.update
ClockTime.toordinal
ERROR_REWRITE_MAP.get
cls.from_native.replace
handler
self.__eq__
rollback
self._obtain_summary
self._exit
neo4j.bearer_auth
asyncio.get_event_loop.getaddrinfo
self.__exit__
fromtestkit.to_cypher_and_params
auth_token.mark_item_as_read
ExperimentalOption
Auth
self._acquire.route
copy.copy
s.join.split
coro_function
cls.from_native
asyncio.get_running_loop.create_future
int.toordinal
ssl.SSLContext.load_default_certs
BoltSocket._secure.connect
self.pack_list_header
pytz.timezone
self._exhaust
_bolt.Bolt.open
seconds_and_nanoseconds
auth_token.get
self._connection.commit
_meta.experimental_warn
_common.CommitResponse
pytest.mark.skip
bookmarks_supplier
self._properties.values
self.time.to_clock_time.cast
socket.getservbyname
api.Bookmarks.from_raw_values
connections.append
self._loop.create_future
super.get_base_headers
addressing.Address.parse
_util.NetworkUtil.resolve_address
frozenset
version.to_bytes
self.HYDRATION_HANDLER_CLS
self._wr.flush
self.responses.popleft.on_failure
round
asyncio.get_running_loop
pytz.utc.localize
self._wrap_message
self._wait
self.hydration_handler.patch_utc
self.index
func
base._experimental_options
super.__init__
_async_compat.concurrency.AsyncCondition
_data.RecordTableRowExporter.transform
data.pop
_common.AsyncInbox
result.Result._tx_end
math.isinf
_data.Record
self._entity_dict.values
graph.Path
self.get_or_create_routing_table
_sanitize_deadline
e.invalidates_all_connections
_async_compat.util.Util.callback
iterable.keys
self.timetz
typing
database_callback
cls.from_clock_time.to_native
super.__setattr__
datetime.date.fromordinal
neo4j._async_compat.shims.wait_for
_driver_logger.log.debug
self._close_connections
_days_in_month
self._acquire_from_pool
getattr
re.match
_async_compat.network.BoltSocket.connect
error_class
bookmarks.append
self._lock.release
self.time
__file__.Path.absolute
OrderedSet
record.value
self.update_routing_table
cls.combine
DURATION_ISO_PATTERN.match.group
self.utc_offset
main
self.date
commit
self.tzinfo.dst
any
self._connection.fetch_message
dict.fromkeys
get_date_unix_epoch.to_ordinal
self._deprecated_options
bookmark_manager.AsyncNeo4jBookmarkManager
session.run.single
base._deprecated_aliases
self._connection.run
cls.__normalize_hour
self._buffer_all
self.Server.super.__init__
parts.insert
json.load
json.dumps
self.update_connection_pool
self.values
pytest.fail
backend.send_response
self.__update
self._consume_results
_conf.PoolConfig.get_ssl_context
close
</pre>
</details>

@developer
Could please help me check this issue?
May I pull a request to fix it?
Thank you very much.

**Comment by robsdedude** [comment]
Since `pytz`
 * is not likely to change its API
 * does not follow semver (=> not possible to pin to any non-breaking version range without cutting off too much)
 * ships with its own timezone database, which we want to be as up-to-date as possible
 
we deliberately do not pin the version to anything.
