### ISSUE TITLE
Bolt Driver does not work in Python 3.5

### ISSUE THREAD

**Issue by ReedJessen** [neo4j/neo4j-python-driver#87]
The following code is sourced from the [ReadMe](neo4j-python-driver/README.rst) page and works in Python 2.7 after installing neo4j-driver.

``` python
from neo4j.v1 import GraphDatabase, basic_auth

driver = GraphDatabase.driver("bolt://hobby-kfkdjimaoibhgbkeccpmfcnl.dbs.graphenedb.com:24786",
                              auth=basic_auth("IPStreetSandbox", "qF1yZ85Y2nb30STRNLdo"))
session = driver.session()
session.run("CREATE (a:Person {name:'Bob'})")
result = session.run("MATCH (a:Person) RETURN a.name AS name")
for record in result:
    print(record["name"])
session.close()
```

When running the same code in Python 3.5 after installing neo4j-driver, I get the following error:

```
Traceback (most recent call last):
  File "C:/PythonApps/Neo4jBoltDriverTest/run.py", line 1, in <module>
    from neo4j.v1 import GraphDatabase, basic_auth
  File "C:\Users\username\AppData\Local\Programs\Python\Python35\lib\site-packages\neo4j\__init__.py", line 29, in <module>
    from neo4j.core import GraphDatabase, Direction, NotFoundException, BOTH, ANY, INCOMING, OUTGOING
  File "C:\Users\username\AppData\Local\Programs\Python\Python35\lib\site-packages\neo4j\core.py", line 19, in <module>
    from _backend import *
ImportError: No module named '_backend'
```

The[ setup.py](neo4j-python-driver/setup.py) file lists up to python 3.4 but not python 3.5 which I expect is reason for this error.  Is this correct?  If so, is there a timeline for when the library will be support python 3.5?

**Comment by technige** [comment]
I'm confused. There is no module called `neo4j.core` in this driver. Where did you install from?

**Comment by ReedJessen** [comment]
I use pycharm as an IDE.  I installed neo4j-driver from their package manager.
![neo4j-driver](https://cloud.githubusercontent.com/assets/12887285/18330826/a9d97fc2-750f-11e6-8471-f03fc46d969c.JPG)

**Comment by ReedJessen** [comment]
I am not sure what the problem is but I can confirm that it is on my side.  I created a new Python 3.5 VirtualEnv, installed neo4j-driver, and the demo code now works in Python 3.5.  Basically a case of poor package management on my part.  

Thanks for your help.  I am sorry if I caused you any stress or headaches.

**Comment by technige** [comment]
No problem here. Glad you got it solved.
