### ISSUE TITLE
Interacting with database from pure python?

### ISSUE THREAD

**Issue by eregen** [neo4j/neo4j-python-driver#880]
Is it possible to interact with a neo4j database, create an instance, update it with new data, or delete an instance entirely from a python script?

**Comment by robsdedude** [comment]
Hello and thanks for reaching out.

I'll quote the issue template

> If you are unsure about the usage of the driver, this issue tracker is not
> the right place to ask. Please use one of the following channels instead:
>
> - Neo4j Online Community: https://community.neo4j.com/
> - StackOverflow: https://stackoverflow.com/questions/tagged/neo4j+python
> - Discord: https://discord.gg/neo4j
> - Neo4j Support Portal if you are an enterprise customer:
>   https://support.neo4j.com/

With that said, it should be possible by writing a wrapper that starts a neo4j server. You could for example use libraries that interact with docker to start a dockerized server. This is certainly beyond the scope of the driver :)
