### ISSUE TITLE
Any plans for providing instrumentation via open telemetry?

### ISSUE THREAD

**Issue by MrwanBaghdad** [neo4j/neo4j-python-driver#888]
# Feature Request

As the title indicates, I'm wondering if there're any plans to integrate provide instrumentation via open telemetry (Otel)

# Pitch
- Otel provides a lean SDK with the support of multiple exporters. Neo4j can provide the auto instrumentation once and let end users choose which tracing backend. For example, integration with datadog would be pushed as a concern to Otel implementation.
- For end users, it allows better performance observability

**Comment by robsdedude** [comment]
Hi @MrwanBaghdad and thanks for reaching out.

We have already been internally discussing if and how telemetry support in the drivers could be added ([internal Trello link](https://trello.com/c/Ap9KojWJ)). As it stands right now, this topic is not on the roadmap but that might change in the future. I will close this issue as we are aware of the feature request and are tracking it internally. If you have further questions, please feel free to keep commenting. I will keep you updated here as the feature progresses.

Other users that come across this and are also interested in this feature please leave a :+1: on the issue so we can see how big the demand is.

**Comment by MrwanBaghdad** [comment]
Hi @robsdedude, thanks for your prompt reply. 
I'm happy to hear that it's been discussed internally. 
I can't access the internal Trello link you provided, is there any other medium that I can follow up on the discussion? Thanks

**Comment by robsdedude** [comment]
> I can't access the internal Trello link you provided, is there any other medium that I can follow up on the discussion? Thanks

Sorry about that. I mainly put the link there as a cross reference for our team. The Trello wall is considered internal information. So far the discussion didn't go much further than investigating different frameworks/tools for adding telemetry support. If you have input beyond Otel would be a great fit (which we already took note of), feel free to leave it here and I'll make sure to take it to the team for consideration.
