### ISSUE TITLE
Getting json output in the format I want

### ISSUE THREAD

**Issue by Winchester37** [neo4j/neo4j-python-driver#899]
I want to get results like below using fastapi and neo4j, but none of the results give me this result or I couldn't find it. Do I need to write a separate function for this?

`{
    "results": [
        {
            "columns": ["user", "entity"],
            "data": [
                {
                    "graph": {
                        "nodes": [
                            {
                                "id": "1",
                                "labels": ["User"],
                                "properties": {
                                    "userId": "eisman"
                                }
                            },
                            {
                                "id": "8",
                                "labels": ["Project"],
                                "properties": {
                                    "name": "neo4jd3",
                                    "description": "Neo4j graph visualization using D3.js.",
                                    "url": "https://eisman.github.io/neo4jd3"
                                }
                            }
                        ],
                        "relationships": [
                            {
                                "id": "7",
                                "type": "DEVELOPES",
                                "startNode": "1",
                                "endNode": "8",
                                "properties": {
                                    "from": 1470002400000
                                }
                            }
                        ]
                    }
                }
            ]
        }
    ],
    "errors": []
}`

**Comment by robsdedude** [comment]
Hi and thanks for reaching out.

Yes, you will have to write your own serializer. If you get stuck doing so, I recommend reaching out to the common places for support

 - Neo4j Online Community: https://community.neo4j.com/
 - StackOverflow: https://stackoverflow.com/questions/tagged/neo4j+python
 - Discord: https://discord.gg/neo4j
 - Neo4j Support Portal if you are an enterprise customer:
   https://support.neo4j.com/

or check the documentation:

 - API documentation: https://neo4j.com/docs/api/python-driver/current/
 - Driver manual: https://neo4j.com/docs/python-manual/current/
