### ISSUE TITLE
Session is lost when Neo4j is restarted

### ISSUE THREAD

**Issue by ayosec** [neo4j/neo4j-python-driver#92]
With version 1.0.2, the driver does not reconnect when the server closes its connection. This is an important issue because we have to reinitialize the session if we restart the Neo4j process.

Is it possible to create a new Bolt connection when the current one is lost?

The issue can be reproduced with the following script:

``` python
import os, socket, time
from neo4j.v1 import GraphDatabase, basic_auth

driver = GraphDatabase.driver("bolt://localhost", auth=basic_auth("neo4j", "neo4j"))
session = driver.session()

#1) Execute a query

for record in session.run("RETURN 1"):
  print("### Got a record; Restart Neo4j")

#2) Restart Neo4j

os.system("./neo4j-community-3.0.6/bin/neo4j restart")

#3) When Neo4j is ready, execute the next query

while True:
  try:
    socket.create_connection(("localhost", 7687)).close()
    break
  except socket.error:
    time.sleep(0.3)

print("### Bolt is ready to be used; driver should be able to reconnect")

for record in session.run("RETURN 1"):
  print("### It works!")

session.close()
```

This script produces the following output:

```
### Got a record; Restart Neo4j
Stopping Neo4j.. stopped
Starting Neo4j.
Started neo4j (pid 7595). By default, it is available at http://localhost:7474/
There may be a short delay until the server is ready.
See /h/neo4j-community-3.0.6/logs/neo4j.log for current status.
### Bolt is ready to be used; driver should be able to reconnect
Traceback (most recent call last):
  File "test.py", line 27, in <module>
    for record in session.run("RETURN 1"):
  File "/usr/local/lib/python2.7/dist-packages/neo4j/v1/session.py", line 232, in __iter__
    self.connection.fetch()
  File "/usr/local/lib/python2.7/dist-packages/neo4j/v1/connection.py", line 311, in fetch
    raw.writelines(self.channel.chunk_reader())
  File "/usr/local/lib/python2.7/dist-packages/neo4j/v1/connection.py", line 169, in chunk_reader
    chunk_header = self._recv(2)
  File "/usr/local/lib/python2.7/dist-packages/neo4j/v1/connection.py", line 152, in _recv
    raise ProtocolError("Server closed connection")
neo4j.v1.exceptions.ProtocolError: Server closed connection
```

**Comment by zhenlineo** [comment]
Hi,

I think you might consider adding error handling on the session rather than connection. If you keep the `driver` around, then you could easily create a new session from the driver. If you retry your statement in another session after the server already restated, then the statement will run successfully in this new session.

Is there any reason that you want to keep the session around? I do not think you could re-establish a connection for a session. But a new connection will be established when you obtain a new session from the driver.

Cheer,
Zhen

**Comment by technige** [comment]
The driver is not designed to reconnect when the database is restarted, I'm not aware of any other database drivers that would exhibit that behaviour for a persistent connection.

If either side closes the underlying connection (through a restart or any other mechanism), the session becomes invalid and the application should create a new session. One area where we are improving this process in the 1.1 series drivers is in a more consistent use of errors. Therefore in 1.1 you will see a `ServiceUnavailable` exception raised whenever the server goes away. You will then need to re-call `session = driver.session()` to reconnect.
