### ISSUE TITLE
Opening of the session throwing up error ([SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:590) error)

### ISSUE THREAD

**Issue by bhanu-sharma** [neo4j/neo4j-python-driver#96]
While following the python driver instruction code in the documentation, the running of the throws up this error:  
I am using Neo4j version 3.0.6 community edition. I have tried using version 3.1.0-M13-beta3 too but the problem still persists. I am currently using python version 2.7.12

```Traceback (most recent call last):  
 File "...\neo.py", line 6, in <module  
    session = driver.session()  
  File "C:\Python27\lib\site-packages\neo4j\v1\session.py", line 148, in session  
    session = Session(self)  
  File "C:\Python27\lib\site-packages\neo4j\v1\session.py", line 461, in __init__  
    self.connection = connect(driver.host, driver.port, driver.ssl_context, **driver.config)  
  File "C:\Python27\lib\site-packages\neo4j\v1\connection.py", line 418, in connect  
    raise error  
ProtocolError: Cannot establish secure connection; [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:590)

#Code
from neo4j.v1 import GraphDatabase, basic_auth
url = "bolt://localhost:7474"
driver = GraphDatabase.driver(url, auth=basic_auth("neo4j", "xxx"))
session = driver.session()

**Comment by zhenlineo** [comment]
Hi,

By default, Bolt protocol connects port 7687. So if you just download a neo4j server and connects a driver with it, you should use 7687 instead of 7474. Let me konw if you still have the problem after trying with port 7687 instead.

Cheers,
Zhen

**Comment by bhanu-sharma** [comment]
Thank you Zhen for responding so swiftly. 
It worked like a charm.

**Comment by zhenlineo** [comment]
Have fun with the driver. Then I am closing this issue. You are most welcome to open new ones if you get any other problem with the driver.
