### ISSUE TITLE
can i make wrapper about neo4j query?

### ISSUE THREAD

**Issue by shaan-lee** [neo4j/neo4j-python-driver#976]
https://github.com/shaan-lee/neo4j-manager

i feel problem to use neo4j query in python, so open the repo in my git
if you want, can i merge in neo4j-python-driver repo?
i will develop more function about this can work almost every query

**Comment by robsdedude** [comment]
Hi and thanks for reaching out.

What you linked looks like the beginning of an OGM (object-graph-mapper, based on the word ORM for relational databases). There are already some out there. I recommend you look around to see if there are any that suite your needs. One prominent example that comes to my mind is [neomodel](https://github.com/neo4j-contrib/neomodel).

Generally, there are quite a few things that are easy to get wrong when writing an OGM or ORM:
 * managing resource lifetimes
 * making sure not to be vulnerable to query injection
 * specifically for Neo4j: handling indexes and ids as there is no such thing as primary keys
 * ... the list goes on

This driver library is very unlikely to ever get support for anything like that. It's more low-level and is meant to enable wrapping it, just like you suggested, to create higher level frameworks. Currently, there is no Python OGM officially supported by Neo4j, though. Maybe this changes in the future.

I'll close the issue now, as we're not interested in merging it. But please feel free to:
 * keep working on your library, other users might be interested.
 * keep commenting here, if you have further thoughts.
